- component/component.yaml
Otherwise the component shows up as using the legacy 32bit API on Xamarin.iOS.
> Change ios package in Xamarin Component to unified

- wrappers/src/object-store/src/impl/android/external_commit_helper.cpp
- wrappers/src/object-store/src/impl/android/weak_realm_notifier.cpp
- wrappers/src/object-store/src/impl/android/weak_realm_notifier.hpp
WeakRealmNotifier's move assignment operator could be invoked on another thread so we need to make sure to remove ourselves from the looper always on the looper thread.
> Ensure thread safety in the Android WeakRealmNotifier

- wrappers/src/object-store/src/impl/android/weak_realm_notifier.cpp
We need to call write(2) with the address of the buffer, not the buffer itself, d'oh
> WeakRealmNotifier should use POSIX write correctly

- CHANGELOG.md
- Realm.PCL/RealmObjectPCL.cs
- Realm.Shared/MarshalHelpers.cs
- Realm.Shared/RealmObject.cs
- Realm.Shared/linq/RealmResultsVisitor.cs
- Realm.Shared/native/NativeQuery.cs
- Realm.Shared/native/NativeTable.cs
- RealmWeaver/ModuleWeaver.cs
- Tests/IntegrationTests.Shared/AccessTests.cs
- Tests/IntegrationTests.Shared/PeopleTestsBase.cs
- Tests/IntegrationTests.Shared/Person.cs
- Tests/IntegrationTests.Shared/SimpleLINQtests.cs
- Tests/IntegrationTests.Shared/TestObjects.cs
- wrappers/src/query_cs.cpp
- wrappers/src/table_cs.cpp
> Add support for byte[] properties

- wrappers/src/object-store/src/impl/generic/external_commit_helper.cpp
- wrappers/wrappers.vcxproj
- wrappers/wrappers.vcxproj.filters
This allows us to build wrappers with VS again. Note that the external commit helper is broken, but we're not using it on Windows anywhere so it doesn't break anything at the moment.
> Make wrappers build on Windows again

- Realm.Shared/RealmObject.cs
- Tests/IntegrationTests.Shared/StandAloneObjectTests.cs
> Standalone objects should not crash on equals

- Realm.Shared/Attributes.cs
- RealmWeaver/ModuleWeaver.cs
- Tests/IntegrationTests.XamarinAndroid/IntegrationTests.XamarinAndroid.csproj
- Tests/IntegrationTests.XamarinIOS/IntegrationTests.XamarinIOS.csproj
The Xamarin linker would mess up the parameter of the `WovenAttribute` constructor because the woven helper type had a namespace.
Fixes #577
> Fix woven code so that the Xamarin linker likes it

- RealmWeaver/ModuleWeaver.cs
- Tests/WeaverTests/AssemblyToProcess/TestObjects.cs
- Tests/WeaverTests/RealmWeaver.Tests/RealmWeaver.Tests.csproj
- Tests/WeaverTests/RealmWeaver.Tests/WeaverOptions.cs
- Tests/WeaverTests/RealmWeaver.Tests/WeaverTests.cs
- Tests/WeaverTests/RealmWeaver.Tests/packages.config
Hi folks,
I've added basic support for INotifyPropertyChanged, having checked out and experimented with Realm, I was hoping for something I could drop in next to my UI code and see live updates. This seems to do the trick.
I had initially tried to use PropertyChanged.Fody in conjunction with Realm, but once an object became managed, the early return short-circuited raising the property changed at the end of the setter.
This seems to be related to the following issue: https://github.com/realm/realm-dotnet/issues/253
Cheers,
Joe
> Add automatic support for INotifyPropertyChanged via weaver.

- CHANGELOG.md
- Realm.Shared/Realm.cs
Calling `Assembly.GetTypes()` on an assembly that is a `System.Reflection.Emit.AssemblyBuilder` throws an exception if any of the types in the assembly aren't fully built yet.
We don't care about dynamic assemblies because there's no way for them to be woven anyway.
> Ignore types from dynamic assemblies

- CHANGELOG.md
- NuGet/NuGet.Library/Realm.nuspec
- Realm.Shared/native/NativeCommon.cs
- Realm.Win32/Realm.Win32.csproj
- Realm.Win32/packages.config
- Realm.XamarinAndroid/Realm.XamarinAndroid.csproj
- Realm.XamarinAndroid/packages.config
- Realm.XamarinIOS/Realm.XamarinIOS.csproj
- Realm.XamarinIOS/packages.config
- Tests/IntegrationTests.XamarinAndroid/IntegrationTests.XamarinAndroid.csproj
- Tests/IntegrationTests.XamarinAndroid/packages.config
- Tests/IntegrationTests.XamarinIOS/Info.plist
- Tests/IntegrationTests.XamarinIOS/IntegrationTests.XamarinIOS.csproj
The notification payload on Realm collections contains generic structures that need to be marshalled. Mono JIT compiles the wrapper code that marshals a type that the AOT compiler hasn't emitted a `PtrToStructure`/`StructureToPtr` method pair for, but the AOT compiler does not do so for generic types as their size is only known when the generic is closed.
Fixes #620
> Fix `attempting to JIT compile` exception in Notifications API

- Realm.PCL/Properties/AssemblyInfo.cs
- Realm.PCL/Realm.PCL.csproj
- Realm.Win32/Properties/AssemblyInfo.cs
- Realm.Win32/Realm.Win32.csproj
- Realm.XamarinAndroid/Realm.XamarinAndroid.csproj
- Realm.XamarinIOS/Properties/AssemblyInfo.cs
- RealmAssemblyInfo.cs
- RealmWeaver/Properties/AssemblyInfo.cs
- RealmWeaver/RealmWeaver.Fody.csproj
Extract all the common parts of all the various AssemblyInfo files in a central one. This makes it easier to stamp versions in CI.
> Refactor and extract AssemblyInfo.cs files

- wrappers/wrappers.xcodeproj/project.pbxproj
> Disable debugging symbols for iOS wrappers in Release

- Tests/IntegrationTests.XamarinAndroid/Properties/AndroidManifest.xml
That way we can run headless unit tests in CI when building for Release.
> Make Android tests debuggable always

- Tests/IntegrationTests.XamarinAndroid/TestRunnerInstrumentation.cs
- Tests/IntegrationTests.XamarinIOS/Main.cs
On iOS we no longer rely on an environment variable, but on a command-line argument
> Change the way CI runs headless unit tests

- Tests/IntegrationTests.Shared/DateTimeTests.cs
DateTimeTests.cs
- SortingFinelyDifferentDateTimes use ToUnixTimeMilliseconds instead of our private offset variation.
> Trivial test change to run unit tests with NuGet

- CHANGELOG.md
- wrappers/src/object-store/src/impl/apple/weak_realm_notifier.cpp
> Check if a Realm is closed before notifying on iOS

- CHANGELOG.md
- Realm.Shared/Schema/ObjectSchema.cs
- Realm.Shared/Schema/RealmSchema.cs
- internals/Realm-dotnet Code Change Diary - Andy Dent.txt
ObjectSchema.cs
- Builder.Build - throw message identifying bad schema name with URL for docs
RealmSchema.cs
- Builder.Build - throw message saying no RealmObjects, with URL for docs
> #739 Better empty schema exception messages

- CHANGELOG.md
- Realm.Shared/exceptions/RealmException.cs
- Realm.Shared/exceptions/RealmExceptionCodes.cs
- Tests/IntegrationTests.Shared/ConfigurationTests.cs
- Tests/IntegrationTests.Shared/RealmMigrationTests.cs
- internals/Realm-dotnet Code Change Diary - Andy Dent.txt
- wrappers/src/error_handling.cpp
- wrappers/src/realm_error_type.hpp
Minor change just to catch the exception currently being thrown from ObjectStore and map it to our desire C# exception.
@fealebenpae or @kristiandupont please review
**NOTE** this does **not** fix our `MigrationTriggersDelete` test as that crashes due to schema issues.
> Ad/bug migration needed exception #507

- Tests/IntegrationTests.Shared/RelationshipTests.cs
- Tests/IntegrationTests.Shared/StandAloneObjectTests.cs
so we don't give people the idea it is needed.
Reformatted to undo the effects of Xamarin Studio silly settings at a previous edit.
@kristiandupont please review, just test changes, no functional changes so no changelog entry.
> Remove ToList from expressions mostly in RelationshipTests

- Realm.PCL/RealmListPCL.cs
- Realm.Shared/Realm.cs
- Realm.Shared/RealmList.cs
- Realm.Shared/RealmObject.cs
- Realm.Shared/RealmObjectOps.cs
- Realm.Shared/linq/RealmResults.cs
- Realm.Shared/linq/RealmResultsEnumerator.cs
- Realm.Shared/linq/RealmResultsProvider.cs
- Realm.Shared/linq/RealmResultsVisitor.cs
- internals/Realm-dotnet Code Change Diary - Andy Dent.txt
adding back in after was removed prior to 0.77.1, plus some fixes
@fealebenpae and @kristiandupont this is essentially what was reviewed and passed as #742 but that had a nasty recursive bug which has required a few minor changes in this PR.
Realm.cs
- MakeObjectForRow overload added to take a RealmObject.Metadata instead of doing lookup, and simple rowPtr
- MakeObjectForRow original taking string, changed to take rowPtr for second arg and forward to new overload
- MakeResultsForTable take metadata instead of class name
- MakeSortOrderForTable take metadata instead of class name
- All(both overloads) - lookup metadata for RealmResults
RealmList.cs
- RealmList
- added field _targetMetadata
- use new MakeObjectForRow
- IRealmList.SchemaClassName removed
- _schemaClassName removed
- ctor …
> Refactoring MakeObject logic to assist ObjectID work and reduce lookups

- Realm.PCL/Realm.PCL.csproj
- Realm.Shared/Realm.Shared.projitems
- Realm.Shared/RealmObject.cs
- Realm.Shared/exceptions/RealmDuplicatePrimaryKeyValueException.cs
- Realm.Shared/exceptions/RealmException.cs
- Realm.Shared/exceptions/RealmExceptionCodes.cs
- Realm.Shared/native/NativeTable.cs
- Tests/IntegrationTests.Shared/PrimaryKeyTests.cs
- internals/Realm-dotnet Code Change Diary - Andy Dent.txt
- wrappers/src/error_handling.cpp
- wrappers/src/error_handling.hpp
- wrappers/src/realm_error_type.hpp
- wrappers/src/table_cs.cpp
@kristiandupont please review
Has exception handling with a new exception from OS as discussed
RealmDuplicatePrimaryKeyValueException.cs
- added
RealmExceptionCodes.cs
- RealmDuplicatePrimaryKeyValue added
RealmExceptions.cs
- Create - map RealmDuplicatePrimaryKeyValue to RealmDuplicatePrimaryKeyValueException
wrappers/realm_error_type.hpp
- RealmDuplicatePrimaryKeyValue added
wrappers/error_handling.hpp
- add decl of SetDuplicatePrimaryKeyValueException
wrappers/error_handling.cpp
- map the existing objectstore DuplicatePrimaryKeyValueException and  SetDuplicatePrimaryKeyValueException to RealmDuplicatePrimaryKeyValue
wrappers/table_cs.cpp
- table_set_int64_unique and  table_set_string_unique
change return type to bool and check if key already exists
- table_set_null throw …
> Ad/bug/same primarykey should throw #655

- CHANGELOG.md
- Realm.Shared/linq/RealmResultsVisitor.cs
- Tests/IntegrationTests.Shared/RealmResults/SimpleLINQtests.cs
- Tests/IntegrationTests.XamarinIOS/IntegrationTests.XamarinIOS.csproj
- internals/Realm-dotnet Code Change Diary - Andy Dent.txt
Fairly mechanical extension except ran into a weird LINQ behaviour at the top level - the lambda converts a literal char on the RHS into an `Int32` them wraps the character property on the LHS in a `Convert` which needed unpacking as a `UnaryExpression`. A nice side-effect is that also fixes errors if people use a different int type from their property, which has already caused at least one user bug report.
Branched off the `more-elements` branch rather than master as I expect to do a bunch of LINQ work before people have time to review, with absences this week.
@fealebenpae please review if you have time.
> Ad/linq/feature/char queries #708

- CHANGELOG.md
- Realm.Shared/Realm.cs
- Tests/IntegrationTests.Shared/PrimaryKeyTests.cs
- internals/Realm-dotnet Code Change Diary - Andy Dent.txt
@kristiandupont  please review
PrimaryKeyTests.cs
- PrimaryKeyFailsIfClassNotinRealm added
- DontFindByStringPrimaryKey added
- DontFindByInt64PrimaryKey added
- DontFindDynamicByInt64PrimaryKey added
- DontFindDynamicByStringPrimaryKey added
Realm.cs
- ObjectForPrimaryKey - all variations
- check for rowPtr returned as zero and return null to indicate not found
> #833 ObjectForPrimaryKey possible failure with interfaces

- RealmWeaver/ModuleWeaver.cs
- Tests/WeaverTests/AssemblyToProcess/FaultyClasses.cs
- Tests/WeaverTests/RealmWeaver.Tests/WeaverTests.cs
Also, add a unit test for unsupported properties.
Fixes #686
> Add a weaver warning when using DateTime? property

- Realm.Shared/Handles/ObjectHandle.cs
- Realm.Shared/RealmList.cs
- Realm.Shared/handles/LinkListHandle.cs
- Realm.Shared/handles/QueryHandle.cs
- Realm.Shared/linq/RealmResultsVisitor.cs
- wrappers/src/linklist_cs.cpp
- wrappers/src/object_cs.cpp
- wrappers/src/object_cs.hpp
- wrappers/src/query_cs.cpp
A follow-up to #866 - this removes the now-unnecessary `RowIndex` from the newly created `ObjectHandle`.
> Remove RowIndex from ObjectHandle

- Weaver/RealmWeaver.Fody/ModuleWeaver.cs
- Weaver/WeaverTests/AssemblyToProcess/FaultyClasses.cs
- Weaver/WeaverTests/RealmWeaver.Tests/WeaverTests.cs
@kristiandupont @fealebenpae do you think this should be a warning or an error?
Resolves #870
> Add weaver warning when applying realm attributes to non-persisted properties

- Platform.Win32/Tests.Win32/RunSpecificTest.cs
- Platform.XamarinIOS/Tests.XamarinIOS/RunLoopTests.cs
- Shared/Tests.Shared/AccessTests.cs
- Shared/Tests.Shared/AddOrUpdateTests.cs
- Shared/Tests.Shared/DateTimeTests.cs
- Shared/Tests.Shared/DynamicAccessTests.cs
- Shared/Tests.Shared/DynamicRelationshipTests.cs
- Shared/Tests.Shared/GetPrimaryKeyTests.cs
- Shared/Tests.Shared/InstanceTests.cs
- Shared/Tests.Shared/NotificationTests.cs
- Shared/Tests.Shared/PeopleTestsBase.cs
- Shared/Tests.Shared/PerformanceTests.cs
- Shared/Tests.Shared/PrimaryKeyTests.cs
- Shared/Tests.Shared/RealmResults/LINQvariableTests.cs
- Shared/Tests.Shared/RealmResults/SimpleLINQtests.cs
- Shared/Tests.Shared/RealmResults/SortingTests.cs
- Shared/Tests.Shared/RelationshipTests.cs
- Shared/Tests.Shared/StandAloneObjectTests.cs
- Weaver/WeaverTests/AssemblyToProcess/TestObjects.cs
- Assert that all column types default to the .NET defaults (except DateTimeOffset)
- Assert that non-unique object ids throw
- Rename Setup to SetUp
Resolves #347
> Minor test improvements

- Platform.PCL/Realm.PCL/RealmObjectPCL.cs
- Shared/Realm.Shared/Realm.Shared.projitems
- Shared/Realm.Shared/RealmObject.cs
- Shared/Realm.Shared/ReflectableType/RealmObjectTypeInfo.cs
- Shared/Realm.Shared/ReflectableType/WovenGetterMethodInfo.cs
- Shared/Realm.Shared/ReflectableType/WovenPropertyInfo.cs
- Shared/Tests.Shared/ReflectableTypeTests.cs
- Shared/Tests.Shared/RelationshipTests.cs
- Shared/Tests.Shared/TestObjects.cs
- Shared/Tests.Shared/Tests.Shared.projitems
- examples/QuickJournal/QuickJournal/EntryMetadata.cs
- examples/QuickJournal/QuickJournal/JournalEntry.cs
- examples/QuickJournal/QuickJournal/QuickJournal.csproj
- examples/QuickJournal/QuickJournal/ViewModels/JournalEntriesViewModel.cs
- examples/QuickJournal/QuickJournal/Views/JournalEntriesPage.xaml
The problem stems from the fact that Xamarin.Forms tries to apply the binding, even after an object is removed. This causes our RealmObject to try query core about the relationship, which obviously fails. While our behavior is semantically correct - you shouldn't try to get properties of a detached object, we should play nicer with Forms.
The proposed solution is to implement `IReflectableType` which Forms [respects](https://github.com/xamarin/Xamarin.Forms/blob/f252238fec90d8f71b49e35212275b9e588964e3/Xamarin.Forms.Core/BindingExpression.cs#L125). Then, replace the getter of the property info with a custom one, that will check if the object is valid and if it's not, return the default value.
The methods we should overrider are [`TypeInfo.GetDeclaredProperty`](https://github.com/xamarin/Xa …
> Don't crash when binding to removed object with relationship

- CHANGELOG.md
- Shared/Realm.Shared/Handles/QueryHandle.cs
- Shared/Realm.Shared/Linq/RealmResultsVisitor.cs
- Shared/Tests.Shared/RealmResults/SimpleLINQtests.cs
- wrappers/src/query_cs.cpp
Theoretically, we support case-insensitive contains as well, but .NET's `.Contains` doesn't 🙄 Perhaps we could provide an extension method that we can use to proxy for our needs? @kristiandupont 
Resolves #794
> Add support for .Equals/.StartsWith/.EndsWith ignore case queries

- Platform.PCL/Realm.PCL/RealmObjectPCL.cs
- Shared/Realm.Shared/Handles/SharedRealmHandle.cs
- Shared/Realm.Shared/Linq/RealmResults.cs
- Shared/Realm.Shared/Realm.cs
- Shared/Realm.Shared/RealmConfiguration.cs
- Shared/Realm.Shared/RealmObject.cs
- Shared/Realm.Shared/native/NativeCommon.cs
- Shared/Tests.Shared/NotificationTests.cs
- Shared/Tests.Shared/PropertyChangedTests.cs
- Shared/Tests.Shared/Tests.Shared.projitems
- Weaver/RealmWeaver.Fody/ModuleWeaver.cs
- Weaver/WeaverTests/AssemblyToProcess/TestObjects.cs
- Weaver/WeaverTests/Realm.FakeForWeaverTests/RealmObject.cs
- Weaver/WeaverTests/RealmWeaver.Tests/WeaverTests.cs
- wrappers/src/object_cs.cpp
- wrappers/src/object_cs.hpp
- wrappers/src/shared_realm_cs.cpp
- wrappers/src/shared_realm_cs.hpp
TODO:
Resolves https://github.com/realm/realm-dotnet/issues/886
> Handle change notifications originating from Core

- Jenkinsfile
- Shared/Tests.Shared/TestHelpers.cs
When the instrumented unit test runner crashes, the exit code of `adb shell` is still zero so the build isn't failed.
This checks the `INSTRUMENTATION_RESULT` output of `am instrument` and fails the build if the instrumentation errors out, while archiving the logcat output in case of error.
Fixes #946
> Handle crashes in Android tests

- Platform.PCL/Realm.Sync.PCL/Realm.Sync.PCL.csproj
- Platform.PCL/Realm.Sync.PCL/UserPCL.cs
- Shared/Realm.Sync.Shared/Handles/SharedRealmHandleExtensions.cs
- Shared/Realm.Sync.Shared/Realm.Sync.Shared.projitems
- Shared/Realm.Sync.Shared/User.cs
- Shared/Realm.Sync.Shared/UserPersistenceMode.cs
- wrappers/src/sync_manager_cs.cpp
which allows a custom encryption key for the sync metadata realm to be provided on Android since we cannot use the AndroidKeyStore because of its version requirements
Closes #975
> API to control user persistence

- Platform.PCL/Realm.PCL/RealmPCL.cs
- Shared/Realm.Shared/Handles/SharedRealmHandle.cs
- Shared/Realm.Shared/Realm.cs
- Shared/Tests.Shared/InstanceTests.cs
- Shared/Tests.Shared/TestObjects.cs
- Shared/Tests.Sync.Shared/SynchronizedInstanceTests.cs
- Shared/Tests.Sync.Shared/Tests.Sync.Shared.projitems
- wrappers/src/shared_realm_cs.cpp
Resolves #967 
Waiting for #976 - should be a small fix, so better to have it in.
Docs are updated for Compact.
> Add Realm.Compact

- Shared/Realm.Shared/native/SynchronizationContextEventLoopSignal.cs
Happens on device where no-JIT policy is enforced by the OS.
> Apply [UnmanagedFunctionPointer] to EventLoopPostHandler to fix JIT crash

- Weaver/RealmWeaver.Fody/Extensions/AssemblyResolverExtensions.cs
- Weaver/RealmWeaver.Fody/ModuleWeaver.cs
- Weaver/RealmWeaver.Fody/RealmWeaver.Fody.csproj
Build fails on PCL projects because `Enumerable.Empty` and `.AsQueryable` are not found.
> Fix PCL linq methods lookup

- Platform.PCL/Realm.PCL/RealmObjectPCL.cs
- Shared/Realm.Shared/RealmObject.cs
- Shared/Tests.Shared/PropertyChangedTests.cs
This allows users to hook into PropertyChanged and plug their own logic there. I designed it mostly for raising `PropertyChanged` on computed properties. This came up while working on #1046 - we have a `StatusCode` and we want to proxy it to a more human-readable enum and have it raise `PropertyChanged`.
> Add a virtual OnPropertyChanged method

- Shared/Tests.Shared/PropertyChangedTests.cs
This adds a slight delay for the `ManagedObject_WhenAnotherThreadInstanceChanged` test case, since it seems to fail every once in a while.
> Attempt to fix sporadically failing test

- Shared/Tests.Shared/ObjectIntegrationTests.cs
As far as I could see, we had nothing covering this particular scenario - can we write immediately after a rollback? The test worked, which I think also proves we can close #851 (see discussion in the comments on that issue.)
> Test added for scenario we didn’t cover, as part of checking issue #851

- Platform.PCL/Realm.Sync.PCL/UserPCL.cs
Followup to prematurerly closed PR where I forgot to add PCL version of comment update.
Whilst doing that and difffing PCL version, realised GetHashCode was missing.
> Add PCL comment changes for User.Current and missing GetHashCode

- Platform.PCL/Realm.Sync.PCL/Permissions/PermissionChangePCL.cs
- Platform.PCL/Realm.Sync.PCL/Permissions/UserPermissionsExtensionsPCL.cs
- Platform.PCL/Realm.Sync.PCL/Realm.Sync.PCL.csproj
- Shared/Realm.Sync.Shared/Permissions/IPermissionObject.cs
- Shared/Realm.Sync.Shared/Permissions/ManagementObjectStatus.cs
- Shared/Realm.Sync.Shared/Permissions/PermissionChange.cs
- Shared/Realm.Sync.Shared/Permissions/UserPermissionsExtensions.cs
- Shared/Realm.Sync.Shared/Realm.Sync.Shared.projitems
- Shared/Tests.Sync.Shared/Constants.cs
- Shared/Tests.Sync.Shared/PermissionsTests.cs
- Shared/Tests.Sync.Shared/Tests.Sync.Shared.projitems
- Weaver/RealmWeaver.Fody/ModuleWeaver.cs
Previously, it was wrongly implied you could modify a PermissionChange after adding it to the Realm. That is not the case, so I've made all setters private and exposed a constructor similar to what we have in Cocoa.
Additionally, I've exposed a `ManagementObjectStatus` enum to make it friendlier to check the status of the request.
Finally, I've created an explicit unit test to verify that permissions are actually processed and we get notified about it.
> Make PermissionChange immutable

- wrappers/src/sync_manager_cs.cpp
Metadata encryption relies on the Keychain APIs on iOS but those behave erratically on the Simulator when the app is not explicitly signed with a keychain access group entitlement, even those the exact same app works fine on a device.
This causes spurious failures on CI when testing on an iOS Simulator so better turn it off for the time being.
> Turn off sync metadata encryption on the iOS Simulator

- Shared/Tests.Shared/AddOrUpdateTests.cs
- Weaver/RealmWeaver.Fody/ModuleWeaver.cs
- clear to-many relationship lists
- only force setting of properties when not-setting PK (e.g. 100% updating)
Motivation for the weaver change (from `update || non-default` to `!setPrimaryKey || non-default`):
`setPrimaryKey` is always true when `update` is false - we always create a new object in that case. However, if we did create a new object, even though `update` was true (i.e. existing object with that PK was not found), `setPrimaryKey` will also be true, allowing us to optimize that case as well.
Closes #1037 
Closes #1038
> Fix a NRE when adding an object with a non-accessed list

- Shared/Tests.Shared/AddOrUpdateTests.cs
Test scenario confirms that the repeated updates don't add items in the IList.
> Added extra test for case in #1102 to confirm that it is fixed by #1040

- Shared/Tests.Sync.Shared/Constants.cs
- Shared/Tests.Sync.Shared/PermissionsTests.cs
Also add a check there's no error after opening a shared realm.
> Improve permission test reliability.

- Shared/Realm.Sync.Shared/Permissions/PermissionChange.cs
- Shared/Realm.Sync.Shared/Permissions/PermissionOffer.cs
- Shared/Realm.Sync.Shared/Permissions/PermissionOfferResponse.cs
- Shared/Tests.Sync.Shared/PermissionsTests.cs
Based on the [ROS release notes](https://github.com/realm/realm-object-server/blob/master/CHANGELOG.md#breaking-changes-1), objects in the management realm have PKs now, so this change is to accommodate that.
> Designate ids as PK for permission objects

- Jenkinsfile
Wrap `xbuild` calls in try-catch and ignore mono gc assertions. Those are caused by stylecop, which means that the build was successful.
> Don't fail the build if stylecop crashes

- Platform.PCL/Realm.Sync.PCL/Permissions/PermissionOfferPCL.cs
- Shared/Realm.Sync.Shared/Permissions/PermissionOffer.cs
#1139 was merged prematurely which causes build failures due to stylecop violations.
> Fix stylecop error

- Shared/Tests.Shared/TestHelpers.cs
`NUnit.Framework.TestContext.CurrentContext.TestDirectory` doesn't produce the correct directory on iOS devices:
This is the returned (incorrect) location:
```
/private/var/containers/Bundle/Application/9FDCAEBE-D0B1-4DA8-8825-6A11239F8D1C/Tests.XamarinIOS.app/.monotouch-64
````
whereas `NSBundle.MainBundle.BundlePath` returns the correct:
```
/var/containers/Bundle/Application/9FDCAEBE-D0B1-4DA8-8825-6A11239F8D1C/Tests.XamarinIOS.app
```
Both return the correct path on simulators, but that doesn't help much when testing on device.
> Use NSBundle for iOS devices

- Jenkinsfile
This allows the temp files created during testing to be easily deleted with the rest of the Jenkins workspace.
> Redirect the temp folder when running Windows tests

- NuGet/Realm.Database/Realm.Database.targets
- NuGet/Realm/Realm.nuspec
- NuGet/Realm/Realm.targets
Make sure we always use forward slashes, because Windows (fixes #1169).
Refactor the MSBuild code that includes realm-wrappers in user projects.
> Cleanup NuGet targets files

- wrappers/src/shared_realm_cs.cpp
The current notification implementation has a bug where while iterating, we can delete objects, effectively getting pointers to invalid memory. This was then passed to managed where we attempt to create a GCHandle from the pointer, resulting in a crash. This PR creates a temporary vector to store the pointers.
Fixes #1207
> Fix notification crash

- Shared/Realm.Shared/Realm.cs
- Shared/Realm.Shared/native/NativeCommon.cs
- wrappers/src/shared_realm_cs.cpp
- wrappers/src/shared_realm_cs.hpp
> Do not mutate the Realm managed state on the finalizer thread

- CHANGELOG.md
- NuGet/Realm.Database/Realm.Database.targets
The path should always point to the location of the `Realm.Database` package and should not be affected by the presence of the `Realm` package like the iOS and Android wrappers because `Realm` doesn't provide Win32 wrappers.
Fixes #1239
> Win32 wrappers path should not be dynamic

- CHANGELOG.md
- Platform.PCL/Realm.Sync.PCL/CredentialsPCL.cs
- Shared/Realm.Sync.Shared/Credentials.cs
> Add azuread provider

- Weaver/Realm.BuildTasks/Realm.BuildTasks.csproj
- Weaver/Realm.BuildTasks/WeaveRealmAssembly.cs
- Weaver/Realm.BuildTasks/packages.config
Make skipping logic more robust
- Uses Cecil from Nuget - means we're compatible with XF's version of Cecil, which may get loaded into the appdomain before ours, so that caused a very obscure build error.
- Ensures we're not falsely skipping weaving - if the user project references but doesn't use realm, we would incorrectly ignore it.
> More fixes related to BuildTasks

- Jenkinsfile
Just a simple reordering of the steps so we fail sooner if there are issues. It also mitigates congestion of CI a little bit.
> Reorder pipeline to test sooner rather than later

- CHANGELOG.md
- Realm/Realm.Sync/Handles/SessionHandle.cs
- Realm/Realm.Sync/Helpers/AuthenticationHelper.cs
- Realm/Realm.Sync/Session.cs
- Tests/Tests.Sync.Shared/SessionTests.cs
- wrappers/src/sync_session_cs.cpp
> Properly return null for session's user when the session is invalid

- CHANGELOG.md
- Tests/Tests.Shared/CollectionTests.cs
- wrappers/src/results_cs.cpp
> Throw exception when accessing an out of range item from RealmResults

- Platform.PCL/Realm.PCL/RealmPCL.cs
- Platform.PCL/Realm.Sync.PCL/Realm.Sync.PCL.csproj
A redundant reference (since we already depend on Realm, we can use the original helper) and a using statement to correctly resolve the xml reference.
> Cleanup some PCL warnings

- CHANGELOG.md
- Platform.PCL/Realm.Sync.PCL/SessionPCL.cs
- Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs
- Realm/Realm.Sync/Session.cs
- wrappers/src/sync_manager_cs.cpp
> Expose OS’s reconnect method

- CHANGELOG.md
- Realm/Realm/MarshalHelpers.cs
> fix a leak when marshalling strings

- CHANGELOG.md
- Realm/Realm/Handles/CollectionHandleBase.cs
- Realm/Realm/Handles/ListHandle.cs
- Realm/Realm/Handles/NotifiableObjectHandleBase.cs
- Realm/Realm/Handles/NotificationTokenHandle.cs
- Realm/Realm/Handles/ObjectHandle.cs
- Realm/Realm/Handles/ResultsHandle.cs
- Realm/Realm/Handles/SharedRealmHandle.cs
- Realm/Realm/Native/NativeCommon.cs
- Realm/Realm/NotificationsHelper.cs
- Realm/Realm/Realm.cs
- Realm/Realm/Realm.csproj
- Realm/Realm/RealmCollectionBase.cs
- Realm/Realm/RealmObject.cs
- Realm/Realm/Transaction.cs
- Tests/Tests.Shared/PropertyChangedTests.cs
- Tests/Tests.XamarinIOS/Tests.XamarinIOS.csproj
- wrappers/src/list_cs.cpp
- wrappers/src/notifications_cs.hpp
- wrappers/src/object_cs.cpp
- wrappers/src/object_cs.hpp
- wrappers/src/results_cs.cpp
- wrappers/src/shared_realm_cs.cpp
- wrappers/src/shared_realm_cs.hpp
- wrappers/wrappers.xcodeproj/project.pbxproj
This is a POC of using the new object notifications API from OS. There are two breaking changes compared to our old approach:
- You can't subscribe for notifications during a write transaction. That means that if you open a page with an ongoing transaction (like we do with the quickjournal), you won't be able to subscribe for notifications until the transaction is committed.
- You don't get notifications until a write transaction is committed. Previously, we would send notifications to same-thread subscribers as soon as the change is made. This means that if you subscribe on the main thread and then start manipulating realm objects there, the UI will be updated only after the transaction has completed.
These may or may not be a deal breaker. The huge benefit we get from that approach is …
> POC of the new object notifications

- Realm/Realm/NotificationsHelper.cs
GCHandles for RealmObjects are weak so we may receive notifications for collected object.
> Fix NRE due to weak gchandle

- CHANGELOG.md
- NuGet/Realm.Database/Realm.Database.nuspec
- NuGet/Realm/Realm.nuspec
- Realm/Realm/Native/NativeCommon.cs
Looks like RuntimeInformation is fairly unreliable - revert back to the reflection and `Environment.OsVersion` approach.
Fixes #1335
> Remove dependency on runtimeinformation

- Realm/Realm.Sync/Realm.Sync.csproj
- Tests/Tests.Win32/Tests.Win32.csproj
- Weaver/WeaverTests/RealmWeaver.Tests/RealmWeaver.Tests.csproj
Removes some targets that nuget failed to clean up
> Remove leftover fody targets

- CHANGELOG.md
- Realm/Realm/Linq/RealmResultsVisitor.cs
- Realm/Realm/Realm.csproj
- Tests/Tests.Shared/RealmResults/SimpleLINQtests.cs
- Tests/Tests.Shared/TestObjects.cs
Fixes #1404
Ignore the first commit - it's only cosmetic changes. Here's the actual change: https://github.com/realm/realm-dotnet/pull/1405/files/4ae2fadabfaa861a53f26162f0dfd4b6624905e3..9311aea824d449ab7433e6f3764ace81d18a5284
> Fix crash when querying [MapTo]-ed columns

- CHANGELOG.md
- Realm/Realm/RealmConfiguration.cs
- Tests/Tests.Shared/InstanceTests.cs
> Execute migrations on a background thread when opening a local realm

- CHANGELOG.md
- Realm/Realm.Sync/Helpers/AuthenticationHelper.cs
- wrappers/Makefile
Cocoa PR: https://github.com/realm/realm-cocoa/pull/4957/files
> Update OS to get the reconnect fix

- Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs
- Realm/Realm/Native/Configuration.cs
Removes a few workarounds introduced when the compiler had trouble with .NET standard packages.
> Remove compiler workarounds

- CHANGELOG.md
- Realm/Realm/RealmObject.cs
- Tests/Tests.Shared/PropertyChangedTests.cs
> Raise PropertyChanged with correct property name, regardless of order.

- CHANGELOG.md
- Platform.PCL/Realm.PCL/Schema/RealmSchemaPCL.cs
> Don’t throw exceptions in the module initializer of PCL assemblies

- Platform.PCL/Realm.Sync.PCL/UserPCL.cs
- Realm/Realm/RealmConfiguration.cs
- Tests/Tests.Shared/ConfigurationTests.cs
- Tests/Tests.Shared/InstanceTests.cs
- Tests/Tests.Shared/LifetimeTests.cs
- Tests/Tests.Shared/MigrationTests.cs
- Tests/Tests.Shared/NotificationTests.cs
- Tests/Tests.Shared/RealmResults/DisallowedPredicateParameters.cs
- Tests/Tests.Shared/RealmTest.cs
- Tests/Tests.Shared/RelationshipTests.cs
- Tests/Tests.Shared/StandAloneObjectTests.cs
On non-sandboxed environments (e.g. Windows, macOS, etc.), our tests operate in the same documents folder, so parallel builds often report false negatives.
> Ensure tests always use temp filenames

- CHANGELOG.md
- Platform.PCL/Realm.Sync.PCL/CredentialsPCL.cs
- Platform.PCL/Realm.Sync.PCL/Realm.Sync.PCL.csproj
- Platform.PCL/Realm.Sync.PCL/UserPCL.cs
- Realm/Realm.Sync/Credentials.cs
- Realm/Realm.Sync/Dtos/UserInfo.cs
- Realm/Realm.Sync/Dtos/UserLookupResponse.cs
- Realm/Realm.Sync/Helpers/AuthenticationHelper.cs
- Realm/Realm.Sync/Realm.Sync.csproj
- Realm/Realm.Sync/User.cs
- Realm/Realm/Helpers/Argument.cs
- Realm/Realm/Realm.csproj
- Tests/Tests.NetCore/Dockerfile.linux
- Tests/Tests.Sync.Shared/Constants.cs
- Tests/Tests.Sync.Shared/CredentialsTests.cs
- Tests/Tests.Sync.Shared/MergeByPKTests.cs
- Tests/Tests.Sync.Shared/PermissionsTests.cs
- Tests/Tests.Sync.Shared/SSLConfigurationTests.cs
- Tests/Tests.Sync.Shared/SyncTestHelpers.cs
- Tests/Tests.Sync.Shared/SynchronizedInstanceTests.cs
> Add user lookup API

- README.md
This PR updates the `License` section of the README to:
* State that Realm Core is now officially open source.
* Properly identifies Realm Xamarin as the product that is under the Apache 2.0 License (As simply stating 'Realm' is too generic.)
> Updated License section of README

- CHANGELOG.md
- Realm/Realm/Schema/RealmSchema.cs
- Tests/Tests.Shared/ConfigurationTests.cs
> Validate schema classes for duplicates

- CHANGELOG.md
- Realm/Realm/Linq/RealmResultsVisitor.cs
- Tests/Tests.Shared/RealmResults/DisallowedPredicateParameters.cs
- Tests/Tests.Shared/TestObjects.cs
Throws NotSupportedException when trying to use an IList or IQueryable property in queries. Also fixes a corner case where querying by a related property could produce incorrect results.
Fixes #1353
> Throw when trying to access a list/query in queries

- CHANGELOG.md
- wrappers/CMakeLists.txt
- wrappers/src/shared_realm_cs.cpp
> Use the application bundle ID for keychain work

- CHANGELOG.md
- Platform.PCL/Realm.Sync.PCL/UserPCL.cs
- Realm/Realm.Sync/Helpers/AuthenticationHelper.cs
- Realm/Realm.Sync/User.cs
- Tests/Tests.Sync.Shared/CredentialsTests.cs
> Revoke refresh token on Logout

- CHANGELOG.md
- Realm/Realm/Handles/SharedRealmHandle.cs
- Realm/Realm/Handles/TableHandle.cs
- Realm/Realm/Helpers/Operator.cs
- Tests/Tests.Shared/AddOrUpdateTests.cs
- Tests/Tests.Shared/PrimaryKeyTests.cs
- Tests/Tests.Shared/TestObjects.cs
- wrappers/src/shared_realm_cs.cpp
> Allow null PKs for strings

- Realm/Realm/Helpers/Operator.cs
When debugging an application that uses Realm with Just My Code debugging disabled the debugger stops at first chance exceptions even when they're handled inside Realm. This change makes one such first chance exception opportunity occur more rarely by relying on lazy initialization of the `GenericOperator<T, U>` helpers.
> Make generic operators lazily initialized

- CHANGELOG.md
- Realm/Realm.Sync/Permissions/Permission.cs
- Realm/Realm.Sync/Permissions/PermissionChange.cs
- Realm/Realm.Sync/Permissions/PermissionOffer.cs
- Realm/Realm.Sync/Permissions/PermissionOfferResponse.cs
- Realm/Realm.Sync/Properties/AssemblyInfo.cs
- Realm/Realm/Attributes/Attributes.cs
- Tests/Tests.Shared/ConfigurationTests.cs
- Weaver/RealmWeaver.Fody/ImportedReferences.cs
- Weaver/RealmWeaver.Fody/ModuleWeaver.Schema.cs
> Expose [Explicit] to the world

- wrappers/CMakeLists.txt
That way they are inherited by every target that depends on realm-object-store nomatter where it is.
> Move the REALM_USE definitions to the object store target

- CHANGELOG.md
- Platform.PCL/Realm.PCL/RealmConfigurationBasePCL.cs
- Realm/Realm.Sync/Exceptions/IncompatibleSyncedFileException.cs
- Realm/Realm.Sync/SyncConfiguration.cs
- Realm/Realm/Realm.cs
- Realm/Realm/RealmConfiguration.cs
- Realm/Realm/RealmConfigurationBase.cs
- Tests/Tests.Shared/DynamicAccessTests.cs
- Tests/Tests.Shared/DynamicRelationshipTests.cs
- Tests/Tests.Shared/InstanceTests.cs
- Tests/Tests.Sync.Shared/SyncTestBase.cs
- Tests/Tests.Sync.Shared/SynchronizedInstanceTests.cs
> Expose config.Dynamic

- Weaver/RealmWeaver.Fody/ImportedReferences.cs
Fixes https://forums.realm.io/t/ireflectabletype-is-defined-in-an-assembly-that-is-not-referenced/792/4
> Add custom references for .NET standard 2

- CHANGELOG.md
- Tests/Tests.Shared/RealmObjectTests.cs
- wrappers/src/object_cs.cpp
Fixes #1695 
Based on #1696 to include that fix in the prerelease package.
> Make sure RealmObject.Equals doesn't return true for deleted objects

- CHANGELOG.md
- Platform.PCL/Realm.PCL/RealmPCL.cs
- Realm/Realm/Handles/SharedRealmHandle.cs
- Realm/Realm/Realm.cs
- Tests/Tests.Shared/AsyncTests.cs
- wrappers/src/shared_realm_cs.cpp
> Make WriteAsync wait for changes asynchronously

- CHANGELOG.md
- Realm/Realm/RealmCollectionBase.cs
Fixes https://github.com/realm/realm-dotnet/issues/1575
> Remove IList implementation of Realm collections

- CHANGELOG.md
- Realm/Realm/Linq/RealmResultsVisitor.cs
- Tests/Tests.Shared/RealmResults/SimpleLINQtests.cs
Fixes https://github.com/realm/realm-dotnet/issues/1760
> Throw NotSupported exception when comparing to an unmanaged object

- CHANGELOG.md
- Platform.PCL/Realm.Sync.PCL/Configurations/SyncConfigurationBasePCL.cs
- Realm/Realm.Sync/Configurations/SyncConfigurationBase.cs
- Tests/Tests.Sync.Shared/SessionTests.cs
- Tests/Tests.Sync.Shared/SynchronizedInstanceTests.cs
Exposes OnProgress for https://support.realm.io/helpdesk/tickets/2114.
> Expose SyncConfiguration.OnProgress

- CHANGELOG.md
- Platform.PCL/Realm.Sync.PCL/SessionPCL.cs
- Realm/Realm.Sync/Handles/SessionHandle.cs
- Realm/Realm.Sync/Session.cs
- Tests/Tests.Sync.Shared/SessionTests.cs
- Tests/Tests.Sync.Shared/SyncTestHelpers.cs
- wrappers/src/sync_session_cs.cpp
Fixes https://github.com/realm/realm-dotnet-private/issues/138
> Add session.stop/start methods

- CHANGELOG.md
- Realm/Realm/Handles/SyncUserHandle.cs
- Realm/Realm/Sync/Credentials.cs
- Realm/Realm/Sync/User.cs
- Tests/Realm.Tests/Sync/CredentialsTests.cs
- Tests/Realm.Tests/Sync/SyncTestHelpers.cs
- wrappers/src/sync_user_cs.cpp
Adds support for custom refresh tokens. Depends on an yet-unreleased ROS version. Couldn't find a reasonable way to test it without rewriting the entire way we run ROS tests, so tested things against a local ROS instance.
> RNET-1 Custom refresh tokens

- CHANGELOG.md
- Realm/Realm/Sync/Credentials.cs
- Tests/Realm.Tests/Sync/CredentialsTests.cs
> ROS-110: Expose userId and isAdmin as parameters to Credentials.CustomRefreshToken

- CHANGELOG.md
- Realm.sln
- Realm/Realm.Fody/Realm.Fody.csproj
- Realm/Realm/Realm.csproj
- Tests/Weaver/Realm.Fody.Tests/Realm.Fody.Tests.csproj
Make the [FodyHelpers](https://www.nuget.org/packages/fodyhelpers) package a private dependency of the Realm.Fody package. This will stop it being included as a transient dependency in user projects, which in turn breaks debugging.
Thanks to @Dids and @SimonCropp for diagnosing the issue.
Fixes #1910
> Fix the FodyHelpers dependency

- Realm/Realm.Fody/ImportedReferences.cs
- Realm/Realm.Fody/ModuleWeaver.cs
- Realm/Realm/Dynamic/MetaRealmObject.cs
- Realm/Realm/Handles/QueryHandle.cs
- Realm/Realm/Linq/RealmResultsVisitor.cs
- Realm/Realm/Native/PrimitiveValue.cs
- Realm/Realm/RealmList.cs
- Realm/Realm/RealmObject.cs
- Tests/Weaver/AssemblyToProcess/CopyToRealmTestObjects.cs
- Tests/Weaver/Realm.FakeForWeaverTests/Realm.FakeForWeaverTests.csproj
- Tests/Weaver/Realm.FakeForWeaverTests/RealmObject.cs
- Tests/Weaver/Realm.Fody.Tests/WeaverTests.cs
- wrappers/src/query_cs.cpp
This removes RealmObject's methods for getting and setting
- char
- float
- double
- DateTimeOffset
- bool
And replaces them with `PrimitiveValue` (similar to what we're doing with lists/results).
> Refactor RealmObject to reduce the number of methods

- CHANGELOG.md
- Jenkinsfile
- Realm/Realm/Extensions/SynchronizationContextExtensions.cs
- Realm/Realm/Native/SynchronizationContextScheduler.cs
This introduces a fallback mechanism where contexts of type `DispatcherSynchronizationContext` will get their thread ids compared for equality. 
Fixes #2026
> Special-case DispatcherSynchronizationContext

- CHANGELOG.md
- Realm/Realm.Fody/Extensions/PropertyDefinitionExtensions.cs
- Realm/Realm.Fody/ImportedReferences.cs
- Realm/Realm.Fody/ModuleWeaver.cs
- Realm/Realm/Dynamic/MetaRealmObject.cs
- Realm/Realm/Handles/CollectionHandleBase.cs
- Realm/Realm/Handles/ObjectHandle.cs
- Realm/Realm/Helpers/Operator.cs
- Realm/Realm/Linq/RealmResultsVisitor.cs
- Realm/Realm/Native/PrimitiveValue.cs
- Realm/Realm/Realm.csproj
- Realm/Realm/RealmInteger.cs
- Realm/Realm/RealmObject.cs
- Realm/Realm/Schema/PropertyType.cs
- Realm/Realm/Schema/PropertyTypeEx.cs
- Tests/Realm.Tests/Database/AccessTests.cs
- Tests/Realm.Tests/Database/RealmResults/ConvertTests.cs
- Tests/Realm.Tests/Database/RealmResults/LINQvariableTests.cs
- Tests/Realm.Tests/Database/RealmResults/SortingTests.cs
- Tests/Realm.Tests/Database/TestObjects.cs
- Tests/Weaver/AssemblyToProcess/AssemblyToProcess.csproj
- Tests/Weaver/AssemblyToProcess/CopyToRealmTestObjects.cs
- Tests/Weaver/AssemblyToProcess/TestObjects.cs
- Tests/Weaver/Realm.Fody.Tests/WeaverTests.cs
- wrappers/src/marshalling.hpp
- wrappers/src/object_cs.cpp
- wrappers/src/query_cs.cpp
This adds support for persisting and querying decimal properties. The database stores these values as a 128-bit decimal value, but we're also allowing defining the properties as .NET's built-in `decimal` type, even though it's only 96-bit. We'll automatically convert between the 96 and the 128-bit version where appropriate, but keep in mind that you may lose precision or range when using the built-in type.
Example code:
```csharp
public class MyClassWithDecimals : RealmObject
{
// Declare decimal properties as usual - with an automatic getter and setter
public decimal VeryPreciseNumber { get; set; }
// To use the full range of the native decimal, use Decimal128 from the MongoDB.Bson package.
// The .NET SDK already pulls that as a dependency, so you don't have to NuGet install it.
public …
```
> Add decimal support

- wrappers/CMakeLists.txt
Removes arm64 and arm64e from the list of valid archs for simulator builds. This is needed because core and sync don't include these slices in the prebuilt binaries.
> Only allow x86 and x64 targets for simulator builds

- Realm/Realm/Realm.cs
Simplifies code for `WriteAsync` methods, using `async/await`. This was not done in the past due to a mono bug.
https://github.com/realm/realm-dotnet/blob/6228b00777793780a24e0348c0d6ad6cc85cc43e/Realm/Realm/Realm.cs#L712-L743
Fixes #2088
> Simplified WriteAsync code

- Realm/Realm/Handles/ListHandle.cs
- Realm/Realm/Handles/ObjectHandle.cs
- Realm/Realm/Handles/QueryHandle.cs
- Realm/Realm/Handles/SetHandle.cs
- Realm/Realm/Handles/SharedRealmHandle.cs
- Realm/Realm/Handles/SyncUserHandle.cs
- Realm/Realm/Handles/TableHandle.cs
- wrappers/src/list_cs.cpp
- wrappers/src/object_cs.cpp
- wrappers/src/query_cs.cpp
- wrappers/src/shared_realm_cs.cpp
- wrappers/src/sync_user_cs.cpp
- wrappers/src/table_cs.cpp
Avoid passing `PrimitiveValue` as pointer. It was done like that due to a bug in .NET Core for macOS/Linux.
Fixes #2062
> Removed passing pointer

- .gitignore
- Jenkinsfile
- Realm/Realm.Unity/Runtime/UnityUtils.dll.meta
- Realm/Realm.Unity/Runtime/iOS/realm-wrappers.framework.meta
- Realm/Realm/InteropConfig.cs
- Tools/SetupUnityPackage/SetupUnityPackage.sln
- Tools/SetupUnityPackage/SetupUnityPackage/Program.cs
- Tools/SetupUnityPackage/SetupUnityPackage/SetupUnityPackage.csproj
- Tools/SetupUnityPackage/UnityUtils/FileHelper.cs
- Tools/SetupUnityPackage/UnityUtils/UnityUtils.csproj
This adds an extra Unity-only project that we can use to put functionality rather than relying on reflection. Right now it only has one method which returns the internal files location for the app.
Fixes https://github.com/realm/realm-dotnet/issues/2132
Fixes https://github.com/realm/realm-dotnet/issues/2134
> Provide fallback for Unity on Android

- Docs/index.md
> Migrate docs links from realm.io to docs.mongodb.com

- Realm/Realm.Unity/Editor/Common/ImportedReferences.cs
- Realm/Realm.Unity/Editor/Common/RealmWeaver.Schema.cs
Added `RuntimeInitializeOnLoadMethod` on `RealmModuleInitializer` when is in UnityEngine with backend il2cpp.
Fixes #2144
> Added RuntimeInitializeOnLoad attribute

- Tools/SetupUnityPackage/UnityUtils/FileHelper.cs
- Tools/SetupUnityPackage/UnityUtils/Properties/AssemblyInfo.cs
- Tools/SetupUnityPackage/UnityUtils/UnityUtils.csproj
The addition of the attribute you, @nirinchev, suggested seems to work.
I say "seems" because the only way I had to test if the change was making a difference was to check the temp/staging area during the building process. It was not possible to use breakpoints because the debugging session was being stopped by unity regularly at the important point.
Anyway, what I could observe was that with the attribute added, the `UnityUtils.dll` was kept in the staging area until the very last step (the one that cleans away all the dll but leaving some pdb but not all). Instead, Without such attribute the dll was initially copied in the staging area but delete almost immediately.
This is not the most scientific way of testing this, but my expectation is that when we've merged my changes for adding …
> Added attr to avoid dll stripping

- CHANGELOG.md
- Realm/Realm/Native/PrimitiveValue.cs
- Tests/Tests.UWP/Tests.UWP.csproj
- wrappers/CMakeLists.txt
- wrappers/src/marshalling.hpp
- wrappers/src/query_cs.cpp
Hopefully fixes https://github.com/realm/realm-dotnet/issues/2169.
> Fix .NET Native compilation

- Realm/Realm/Handles/ObjectHandle.cs
- Realm/Realm/Handles/SetHandle.cs
- Realm/Realm/RealmSet.cs
- Tests/Realm.Tests/Database/RealmSetTests.cs
- wrappers/src/CMakeLists.txt
- wrappers/src/object_cs.cpp
- wrappers/src/set_cs.cpp
Wires up some of the native set implementation - there are still a few missing methods (IsStrictSubset, IsStrictSuperset, SetEquals), and Core hasn't exposed an ability to invoke the Set-specific methods with a non-set collection, but most of the remaining stuff should be there.
> Wire up some of the native set implementation

- CHANGELOG.md
- Tests/Realm.Tests/Database/CollectionTests.cs
- wrappers/src/results_cs.cpp
- wrappers/src/schema_cs.hpp
> Migrate to bison parser

- CHANGELOG.md
- Jenkinsfile
- Realm/Realm/Handles/AppHandle.cs
The -beta.4 release is cursed, so we're jumping to -beta.5. Supersedes https://github.com/realm/realm-dotnet/pull/2189.
> Prepare for 10.0.0-beta.5

- CHANGELOG.md
- Realm/Realm/Native/PrimitiveValue.cs
Fixes an issue reported on Forums where date properties are not read correctly from pre-beta.5 versions of Realm.
> Fix date marshaling

- Tests/Benchmarks/Benchmarks.iOS/Benchmarks.iOS.csproj
- Tests/Benchmarks/Benchmarks/Benchmarks.csproj
This adds full linking for release iPhone builds (otherwise, I was hitting link-time errors about missing methods). It also removes the `Realm` reference from the shared XF project as that doesn't seem like something we need to reference.
> Some project cleanup

- Realm/Realm/DatabaseTypes/IMetadataObject.cs
- Realm/Realm/DatabaseTypes/RealmCollectionBase.cs
- Realm/Realm/DatabaseTypes/RealmDictionary.cs
- Realm/Realm/DatabaseTypes/RealmList.cs
- Realm/Realm/DatabaseTypes/RealmObjectBase.cs
- Realm/Realm/Dynamic/MetaRealmDictionary.cs
- Realm/Realm/Handles/DictionaryHandle.cs
- Realm/Realm/Realm.cs
- Tests/Realm.Tests/Database/DynamicRelationshipTests.cs
Will rebase after https://github.com/realm/realm-dotnet/pull/2214 is merged.
Adds support for dynamic dictionaries except dictionaries of embedded objects. This will come later.
Fixes https://github.com/realm/realm-dotnet/issues/2208.
> Add dynamic support for dictionaries

- CHANGELOG.md
- README.md
- Realm/Realm.Unity/package.json
- Realm/Realm/Exceptions/ClientResetException.cs
- Realm/Realm/Exceptions/PermissionDeniedException.cs
- Realm/Realm/Exceptions/RealmClassLacksPrimaryKeyException.cs
- Realm/Realm/Exceptions/RealmDuplicatePrimaryKeyValueException.cs
- Realm/Realm/Exceptions/RealmMigrationNeededException.cs
- Realm/Realm/Helpers/AsyncHelper.cs
- Realm/Realm/Migration.cs
- Realm/Realm/Realm.csproj
- Realm/Realm/Schema/ObjectSchema.cs
- Realm/Realm/Schema/RealmSchema.cs
- SUPPORT.md
Move all realm.io links to mongodb docs
I couldn't find some information, I was thinking to contact the docs team to ask. If you @nirinchev know already that some should not exist anymore, then I'll just rearrange the documents to rephrase/remove the links.
The changes were made on entries coming from the following command:
`grep -rin --exclude-dir={Docs,obj,bin,realm-core} "https://realm.io*" .`
executed at the highest level of realm-dotnet folder.
Fixes #2143
> Move all realm.io links to mongodb docs

- CHANGELOG.md
- Realm/Realm/Exceptions/RealmException.cs
- Realm/Realm/Handles/SortDescriptorHandle.cs
- Realm/Realm/Linq/RealmResultsVisitor.cs
- Tests/Realm.Tests/Database/CollectionTests.cs
- Tests/Realm.Tests/Database/ConfigurationTests.cs
- Tests/Realm.Tests/Database/InstanceTests.cs
- Tests/Realm.Tests/Database/LifetimeTests.cs
- Tests/Realm.Tests/Database/ObjectIntegrationTests.cs
- Tests/Realm.Tests/Database/Person.cs
- Tests/Realm.Tests/Database/PropertyChangedTests.cs
- Tests/Realm.Tests/Database/RealmResults/SimpleLINQtests.cs
- Tests/Realm.Tests/Database/RealmResults/SortingTests.cs
- Tests/Realm.Tests/Sync/SyncTestBase.cs
- Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
- Tests/Realm.Tests/Sync/UserManagementTests.cs
- Tests/Realm.Tests/TestHelpers.cs
- Tests/Weaver/Realm.Fody.Tests/WeaverTests.cs
- wrappers/android.Dockerfile
- wrappers/src/sort_descriptor_cs.cpp
This is mostly a cleanup PR that achieves the following:
* Fixes `OrderBy(...).OrderBy(...)` query chains by having the last clause replace all preceding ones.
* Reenables all previously disabled Windows tests. They seem to pass locally.
* Reenable all previously explicit tests that have been fixed. Explicit tests that haven't been fixed are [Ignore]-d
* Reenable some previously [Ignore]-d tests that have been fixed.
* Throws `RealmMigrationNeededException` when opening a readonly file that uses an old core format.
> Assorted test-related improvements

- CHANGELOG.md
- Realm/Realm/Configurations/InMemoryConfiguration.cs
- Realm/Realm/Configurations/RealmConfiguration.cs
- Realm/Realm/Configurations/RealmConfigurationBase.cs
- Realm/Realm/Configurations/SyncConfiguration.cs
- Realm/Realm/Exceptions/RealmException.cs
- Realm/Realm/Exceptions/RealmExceptionCodes.cs
- Realm/Realm/Exceptions/RealmSchemaValidationException.cs
- Realm/Realm/Native/Configuration.cs
- Realm/Realm/Native/SyncConfiguration.cs
- Realm/Realm/Sync/SchemaMode.cs
- Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
- wrappers/src/error_handling.cpp
- wrappers/src/realm_error_type.hpp
- wrappers/src/shared_realm_cs.cpp
- wrappers/src/shared_realm_cs.hpp
Based on `RealmConfigurationBase.ObjectClasses` "AdditiveDiscovered" or "AdditiveExplicit" is now appropriately selected and passed to core.
Currently, because of the way core did it, this is a detail only relevant for synced scenarios. I'll talk to James Stone to understand better the why's'.
This PR also adds an additional exception to have a more precise error category when an issue with the schema validation arises.
==================================
UPDATE
I talked with James and he explained that the 2 types of Additive behaviours are purposedly used only for sync-d realms because unreachable embeddedObjects are only problematic for the server. Hence, when the client doesn't sync, there's no reason to check for them as these unreachable objs don't really create an issue; although …
> Pass in correct schema type for explicit and autodiscovered types

- Docs/index.md
These changes resolves a redirect chain that is currently in the dotnet SDK docs and is negatively affecting search engine performance.
(I'm on the Documentation Platform team at MongoDB and this was identified as part of a broader SEO project that we're currently working on, and this seemed like an easy way to fix it 😁.)
cc @nathan-contino-mongo 
Addresses DOP-1883
None.
> Use canonical URLs for docs links on overview page

- .github/ga_packages/build_cache_executor/.eslintignore
- .github/ga_packages/build_cache_executor/.eslintrc
- .github/ga_packages/build_cache_executor/.prettierrc
- .github/ga_packages/build_cache_executor/__tests__/common.ts
- .github/ga_packages/build_cache_executor/__tests__/input_parsing.ts
- .github/ga_packages/build_cache_executor/dist/build_cache_executor.d.ts
- .github/ga_packages/build_cache_executor/dist/utils/common.d.ts
- .github/ga_packages/build_cache_executor/src/build_cache_executor.ts
- .github/ga_packages/build_cache_executor/src/utils/common.ts
- .github/ga_packages/build_cache_executor/src/utils/input_parsing.ts
- .github/pipeline.code-workspace
Indents code with 4 instead of 2 spaces.
> Indent code with 4 spaces

- .github/workflows/lint.yml
- Jenkinsfile
This is using a very simple action I created during skunkworks - it walks the changed files and emits warnings if there's a `// TODO: blah blah` comment that doesn't have a link to Jira/Github.
> Add workflow to verify code todos

- Realm/Realm.Weaver/RealmWeaver.cs
- Tests/Realm.Tests/Database/ListOfPrimitivesTests.cs
- Tests/Realm.Tests/Database/RealmDictionaryTests.cs
- Tests/Realm.Tests/Database/RealmSetTests.cs
- Tests/Realm.Tests/Database/TestObjects.cs
- Tests/Weaver/AssemblyToProcess/FaultyClasses.cs
- Tests/Weaver/AssemblyToProcess/TestObjects.cs
- Tests/Weaver/Realm.Fody.Tests/WeaverTests.cs
This PR adds an error in the weaver when declaring collections of `RealmInteger`.
Fixes #2308
> Disallow counter collections

- Realm/Realm/DatabaseTypes/RealmObjectBase.cs
- Realm/Realm/DatabaseTypes/RealmValue.cs
This PR adds DebuggerDisplay to some Realm types. In particular debugger display contains:
- `RealmObjectBase`: `IsValid`
- `RealmValueType`: `Type - ToString()`  --> This can be useful to differentiate between different numerical types with similar string representation, for instance
Regarding the rest of the Realm types:
- Collection types (`Set`, `Dictionary`, `List`, `Result`) and their superclass `RealmCollectionBase` don't have anything meaningful to display in my opinion. For the "proper" collection types (`Set`, `Dictionary`, `List`), the parameter `Count` was already in the `DebuggerDisplay` attribute, and that seems fine.
- RealmInteger already prints the containing value in ToString(), and that also seems fine enough.
Fixes #2047
> Added missing DebuggerDisplay

- CHANGELOG.md
- Realm/Realm/GlobalSuppressions.cs
- Realm/Realm/Helpers/Operator.cs
- Realm/Realm/Helpers/Operator.tt
- Realm/Realm/Linq/RealmResultsVisitor.cs
- Tests/Realm.Tests/Database/RealmResults/ConvertTests.cs
- Tests/Realm.Tests/Realm.Tests.csproj
Replaces `Lambda.Compile` in the query visitor with a newly introduced `Operator.Convert<T>(object)` call. While it's not as versatile as `Lambda.Compile`, it's at least supported in IL2CPP.
> Remove Lambda.Compile from results visitor

- Tests/Realm.Tests/Database/ObjectIntegrationTests.cs
This PR adds a test to be sure we don't introduce any regressions with deletion and rollbacks. 
Fixes #1332
> Added test for property acess after delete rollback

- .github/templates/main.yml
- .github/workflows/main.yml
- Tests/Weaver/Realm.Fody.Tests/Realm.Fody.Tests.csproj
Fixes a few nits that I noticed when reviewing https://github.com/realm/realm-dotnet/pull/2354, notably:
- `buildPackages` yield returns array nodes while iterating.
- `dotnetPublish` is replaced with `dotnetPublishAndRun` which publishes an executable then runs it.
- `dotnetPublishAndRunTests` is added as a convenience wrapper around `dotnetPublish` for when we need to setup some of the build properties
- Modified the weaver tests to use `dotnetPublish` - there was no fundamental issue with `dotnetRun` but since it was the only job that used it, figured might as well unify things.
- Modified the weaver test project to output executable
> Fix a few GA nits

- Tests/Benchmarks/PerformanceTests/FodyWeavers.xml
- Tests/Realm.Tests/FodyWeavers.xml
Tests are messing with our analytics hence we need to turn off analytics for tests and benchmarks.
In order to do so the attribute **DisableAnalytics** was added and set to true in **FodyWeavers.xml**-s. Once that's done, `RealmWeaver.Execute` receives `Analytics.Config` with `RunAnalytics` set to false. When the flow arrives to `Analytics.SubmitAnalytics`, such method skips the analytics collection and delivery because `Analytics.Config.RunAnalytics` is set to false.
> Turn off analytics for tests and benchmarks

- Realm/Realm/Helpers/Operator.cs
- Realm/Realm/Helpers/Operator.tt
- Tests/Realm.Tests/Database/RealmResults/ConvertTests.cs
This adds a fallback when converting `IConvertible` types to go ahead and try to use `Convert.ChangeType` - while it's slower than our built-in convertors, it's still better than throwing. The most common case this will handle is using enums in queries.
Fixes https://github.com/realm/realm-dotnet/issues/2392
> Handle conversions of enums in queries

- Tests/Realm.Tests/RealmTest.cs
- Tests/Realm.Tests/Sync/DataTypeTests.cs
- Tests/Realm.Tests/Sync/FunctionsTests.cs
- Tests/Realm.Tests/Sync/SyncTestBase.cs
- Tests/Realm.Tests/TestHelpers.cs
This converts all cleanup lists in tests into queues and we make sure to drain the queues - previously we'd just push stuff to the lists and never empty them.
It resolves the slowing down of test runs with the new delete functionality.
> Make sure we don't accumulate test resources endlessly

- CHANGELOG.md
- Realm/Realm.UnityWeaver/UnityWeaver.cs
- Tools/SetupUnityPackage/CommandLineOptions/TestOptions.cs
> Add a Unity option to enable weaving of editor assemblies

- Realm/Realm/Attributes/PreserveAttribute.cs
- Realm/Realm/Attributes/WovenAssemblyAttribute.cs
- Realm/Realm/Attributes/WovenAttribute.cs
- Realm/Realm/Attributes/WovenPropertyAttribute.cs
Just noticed that the attributes used by the weaver didn't have EditorBrowsable(Never).
> Apply EditorBrowsable(Never) to internal-ish attributes

- CHANGELOG.md
- Realm/AssemblyInfo.props
- Realm/Realm.UnityWeaver/UnityWeaver.cs
- Realm/Realm.Weaver/Extensions/TypeReferenceExtensions.cs
- Realm/Realm.Weaver/RealmWeaver.cs
- Realm/Realm.Weaver/WeaveResults.cs
- Realm/Realm/InteropConfig.cs
- Realm/Realm/Schema/RealmSchema.cs
- Tests/Weaver/Realm.Fody.Tests/WeaverTests.cs
This PR contains two main changes:
* Stops the weaving process on error. This is necessary because Unity will not treat extension-generated error logs as build failures and will happily run the built assembly. This means that we may end up in a situation where classes are partially woven and things fail silently in runtime.
* Modifies the error message for Unity when a RealmConfiguration is created without schema. This is likely due to a build error and we advise users to re-run the weaver and look for error messages in the logs.
Fixes https://github.com/realm/realm-dotnet/issues/2310
> Handle weaver errors in Unity 

- .github/templates/main.yml
- .github/workflows/main.yml
This deletes the wrappers and the extra packages that only the Unity build uses. Apart from saving space, I'm just annoyed when I have to scroll through a bunch of artifacts to find what I'm looking for 😄
I decided to put it in a separate step even though it can technically be done after packaging because I was thinking we may eventually want to do other things with the artifacts - for example get all the debug symbols and zip them together in a debug package or something similar.
> Delete some artifacts from the workflow after it runs

- wrappers/README.md
Updated README instructions for wrappers
> Updated README instructions

- Realm/Realm/DatabaseTypes/RealmCollectionBase.cs
- Realm/Realm/DatabaseTypes/RealmSet.cs
- Tests/Realm.Tests/Database/CollectionTests.cs
- Tests/Realm.Tests/Database/RealmDictionaryTests.cs
- Tests/Realm.Tests/Database/RealmSetTests.cs
- Tests/Realm.Tests/Database/TestObjects.cs
Added to checks to verify that objects do not belong to a different realm when being added to collection
Fixes #2462
> Verify that objects do not belong to different realm when added to collection

- Realm/Realm/Realm.cs
- Tests/Realm.Tests/Sync/DataTypeSynchronizationTests.cs
- Tests/Realm.Tests/Sync/DataTypeTests.cs
Fixes a few issues that I came across when running the datatype tests on macOS - most notably, we were trying to add an object belonging to a different Realm to a dictionary which was failing in all sorts of weird ways. Additionally, it adds adds equals overrides for the RealmValue tests as `RealmValue.Equals` will return `false` for `RealmObject` instances belonging to different Realms.
> Fixes for the sync datatype tests

- Jenkinsfile
- Tests/Realm.Tests/Sync/SyncTestBase.cs
- wrappers/src/sync_user_cs.cpp
Getting the app from a detached user would result in a segfault. This returns `nullptr` instead.
> Don't try to get the app from a removed user

- CHANGELOG.md
- Realm/Realm.UnityUtils/Initializer.cs
- Realm/Realm/Handles/AppHandle.cs
- Realm/Realm/Handles/SharedRealmHandle.cs
- Realm/Realm/InteropConfig.cs
- Realm/Realm/Native/NativeCommon.cs
When Unity closes the application, it will suspend garbage collection and wait for all native threads to exit (or at least stop doing work - threads that are waiting on conditional variables are not an issue). This is problematic because the managed AppHandle holds a shared_ptr to the native App, which in turn holds a shared_ptr to the SyncManger. This prevents the destruction of the SyncManager and this is where we actually stop the sync client. Not stopping the sync client means that it'll keep polling the socket in a loop, forcing Unity to wait forever.
The fix is to keep a collection of weak references to each AppHandle we create and force close all of them when the application exits.
> Clean up native resources on Unity application exit

- CHANGELOG.md
- Realm/Realm/Handles/SharedRealmHandle.cs
- Realm/Realm/Handles/UnownedRealmHandle.cs
- Realm/Realm/Helpers/Operator.tt
- Realm/Realm/Realm.cs
While investigating https://github.com/realm/realm-dotnet/issues/2224, I spent quite some time convincing myself that the Realm lifecycle is correct. While I couldn't find issues with it, I noticed that the `_states` dictionary approach was wrong. It relied on a ThreadLocal dictionary to hold the states for the current thread, but that is no longer safe since a Realm file may be opened/used across different threads as long as the synchronization context is the same. This was only used for the open Realm detection which should be moved to OS once https://github.com/realm/realm-core/issues/4424 is merged.
Fixes https://github.com/realm/realm-dotnet/issues/2198 (doesn't do anything to fix it per se, but adds a thorough explanation why it's not a problem).
> Remove Realm states dictionary

- .gitignore
- Tests/Realm.Tests/RealmTest.cs
Unity's version of Path.GetTempPath gives us unwritable folder for Android and this was mostly a hack to shorten path names that were a problem on jenkins and won't be an issue on GHA.
> Don't update unity base path location

- .github/templates/main.yml
- .github/workflows/main.yml
In https://github.com/realm/realm-dotnet/pull/2564 I forgot to add the correct condition to skip the cache check for the Win81 SDK.
> Add condition for checking win81 cache

- .github/templates/Readme.md
- .github/templates/main.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- Realm/Realm/Realm.csproj
Fix 2 issues related to release workflow:
1- condition for when to build the docs from the main workflow. The problem was that the var used didn't have the name of the branch in it.
2- The artifacts fetched by the release workflow weren't specified with an exact commit number, so random artifact versions were being fetched
Fixes #2498 , #2499
> Fix some CI publish workflow

- Realm/Realm/Configurations/InMemoryConfiguration.cs
- Realm/Realm/Configurations/RealmConfiguration.cs
- Realm/Realm/Configurations/RealmConfigurationBase.cs
- Realm/Realm/Configurations/SyncConfiguration.cs
- Realm/Realm/Handles/SharedRealmHandle.cs
This fix closes the realm if there are exceptions while retrieving the schema from disk when opening the realm in dynamic mode. At the moment it seems that it's actually not possible to make it throw an exception like is shown in the ticket or even in other ways (at least I have not found a way). 
Given this... this is more of a protection in case something changes in the future, more than fixing an actual bug, so I am not sure if I should continue with this. 
If we decide to continue, the same try-catch needs to be put in another two places.
Fixes #1989
> Close realm in case of exceptions while creating schema

- .github/templates/main.yml
- .github/workflows/main.yml
- Jenkinsfile
- Realm/Realm.Fody/ModuleWeaver.cs
- Realm/Realm/RealmWrappersReferences.props
- Tests/Benchmarks/PerformanceTests/PerformanceTests.csproj
- Tests/Realm.Tests/Realm.Tests.csproj
The new TargetFrameworkIdentifiers shipping with .NET 6 are `net6.0-android`, `net6.0-maccatalyst`, `net6.0-ios`, so this PR updates them.
> Update wrapper props to handle the new TFIs shipping with net6

- CHANGELOG.md
- Realm/Realm/Schema/ObjectSchema.cs
- Tests/Benchmarks/PerformanceTests/README.md
- Tests/Benchmarks/PerformanceTests/SchemaTests.cs
Fixes #2194
This will not have massive performance effect for most users as we expect most people to just use the default schema, which is already cached. But for people who do set `ObjectClasses`, it should speed things up nicely.
|                                                                              Method |      Mean |     Error |    StdDev |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|------------------------------------------------------------------------------------ |----------:|----------:|----------:|--------:|-------:|------:|----------:|
| CreateSchema |  3.897 ms | 0.0313 ms | 0.0261 ms | 78.1250 | 7.8125 |     - |    859 KB |
| OpenRealm | 16.567 ms | 0.2680 ms | 0.2375 ms | 62.5000 |      - |     - |    898 KB |
| …
> Add schema cache

- CHANGELOG.md
- Realm/Realm/DatabaseTypes/RealmCollectionBase.cs
- Realm/Realm/DatabaseTypes/RealmObjectBase.cs
- Tests/Realm.Tests/Database/RealmObjectTests.cs
- Tests/Realm.Tests/Realm.Tests.csproj
- Tests/Tests.UWP/Tests.UWP.csproj
- Tests/Tests.iOS/Tests.iOS.csproj
This replaces `[XmlIgnore]` with `[IgnoreDataMember]` as that works for both the Xml and Json serializer. It removes `[Serializable]` as that was only used in the `BinarySerializer` which is very strongly obsoleted.
Finally, it annotates the RealmCollectionBase properties with `[IgnoreDataMember]` to make sure a json serializer doesn't try to touch them and adds tests for both Xml and Json serialization.
A couple of caveats:
1. Newtonsoft.Json doesn't work on Unity out of the box, so we only test on the other platforms.
2. MongoDB.Bson and XmlSerializer don't serialize collections by default, so we're not validating it.
Fixes https://github.com/realm/realm-dotnet/issues/2579
> Don't try to serialize the `DynamicApi` property

- .github/templates/codeql.yml
- .github/templates/common.lib.yml
- .github/templates/main.yml
- .github/workflows/codeql.yml
- .github/workflows/main.yml
- Realm/Realm.Weaver/Analytics.cs
- Tests/Tests.UWP/FodyWeavers.xml
Most CI services will set the environment variable `CI` to some value, so it's a good idea to check for it and make sure we don't count CI builds as actual developers.
* [Github Actions](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables)
* [Travis CI](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables)
* [Appveyor](https://www.appveyor.com/docs/environment-variables/)
* [Jenkins](https://github.com/jenkinsci/jenkins/pull/5370)
Additionally, this cleans up our workflow to set `REALM_DISABLE_ANALYTICS` statically on the entire workflow rather than per at runtime for each job, similarly to https://github.com/realm/realm-js/pull/3918.
> Disable analytics on CI

- .github/templates/publish-release.yml
- .github/workflows/publish-release.yml
This PR introduces several changes to the release workflow:
1. Renames it to publish-release to better differentiate from prepare-release
2. Adds a template to generate it
3. Enables uploading to nuget
4. Uploads the symbols package for Realm
5. Uploads the unity package to npm
6. Assigns the workflow to the production environment
Fixes https://github.com/realm/realm-dotnet/issues/2491
Fixes https://github.com/realm/realm-dotnet/issues/2582
> Tweaks for the publish release workflow

- CHANGELOG.md
- Realm/Realm/DatabaseTypes/RealmObjectBase.cs
- Realm/Realm/Handles/ObjectHandle.cs
- Tests/Realm.Tests/Database/AddOrUpdateTests.cs
- Tests/Realm.Tests/Database/DynamicAccessTests.cs
- Tests/Realm.Tests/Database/PrimaryKeyTests.cs
- Tests/Realm.Tests/Database/RealmObjectTests.cs
- Tests/Realm.Tests/Database/RealmResults/SimpleLINQtests.cs
- Tests/Realm.Tests/Database/TestObjects.cs
- Tests/Realm.Tests/Sync/AppTests.cs
- Tests/Realm.Tests/Sync/PartitionKeyTests.cs
This adds additional tests for RealmObjectBase, which uncovered a bug with setting the PK property via the dynamic API - it didn't go through the PK equality check and happily sent the value down to native. This is now fixed, but writing the tests required renaming a bunch of properties, resulting in a lot of noise in the PR. I've highlighted the important bits.
> Fix DynamicAPI.Set(PK) not validating PK equality

- .github/templates/main.yml
- .github/workflows/main.yml
Start running Win81 tests using net6.0 now that the TLS issues have been resolved.
> Test net6 on win81

- .github/templates/main.yml
- .github/workflows/main.yml
Just a minor refactoring in the template of main.yml where all the artifacts uploads now use a function instead of writing the same code over and over. I tried to make the function simple enough, so more complicated uploads can't use this function but needs to write the upload code by hand. I don't think we should over complicate the helper as what it does covers already 90% of our use cases.
Fixes: no issue was created
> Minor refactoring of uploading artifacts in main.yml template

- Realm/Realm/Realm.csproj
Noticed that we're getting a compile time warning about unreachable code and it turned out that the inline task generator will generate a `return Success` at the end of the method.
> Fix a build warning due to unreachable code

- CHANGELOG.md
- Realm/Realm.Weaver/Extensions/ModuleDefinitionExtensions.cs
- Realm/Realm.Weaver/ImportedReferences.cs
In the unlikely scenario where `System.Linq.Queryable` is not used at all in the user code, but the user calls a method of an interface that `System.Linq.Queryable` implements, the weaver fails to set the correct version number of `System.Linq.Queryable` to import. This resulted in a runtime issue that states that a certain (and wrong) "x.x.x.x" version of `System.Linq.Queryable` can't be found.
The problem comes from the fact that the version number of each assembly was extracted by the weaver from `System.Runtime` giving the wrong number version and only getting it right in most cases by luck. Reading the version number from the assembly with the majority of our dependencies (`Remotion.Linq`) fixed the issue.
Although, to my limited knowledge, no other similar issue has been reported …
> [Weaver] Fix System.Linq.Queryable not correctly referenced when not imported yet

- .github/workflows/main.yml
- CHANGELOG.md
- wrappers/build-ios.sh
The issue has been fixed with newer versions of CMake. So all it took was removing the cmake arg to force Cmake to use the old build system,
Fixes #2171
> Use new XCode build system for iOS wrappers

- CHANGELOG.md
- Realm/Realm/Schema/ObjectSchema.cs
- Tests/Realm.Tests/Database/ConfigurationTests.cs
> Make the configuration type cache concurrent

- CHANGELOG.md
- Realm/Realm.UnityWeaver/UnityWeaver.cs
Previously we would look for the iOS native libraries using an exact path match, which would fail when the package is installed at a non-default location. We're now getting all assets and using LINQ to look for the one whose path is a partial match. We're looking for the path relative to the xcframework, which should never be changed, so this is robust enough to cover all meaningful use cases.
Fixes https://github.com/realm/realm-dotnet/issues/2698
> Fix Unity NRE when Realm is installed at a non-default location

- .github/templates/main.yml
- .github/workflows/main.yml
Test were failing due to a problem with restoring nuget packages. From the logs one could see that msbuild was trying to restore packages for .NET Framework version 1.0 and 2.0. 
This was due to the fact that we were passing `TargetFrameworkVersion` to the project file, and that refers to the .NET Framework (https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-multi-targeting-overview?view=vs-2019)
> Fix MacOS testing error

- CHANGELOG.md
- Realm/Realm/Extensions/RealmSyncExtensions.cs
- Realm/Realm/Handles/AppHandle.cs
- Realm/Realm/Handles/SharedRealmHandle.cs
- Realm/Realm/Realm.cs
- Realm/Realm/Sync/Session.cs
- Tests/Realm.Tests/Sync/SessionTests.cs
- Tests/Realm.Tests/Sync/SyncTestBase.cs
- Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
- wrappers/src/app_cs.cpp
- wrappers/src/shared_realm_cs.cpp
- wrappers/src/sync_session_cs.cpp
This updates to latest Core and adds a `Realm.SyncSession` property that replaces the extension method. The motivation here is threefold - 1) we no longer ship non-sync binaries, so `GetSession` being an extension method is kind of weird, 2)  it improves discoverability, and 3) it allows us to do some weak reference caching to avoid creating a new session every time the property is accessed.
> Update to Core 11.6.0

- .github/templates/main.yml
- .github/workflows/main.yml
- CHANGELOG.md
While LTO builds are slightly slower, they're more likely to be cached (since master builds are LTO enabled anyway).
Fixes #2709
> Enable LTO for all builds

- CHANGELOG.md
- Realm/Realm/Handles/AppHandle.cs
- Realm/Realm/Handles/SyncUserHandle.cs
- Realm/Realm/Native/HttpClientTransport.cs
- Realm/Realm/Sync/User.cs
Updates to latest core master. This uncovered a bug in the way we were marshaling API keys - we used to pass in the native struct through the task completion source, which meant we didn't copy out the strings, thus making them invalid. I'm not sure why this hadn't manifested previously - it's possible that Core was leaking those strings which was fixed in https://github.com/realm/realm-core/pull/5029.
> Update to latest Core

- .github/templates/main.yml
- .github/workflows/main.yml
- CHANGELOG.md
- Tests/Realm.Tests/Database/InstanceTests.cs
- wrappers/src/shared_realm_cs.cpp
Because the change [#5065](https://github.com/realm/realm-core/pull/5065) in core, the wrappers needed a small change to stop a refresh call when getting a shared instance of a read-only realm.
An extra unit test was added to verify that freezing a read-only realm worked as expected.
Fixes #2718
> Read-only realm properly throws when refreshed

- .github/templates/main.yml
- .github/workflows/main.yml
- CHANGELOG.md
S3 urls are case sensitive and nuget package names are lowercased, but versions are not, which resulted in the wrong url being generated - i.e. https://s3.amazonaws.com/realm.nugetpackages/flatcontainer/realm/10.7.1-PR-2695.1703/realm.10.7.1-PR-2695.1703.nupkg instead of https://s3.amazonaws.com/realm.nugetpackages/flatcontainer/realm/10.7.1-pr-2695.1703/realm.10.7.1-pr-2695.1703.nupkg.
> Use lowercase "pr" for prerelease packages

- CHANGELOG.md
- Realm/Realm/Configurations/RealmConfigurationBase.cs
- Realm/Realm/Native/Configuration.cs
- wrappers/src/shared_realm_cs.cpp
- wrappers/src/shared_realm_cs.hpp
Added new config parameter for the fallback path where named pipes used by realm should be created.
Fixes #2751
> Added fallback path

- .github/templates/main.yml
- .github/workflows/main.yml
- CHANGELOG.md
CI tests on release branches will run on cloud-qa instead of cloud-dev to avoid breaking changes that will be fixed before deployment to QA.
> Enable CI tests on cloud-qa

- CHANGELOG.md
- Realm/Realm/Realm.cs
- Tests/Realm.Tests/Database/InstanceTests.cs
Avoiding creating metadata again when freezing a realm, passing it from the parent instead. 
Fixes #2789
> Copy parent metadata when freezing realms

- CHANGELOG.md
- Tools/SetupUnityPackage/Program.cs
- Tools/SetupUnityPackage/SetupUnityPackage.csproj
> Strip [UsedImplicitly] from the Remotion assembly

- CHANGELOG.md
- Realm/Realm/DatabaseTypes/RealmCollectionBase.cs
- Tests/Realm.Tests/Database/CollectionTests.cs
- Tests/Scripts/DeployCluster.ps1
Fixes https://github.com/realm/realm-dotnet/issues/2840
> Don't throw in GetEnumerator when the collection is not valid

- CHANGELOG.md
- Realm/Realm.UnityWeaver/UnityWeaver.cs
- Realm/Realm.UnityWeaver/WeaverAssemblyResolver.cs
…the Unity weaver
Fixes https://github.com/realm/realm-dotnet/issues/2836
> Don't access Applciation.dataPath from a background thread

- Realm/Realm.Fody/Realm.Fody.xcf
The link `https://github.com/realm/realm-dotnet/blob/main/Realm/Realm.Fody/Common/Analytics.cs` does not work.
I've replaced it with:
`https://github.com/realm/realm-dotnet/blob/main/Realm/Realm.Weaver/Analytics.cs`
> Fix analytics link in `Realm.Fody.xcf`

- .github/templates/build-unity.yml
- .github/workflows/build-unity.yml
https://github.com/realm/realm-dotnet/pull/2860 enabled nuget caching for most builds but I forgot to do it for the Unity package step.
Fixes https://github.com/realm/realm-dotnet/issues/2643.
> Enable nuget cache for unity build

- .github/templates/publish-release.yml
- .github/workflows/publish-release.yml
Due to the docs reorg, they changed the path they're using for API docs
> Update S3 path to start with /docs

- .github/templates/codeql.yml
- .github/workflows/codeql.yml
- Tests/Tests.iOS/AppDelegate.cs
CodeQL only works on Windows 2019, but .NET 6.0.5 requires MSBuild 17 which comes with VS 2022. This pins the version used by the workflow to 6.0.4.
> Fix codeql workflow

- Tests/Realm.Tests/Realm.Tests.csproj
* Fixes the way wrappers are selected when they are copied over during the compilation of `Realm.Test`
* Adds `Microsoft.NET.Test.Sdk` to satisfy `.netcore3.1` which before was not finding the `testhost`
* Changes the order in which `TargetFrameworks` are inserted in `Realm.Test` since Visual Studio Run Tests context menu just picks up the first in line
> Fixes some annoyances with running tests from VS

- LICENSE
- README.md
Legal has confirmed that the export compliance clause is not needed on an open source projects such as the Realm SDKs.
This PR replace the LICENSE file with a clean Apache 2 license, ie. no ToC and export compliance. This allows tools such as github to pick up the correct license.
> Remove export compliance from LICENSE and to README.md

- CHANGELOG.md
- Realm/Realm/Realm.cs
- Tests/Realm.Tests/Database/AddOrUpdateTests.cs
Fixes #3020 by validating that objects added via Realm.Add have not been removed prior.
> Add validation and tests when adding invalid (removed) object.

- CHANGELOG.md
- Realm/Realm/DatabaseTypes/Accessors/ManagedAccessor.cs
- Realm/Realm/DatabaseTypes/RealmObjectBase.cs
- Tests/Realm.Tests/Database/RealmObjectTests.cs
Fixes #3045.
When creating a `RealmObject` that throws before being initialized, `_accessor` will be `null`. When the object was garbage collected, `RealmObject`'s destructor would call `_accessor.UnsubscribeFromNotifications()` causing a crash due to `NullReferenceException`.
Solution:
`RealmObject`'s destructor was removed and instead added the call to `UnsubscribeFromNotifications()` in `ManagedAccessor`'s destructor. (For an `UnmanagedAccessor`, a call to `UnsubscribeFromNotifications()` does nothing.)
> Fix crash in RealmObject finalizer due to null _accessor.

- .vscode/extensions.json
- .vscode/settings.json
Allows to run .NET tests in VSCode by first installing extension **.NET Core Test Explorer**.
> Add VSCode settings for running .NET tests

- CHANGELOG.md
- Realm/Realm/Handles/SessionHandle.cs
Reported on the forums: https://www.mongodb.com/community/forums/t/flexible-sync-when-offline/194370/2
> Fix an NRE in session property changed callback

- CHANGELOG.md
- Realm/Realm/DatabaseTypes/Accessors/IRealmAccessor.cs
- Realm/Realm/DatabaseTypes/Accessors/ManagedAccessor.cs
- Realm/Realm/DatabaseTypes/Accessors/UnmanagedAccessor.cs
- Realm/Realm/DatabaseTypes/EmbeddedObject.cs
- Realm/Realm/DatabaseTypes/IRealmObjectBase.cs
- Realm/Realm/Handles/ObjectHandle.cs
- Realm/Realm/Schema/ObjectSchema.cs
- Tests/Realm.Tests/Database/EmbeddedObjectsTests.cs
- Tests/Realm.Tests/Sync/AsymmetricObjectTests.cs
- wrappers/src/object_cs.cpp
Fixes #2742.
Makes `Parent` accessible on `IEmbeddedObject`s and returns `null` for unmanaged embedded objects.
> Get parent of embedded object.

- CHANGELOG.md
- Realm/Realm/DatabaseTypes/RealmCollectionBase.cs
- Tests/Realm.Tests/Database/CollectionTests.cs
- Tests/Realm.Tests/Sync/AsymmetricObjectTests.cs
Removes the snapshotting step if the collection is frozen and adds a basic test for that.
Fixes https://github.com/realm/realm-dotnet/issues/2815
> Stop snapshotting during iteration on frozen collections

- CHANGELOG.md
- Realm/Realm/Handles/SharedRealmHandle.cs
- Realm/Realm/Realm.cs
- Tests/Realm.Tests/Database/RemoveTests.cs
- Tests/Realm.Tests/Sync/FlexibleSyncTests.cs
- Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
- wrappers/src/shared_realm_cs.cpp
Uses a single native call to remove all objects from Realm through `Realm.RemoveAll()`
Fixes https://github.com/realm/realm-dotnet/issues/2233
> Add native removeAll implementation

- CHANGELOG.md
- Realm/Realm/Sync/App.cs
passing null as third arg will now throw a more descriptive `ArgumentNullException` error
Fixes #3011
> add null check for functionArgs in CallResetPasswordFunctionAsync

- CHANGELOG.md
- Realm/Realm/Configurations/RealmConfigurationBase.cs
- Realm/Realm/InteropConfig.cs
- Realm/Realm/Sync/App.cs
- Tests/Realm.Tests/App.Local.config
- Tests/Realm.Tests/Database/InstanceTests.cs
- Tests/Realm.Tests/RealmTest.cs
- Tests/Realm.Tests/Sync/AppTests.cs
- Tests/Realm.Tests/Sync/SyncConfigurationTests.cs
Added helper method to allow us to tell whether we try to get a defaultStorageFolder for a realm or app-config 
Fixes #2863
> disambiguate error message when getting a defaultStorageFolder for realm or app-config

- CHANGELOG.md
- wrappers/src/app_cs.cpp
- wrappers/src/app_cs.hpp
- wrappers/src/marshalling.hpp
- wrappers/src/sync_user_cs.cpp
Removes unnecessary serialisation/deserialisation of args parameter passed to CallAsync
Fixes #3079
> Optimize callAsync

- CHANGELOG.md
- Realm/Realm/DataBinding/WovenPropertyInfo.cs
- Realm/Realm/DataBinding/WovenSetterMethodInfo.cs
- Tests/Realm.Tests/Database/ReflectableTypeTests.cs
Avoids calling the setter for bound properties in case the new value is the same as the old one. This avoids a problem in MAUI in which the UI is calling the setter unnecessarily, and causing an issue in case objects outside of the user's write permissions are modified
Fixes #3128
> Avoid calling setter for bound properties for same value

- .github/workflows/no-response.yml
> Add no-response workflow to close stale issues

- CHANGELOG.md
- Realm/Realm/Configurations/SyncConfigurationBase.cs
- Realm/Realm/Native/AppConfiguration.cs
- Realm/Realm/Native/SyncConfiguration.cs
- Realm/Realm/Sync/App.cs
- Realm/Realm/Sync/AppConfiguration.cs
- Realm/Realm/Sync/SyncTimeoutOptions.cs
- Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
- Tests/Realm.Tests/TestHelpers.cs
- wrappers/src/app_cs.cpp
- wrappers/src/shared_realm_cs.cpp
- wrappers/src/shared_realm_cs.hpp
Adds a few sync timeout options to AppConfiguration as well as an option to cancel async operations on non-fatal session errors.
Fixes https://github.com/realm/realm-dotnet/issues/3222
Fixes https://github.com/realm/realm-dotnet/issues/3223
> Expose options to control sync timeouts

- CHANGELOG.md
- Realm/Realm/Logging/Logger.cs
- Realm/Realm/Sync/App.cs
- Realm/Realm/Sync/AppConfiguration.cs
- Tests/Realm.Tests/Sync/AppTests.cs
> [v11] 6. Remove AppConfiguration.CustomLogger

- CHANGELOG.md
- Realm/Realm/Handles/SyncUserHandle.cs
- Realm/Realm/Sync/User.cs
- Tests/Realm.Tests/Sync/UserManagementTests.cs
- Tools/DeployApps/BaasClient.cs
- wrappers/src/sync_user_cs.cpp
> [v11] 8. Remove deprecated User.PushClient

- CHANGELOG.md
- Realm/Realm/DatabaseTypes/RealmCollectionBase.cs
- Tests/Realm.Tests/Database/NotificationTests.cs
Fixes https://github.com/realm/realm-dotnet/issues/2854
This doesn't technically need v11, but it would have conflicted, so I decided to do it on top of the nullable annotations branch.
> [v11] 12. Raise Replace events for collection notifications

- CHANGELOG.md
- Realm/Realm/Handles/AppHandle.cs
- Realm/Realm/Handles/SharedRealmHandle.cs
- Realm/Realm/Logging/LogLevel.cs
- Realm/Realm/Logging/Logger.cs
- Realm/Realm/Native/AppConfiguration.cs
- Realm/Realm/Sync/App.cs
- Tests/Realm.Tests/Database/GuidRepresentationMigrationTests.cs
- Tests/Realm.Tests/Database/InstanceTests.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/LoneClass_generated.cs
- Tests/Realm.Tests/RealmTest.cs
- Tests/Realm.Tests/TestHelpers.cs
- wrappers/src/app_cs.cpp
- wrappers/src/marshalling.cpp
- wrappers/src/shared_realm_cs.cpp
- wrappers/src/shared_realm_cs.hpp
- wrappers/src/sync_session_cs.cpp
Fixes https://github.com/realm/realm-dotnet/issues/2910
This will fail on CI due to https://github.com/realm/realm-core/issues/6443, but that is a regression in Core and not something that will affect the feature's implementation.
> Integrate Core logging

- CHANGELOG.md
- Directory.build.props
- Realm/Realm.UnityUtils/Realm.UnityUtils.csproj
- Realm/Realm.UnityWeaver/Realm.UnityWeaver.csproj
- Realm/Realm.UnityWeaver/UnityWeaver.cs
Fixes https://github.com/realm/realm-dotnet/issues/3306
> Hack around Unity editor API change

- .github/templates/common.lib.yml
- .github/templates/publish-prerelease.yml
- .github/templates/publish-release.yml
- .github/workflows/publish-prerelease.yml
- .github/workflows/publish-release.yml
Replaces https://github.com/realm/realm-dotnet/pull/2822
> Allow publishing unity package on prerelease workflow

- .github/templates/common.lib.yml
- .github/templates/test.lib.yml
- .github/workflows/cleanup-baas.yml
- .github/workflows/deploy-baas.yml
- .github/workflows/prepare-release.yml
- .github/workflows/publish-release.yml
- .github/workflows/test-android.yml
- .github/workflows/test-code-coverage.yml
- .github/workflows/test-ios.yml
- .github/workflows/test-macos.yml
- .github/workflows/test-net-core.yml
- .github/workflows/test-net-framework.yml
- .github/workflows/test-tvos.yml
- .github/workflows/test-uwp-managed.yml
- .github/workflows/wipe-clusters.yml
- wrappers/README.md
> Update ci-actions to latest commit

- .github/templates/test-weaver.yml
- .github/templates/wrappers.yml
- .github/workflows/test-weaver.yml
- .github/workflows/wrappers.yml
- wrappers/build.ps1
> Try to use a different MSVC version

- CHANGELOG.md
- Realm/Realm.SourceGenerator/Diagnostics.cs
- Realm/Realm.Weaver/RealmWeaver.cs
- Realm/Realm.Weaver/WeaveResults.cs
- Realm/Realm/Realm.csproj
- Tests/Weaver/AnalyticsAssembly/Program.cs
- Tests/Weaver/Realm.Fody.Tests/WeaverTests.cs
Fixes https://github.com/realm/realm-dotnet/issues/3352
> Better warning for skipped properties with attributes

- CHANGELOG.md
- Realm/Realm.Weaver/Analytics/Analytics.cs
- Realm/Realm.Weaver/Analytics/AnalyticsUtils.cs
- Realm/Realm.Weaver/RealmWeaver.cs
This PR attempts to address the issues highlighted in https://github.com/realm/realm-dotnet/issues/3364 by:
1. Creating a hidden window for the `reg` invocation. This should address the annoyance of a terminal window popping up every time we build the project.
2. Caching the results of the `reg` invocation. Those are unlikely to change, so no need to run it on every build.
Fixes https://github.com/realm/realm-dotnet/issues/3364
> Reduce number of reg invocations on Unity

- CHANGELOG.md
- Realm/Realm/DatabaseTypes/RealmList.cs
- Realm/Realm/DatabaseTypes/RealmSet.cs
- Realm/Realm/Handles/SetHandle.cs
- Realm/Realm/Linq/RealmResults.cs
- Tests/Realm.Tests/Database/RealmResults/SimpleLINQtests.cs
- Tests/Realm.Tests/Database/RealmSetTests.cs
- wrappers/src/results_cs.cpp
- wrappers/src/set_cs.cpp
Looks like MAUI really wants to use indexof and our validations are making it quite hard to data bind to realm collections directly. Not sure if this is the best approach here, but need something hacky for a demo.
> Relax IndexOf conditions to handle null and unmanaged objects

- CHANGELOG.md
- Realm/Realm/Configurations/PartitionSyncConfiguration.cs
- Realm/Realm/Configurations/SyncConfigurationBase.cs
- Realm/Realm/DatabaseTypes/RealmValue.cs
- Realm/Realm/Handles/AppHandle.cs
- Realm/Realm/Handles/SessionHandle.cs
- Realm/Realm/Handles/SyncUserHandle.cs
- Realm/Realm/Native/AppConfiguration.cs
- Realm/Realm/Native/PrimitiveValue.cs
- Realm/Realm/Native/SynchronizationContextScheduler.cs
- Realm/Realm/Realm.cs
- Realm/Realm/Schema/RealmSchema.cs
- Realm/Realm/Sync/App.cs
- Realm/Realm/Sync/AppConfiguration.cs
- Realm/Realm/Sync/FlexibleSync/SubscriptionSet.cs
- Realm/Realm/Sync/User.cs
- Realm/Realm/Thread Handover/ThreadSafeReference.cs
- Realm/Realm/Transaction.cs
- Tests/Realm.Tests/Sync/AppTests.cs
- Tests/Realm.Tests/Sync/SessionTests.cs
- Tests/Realm.Tests/Sync/SyncTestBase.cs
- wrappers/src/app_cs.cpp
Alleviates a bit of the pain reported in https://github.com/realm/realm-dotnet/issues/3383
Fixes https://github.com/realm/realm-dotnet/issues/3382
Exposes `App.BaseFilePath`, `App.BaseUri`, and `App.Id`.
> Expose base file path and base uri on App

- .github/templates/common.lib.yml
- .github/templates/test-code-coverage.yml
- .github/workflows/test-code-coverage.yml
- Tests/Realm.Tests/Database/APITests.cs
Noticed coverage was quite lacking there and while it's not particularly complex functionality, figured it's worth adding a simple test to ensure it works as intended.
> Add more extensive coverage for Task.Timeout

- Realm/Realm/Helpers/SerializationHelper.cs
- Realm/Realm/Realm.csproj
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/Company_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/CoordinatesEmbeddedObject_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/CustomGeoPoint_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/ObjectWithInvalidGeoPoints_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/TopLevelGeoPoint_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/TypeEmbeddedObject_generated.cs
- Tools/DeployApps/BaasClient.cs
- Tools/DeployApps/DeployApps.csproj
> Update MongoDB.Bson to 2.19.1

- CHANGELOG.md
- Realm/Realm/Handles/SharedRealmHandle.cs
- Tests/Realm.Tests/Database/AsyncTests.cs
Saw that in a CI run: https://github.com/realm/realm-dotnet/actions/runs/5671307649/job/15368851506
Also adds a missing `ex.ThrowIfNecessary()` in `RefreshAsync`.
The rest of the changes are primarily cosmetic addressing some local member shadowing which was irritating me and the IDE.
> Fix a race between canceling async transaction and Realm.Dispose

- Realm/Realm/Transaction.cs
- Tests/Realm.Tests/Database/AsyncTests.cs
- Tests/Realm.Tests/Database/InstanceTests.cs
- Tests/Realm.Tests/Database/RealmSetTests.cs
- Tests/Realm.Tests/Database/ThreadHandoverTests.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/A_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/B_generated.cs
Saw we had two uncovered branches for async writes and figured we could add a sanity test for those:
Additionally, this adds a test for set thread references as those were completely untested (luckily they worked correctly).
> Add a few tests for uncovered code

- .github/actions/benchmark-uploader/charts-template.json
Adds a RunId filter as it was getting quite overwhelming - the 2149 value is chosen to skip over a period when benchmarks were reporting incorrect data.
Also switches to vertical rather than diagonal axis labels as those are easier to read.
> Update charts template

- CHANGELOG.md
- Realm/Realm/Realm.cs
- Realm/Realm/Sync/Session.cs
- Tests/Realm.Tests/Database/RelationshipTests.cs
- Tests/Realm.Tests/Sync/SessionTests.cs
- Tests/Realm.Tests/TestHelpers.cs
We are trying to avoid that `realm.SyncSession` gets garbage collected, at least until there are subscribers to `realm.SyncSession.PropertyChanged`
> Avoiding GC of session when there are subscribers

- CHANGELOG.md
- Realm/Realm/Native/HttpClientTransport.cs
- Realm/Realm/Native/MarshaledPair.cs
- Realm/Realm/Native/SyncError.cs
Use our own struct for marshaling instead of using `System.KeyValuePair<TKey, TValue>`.
Fixes #3434
> Don’t use KeyValuePair in marshaling because it’s overloaded on UWP

- CHANGELOG.md
- Realm/Realm.SourceGenerator/ClassCodeBuilder.cs
- Realm/Realm.SourceGenerator/CodeEmitter.cs
- Realm/Realm.SourceGenerator/Diagnostics.cs
- Realm/Realm.SourceGenerator/DiagnosticsEmitter.cs
- Realm/Realm.SourceGenerator/GeneratorConfig.cs
- Realm/Realm.SourceGenerator/Parser.cs
- Realm/Realm.SourceGenerator/RealmGenerator.cs
- Realm/Realm/DatabaseTypes/RealmCollectionBase.cs
- Realm/Realm/DatabaseTypes/RealmObjectBase.cs
- Tests/SourceGenerators/SourceGeneratorAssemblyToProcess/.globalconfig
> Allow customizing json ignore attribute for serialized classes

- CHANGELOG.md
- Realm/Realm/Handles/RealmHandle.cs
- Realm/Realm/Handles/SessionHandle.cs
- Realm/Realm/Handles/SharedRealmHandle.cs
- Realm/Realm/Handles/SyncUserHandle.cs
- Realm/Realm/Native/NativeCommon.cs
- Realm/Realm/Sync/User.cs
- Tests/Realm.Tests/Sync/UserManagementTests.cs
- wrappers/src/sync_user_cs.cpp
Addresses https://github.com/realm/realm-dotnet/issues/3429, but is not a real fix as it only notifies that the user changed, but doesn't tell us what exactly changed. We need https://github.com/realm/realm-core/issues/6516 to achieve more precise notifications.
> Add User.Changed event

- CHANGELOG.md
- Realm/Realm.PlatformHelpers/Realm.PlatformHelpers.csproj
- Realm/Realm.SourceGenerator/ClassCodeBuilder.cs
- Realm/Realm.SourceGenerator/Diagnostics.cs
- Realm/Realm.SourceGenerator/Parser.cs
- Tests/SourceGenerators/Realm.SourceGenerator.Tests/ComparisonTests.cs
- Tests/SourceGenerators/Realm.SourceGenerator.Tests/SourceGenerationTest.cs
- Tests/SourceGenerators/SourceGeneratorAssemblyToProcess/ErrorClasses/CollectionErrors.cs
- Tests/SourceGenerators/SourceGeneratorAssemblyToProcess/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/CollectionErrors.diagnostics.cs
Fixes https://github.com/realm/realm-dotnet/issues/3455
> Emit errors for collection assignments

- CHANGELOG.md
- Realm/Realm/Handles/AppHandle.EmailPassword.cs
- Realm/Realm/Sync/App.cs
- Tests/Realm.Tests/Sync/SyncTestHelpers.cs
- Tests/Realm.Tests/Sync/UserManagementTests.cs
- Tools/DeployApps/BaasClient.cs
- wrappers/src/app_cs.cpp
> Added RetryCustomConfirmationAsync

- Realm/Realm/Realm.cs
- Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
> Added missing docs and tests for `WriteCopy` when using flexible sync

- CHANGELOG.md
- Realm/Realm/Realm.csproj
- Tools/SetupUnityPackage/CommandLineOptions/RealmOptions.cs
4.3.0 has been marked as vulnerable. While users can manually upgrade to 4.3.1, it's easy to miss, so it's better to just pull in the latest non-vulnerable version. This is a transitive dependency we take on through System.Net.WebSockets.Client, but unfortunately the latest version of that package is 4.3.2 and it still depends on Security 4.3.0.
> Bump System.Net.Security to 4.3.2

- CHANGELOG.md
- Realm/Realm/Handles/AppHandle.cs
- Tests/Realm.Tests/Database/GuidRepresentationMigrationTests.cs
- Tests/Realm.Tests/Sync/SyncTestBase.cs
- wrappers/src/app_cs.cpp
> Updated core to 13.26.0

- .github/actions/run-android-device-farm-test/action.yml
- .github/templates/test-net-framework.yml
- .github/templates/test-uwp-managed.yml
- .github/workflows/test-net-framework.yml
- .github/workflows/test-uwp-managed.yml
Tests on CI are timing out since we added new sync tests, so for now we're increasing the timeouts.
> Increasing timeouts on Windows/UWP/Android

- Tests/Realm.Tests/Sync/SessionTests.cs
- Tests/Realm.Tests/Sync/StaticQueriesTests.cs
- Tests/Realm.Tests/Sync/UserManagementTests.cs
> Fix various failing CI tests

- Realm/Realm/DatabaseTypes/RealmValue.cs
- Tests/Realm.Tests/Database/RealmValueWithCollections.cs
> RNET-1133: Fixed equality comparison for collections in mixed

- Docs/index.md
- NuGet.md
- README.md
- Realm/Realm.SourceGenerator/Realm.SourceGenerator.csproj
- Realm/Realm.Unity/README.md
- Realm/Realm.Unity/package.json
- Realm/Realm.UnityUtils/Realm.UnityUtils.csproj
- Realm/Realm/Configurations/FlexibleSyncConfiguration.cs
- Realm/Realm/Configurations/PartitionSyncConfiguration.cs
- Realm/Realm/Configurations/SyncConfigurationBase.cs
- Realm/Realm/Exceptions/RealmMigrationNeededException.cs
- Realm/Realm/Exceptions/RealmSchemaValidationException.cs
- Realm/Realm/Exceptions/Sync/ErrorCode.cs
- Realm/Realm/Extensions/CollectionExtensions.cs
- Realm/Realm/Helpers/AsyncHelper.cs
- Realm/Realm/Migration.cs
- Realm/Realm/Schema/ObjectSchema.cs
- Realm/Realm/Sync/ApiKey.cs
- Realm/Realm/Sync/Credentials.cs
- Realm/Realm/Sync/ErrorHandling/ClientResetHandlerBase.cs
- Realm/Realm/Sync/ErrorHandling/DiscardUnsyncedChangesHandler.cs
- Realm/Realm/Sync/ErrorHandling/ManualRecoveryHandler.cs
- Realm/Realm/Sync/ErrorHandling/RecoverOrDiscardUnsyncedChangesHandler.cs
- Realm/Realm/Sync/ErrorHandling/RecoverUnsyncedChangesHandler.cs
- Realm/Realm/Sync/User.cs
- SUPPORT.md
> Update to new documentation URL

- CHANGELOG.md
- Realm/Realm/Handles/AppHandle.cs
- Realm/Realm/Helpers/ExperimentalAttribute.cs
- Realm/Realm/Sync/App.cs
- Tests/Realm.Tests/Sync/AppTests.cs
- wrappers/src/app_cs.cpp
Fixes https://github.com/realm/realm-dotnet/issues/3521
> RNET-1109: Add App.UpdateBaseUri

- .github/build-workflows.ps1
- .github/pkl-workflows/Readme.md
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/AsymmetricObjectWithAllTypes_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/AsymmetricObjectWithEmbeddedDictionaryObject_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/AsymmetricObjectWithEmbeddedListObject_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/AsymmetricObjectWithEmbeddedRecursiveObject_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/BasicAsymmetricObject_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/Dotnet_3597_Old_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/Dotnet_3597_generated.cs
- Tools/DeployApps/BaasClient.cs
Had those staged, but seems I forgot to commit them before merging https://github.com/realm/realm-dotnet/pull/3603.
> Commit some forgotten pkl-related changes

- .editorconfig
- Tests/Realm.Tests/Sync/SyncTestHelpers.cs
- Tools/DeployApps/BaasClient.cs
Fixes https://github.com/realm/realm-dotnet/issues/3627
> RNET-1158: Fix argument extraction for test client

- CHANGELOG.md
- Realm/Realm/DatabaseTypes/QueryArgument.cs
- Tests/Realm.Tests/Database/CollectionTests.cs
Fixes https://github.com/realm/realm-dotnet/issues/3619
> RNET-1155: Add more validation to .Filter arguments

- Realm/Realm/Native/PrimitiveValue.cs
- Realm/Realm/Native/SyncSocketProvider.EventLoop.cs
- Realm/Realm/Native/SyncSocketProvider.WebSocket.cs
- Realm/Realm/Native/SyncSocketProvider.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/AsymmetricObjectWithAllTypes_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/AsymmetricObjectWithEmbeddedDictionaryObject_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/AsymmetricObjectWithEmbeddedListObject_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/AsymmetricObjectWithEmbeddedRecursiveObject_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/BasicAsymmetricObject_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/Dotnet_3597_Old_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/Dotnet_3597_generated.cs
> Cleanup a few websocket things

- CHANGELOG.md
- Realm/Realm/Handles/SessionHandle.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/Dotnet_3597_Old_generated.cs
- Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/Dotnet_3597_generated.cs
- Tests/Realm.Tests/Sync/SessionTests.cs
- wrappers/src/async_open_task_cs.cpp
- wrappers/src/sync_session_cs.cpp
- wrappers/src/sync_session_cs.hpp
This PR uses the correct core value for the progress notification, and adds some basic tests
Fixes #3580
> RNET-1137: Fix progress notification

- CHANGELOG.md
- Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
> Update to Core 14.10.2-14-gf66e24d03

- Tests/Realm.Tests/Sync/DataTypeSynchronizationTests.cs
> Reenable CollectionMerge test

- CHANGELOG.md
> Use Core 14.10.3

- CHANGELOG.md
- Realm/Realm.UnityUtils/Initializer.cs
- Realm/Realm.UnityUtils/UnityLogger.cs
- Realm/Realm/Handles/RealmHandle.cs
- Realm/Realm/Handles/SessionHandle.cs
- Realm/Realm/Handles/SharedRealmHandle.cs
- Realm/Realm/Handles/SyncUserHandle.cs
- Realm/Realm/Helpers/Argument.cs
- Realm/Realm/Logging/LogCategory.cs
- Realm/Realm/Logging/Logger.cs
- Realm/Realm/Native/NativeCommon.cs
- Realm/Realm/Native/SyncSocketProvider.EventLoop.cs
- Realm/Realm/Native/SyncSocketProvider.WebSocket.cs
- Realm/Realm/Native/SyncSocketProvider.cs
- Realm/Realm/Realm.cs
- Realm/Realm/Sync/ProgressNotifications/ProgressNotificationToken.cs
- Tests/Realm.Tests/Database/GuidRepresentationMigrationTests.cs
- Tests/Realm.Tests/Database/InstanceTests.cs
- Tests/Realm.Tests/Database/LoggerTests.cs
- Tests/Realm.Tests/Database/NotificationTests.cs
- Tests/Realm.Tests/RealmTest.cs
- Tests/Realm.Tests/Sync/AppTests.cs
- Tests/Realm.Tests/Sync/SyncTestHelpers.cs
- Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
- wrappers/src/marshalling.hpp
- wrappers/src/shared_realm_cs.cpp
Deprecates `Logger` in favor of its new base class `RealmLogger` (see notes below on avoiding breaking changes).
Primarily, enables more control over which category of messages should be logged and at which criticality level, by setting and getting a `LogLevel` for a given `LogCategory`. The hierarchy of categories starts at `LogCategory.Realm`.
```csharp
RealmLogger.SetLogLevel(LogLevel.Warn, LogCategory.Realm.Sync);
RealmLogger.GetLogLevel(LogCategory.Realm.Sync.Client.Session); // LogLevel.Warn
```
Adds a function logger that accepts a callback that will receive the `LogLevel`, `LogCategory`, and the message when invoked.
```csharp
RealmLogger.Default = RealmLogger.Function((level, category, message) => /* custom implementation */);
```
Adds a `RealmLogger.Log()` overload taking a …
> RNET-1161: Implement support for using a log level for a specific log category

- .github/pkl-workflows/helpers/Actions.pkl
- .github/pkl-workflows/helpers/Package.pkl
- .github/pkl-workflows/helpers/Steps.pkl
- .github/pkl-workflows/wrappers.pkl
- .github/workflows/main.yml
- .github/workflows/pr.yml
- .github/workflows/wrappers.yml
- CHANGELOG.md
- Realm/AssemblyInfo.props
- Realm/Realm.Unity/package.json
> Prepare for 12.3.0

- Tests/Realm.Tests/Database/RealmValueTests.cs
- Tests/Realm.Tests/Database/RealmValueWithCollections.cs
- Tests/Realm.Tests/Database/TestObjects.cs
- Tests/Realm.Tests/Sync/DataTypeSynchronizationTests.cs
Fixes https://github.com/realm/realm-dotnet/issues/3623
> RNET-1156: Add test for merging new objects

- CHANGELOG.md
> Update core to 14.12.0

- CHANGELOG.md
- Realm/Realm/Native/AppConfiguration.cs
- Realm/Realm/Sync/App.cs
- Realm/Realm/Sync/ReconnectBackoffOptions.cs
- Realm/Realm/Sync/SyncTimeoutOptions.cs
- wrappers/src/app_cs.cpp
> Expose ReconnectBackoffOptions on SyncTimeoutOptions

- CHANGELOG.md
- Realm/Realm/Native/SyncSocketProvider.WebSocket.cs
When managed websockets are enabled we use array pooling to cut down on constant managed heap allocations for the byte arrays that store the sync messages Core wants us to send. However there is a chance that if a rented array is bigger than the buffer we need to store we will attempt to send the entire array, including stale data it contained previously. This is avoided by using the `ArraySegment<T>` constructor that accepts the explicit offset and length parameters.
Fixes #3671
> RNET-1175 Fix potential outgoing message corruption in managed websockets

- CHANGELOG.md
- Realm/AssemblyInfo.props
- Realm/Realm.Unity/package.json
> Prepare for 12.4.1

- CHANGELOG.md
- Realm/AssemblyInfo.props
- Realm/Realm.Unity/package.json
> Prepare for 12.5.0
