realm/realm-dotnet

CHANGELOG.md, Realm.Shared/Realm.cs, internals/Realm-dotnet Code Change Diary - Andy Dent.txt
Throws an exception where it can be seen by user rather than in Debug Console.
=> Ad/bug/getinstance crash #541

Realm.PCL/RealmConfigurationPCL.cs
=> Add missing members to PCL RealmConfiguration

NuGet/NuGet.Library/Realm.targets
=> Use more relative paths in NuGet targets

RealmWeaver/ModuleWeaver.cs, Tests/WeaverTests/AssemblyToProcess/AssemblyToProcess.csproj, Tests/WeaverTests/AssemblyToProcess/ClassWithStaticProperty.cs
=> Weaver should ignore static properties

Realm.Shared/linq/RealmResultsVisitor.cs, Realm.Shared/native/NativeQuery.cs, Tests/IntegrationTests.Shared/PeopleTestsBase.cs, Tests/IntegrationTests.Shared/Person.cs, Tests/IntegrationTests.Shared/SimpleLINQtests.cs, wrappers/src/query_cs.cpp
=> Add support for queries on Int64 properties

Realm.XamarinIOS/libwrappers.linkwith.cs, wrappers/wrappers.xcodeproj/project.pbxproj
=> Add support for ArmV7s

NuGet/NuGet.Library/Realm.nuspec
Custom NuGet properties such as `$Configuration$` can be passed to NuGet by appending `-Properties Configuration=${configuration}` to the command.
=> Changes to nuspec for CI

.nuget/packages.config, Tests/WeaverTests/RealmWeaver.Tests/FodyWeavers.xml, Tests/WeaverTests/RealmWeaver.Tests/RealmWeaver.Tests.csproj, Tests/WeaverTests/RealmWeaver.Tests/WeaverTests.cs
This changes the `RealmWeaver.Tests` project so that it builds from the OS X Terminal. The goal is to build these from the command-line and run them with the NUnit Console Runner as part of CI.
=> Prepare weaver tests for CI

RealmWeaver/ModuleWeaver.cs
=> Weaver refactoring + general exception catching in weaving property

RealmWeaver/ModuleWeaver.cs, Tests/WeaverTests/AssemblyToProcess/FaultyClasses.cs, Tests/WeaverTests/RealmWeaver.Tests/WeaverTests.cs
=> Weaver error when RealmObject class is missing default constructor

CHANGELOG.md, Tests/IntegrationTests.Shared/SortingTests.cs, internals/Realm-dotnet Code Change Diary - Andy Dent.txt
SortingTests.cs
- added SortsAccentedAndSpecialCorrectly (will fail on previous builds)
=> Doc and test updates to match 0.76.1 changes

Tests/IntegrationTests.Shared/RelationshipTests.cs, internals/Realm-dotnet Code Change Diary - Andy Dent.txt
RelationshipTests.cs
- TestDeleteChildren added with Product and Report class definitions
=> #639 Sample code to verify approach for cascading delete workaround

examples/QuickJournal/QuickJournal/JournalEntry.cs, examples/QuickJournal/QuickJournal/Views/JournalEntriesPage.xaml, examples/QuickJournal/QuickJournal/Views/JournalEntryDetailsPage.xaml
This demonstrates the new support for `INotifyPropertyChanged` in the weaver.
=> Add Title property to QuickJournal example

CHANGELOG.md, Realm.PCL/Realm.PCL.csproj, Realm.PCL/RealmObjectPCL.cs, Realm.Shared/Realm.Shared.projitems, Realm.Shared/RealmObject.cs, Realm.Shared/exceptions/RealmException.cs, Realm.Shared/exceptions/RealmExceptionCodes.cs, Realm.Shared/exceptions/RealmInvalidObjectException.cs, Tests/IntegrationTests.Shared/AccessTests.cs, Tests/IntegrationTests.Shared/ObjectIntegrationTests.cs, wrappers/src/error_handling.cpp, wrappers/src/error_handling.hpp, wrappers/src/realm_error_type.hpp, wrappers/src/row_cs.cpp
=> Row validation

Realm.Shared/extensions/RealmResultsCollectionChanged.cs, Tests/IntegrationTests.Shared/NotificationTests.cs
=> Use IOrderedQueryable instead of RealmResults for ToNotifyCollectionChanged

NuGet/NuGet.Library/Realm.targets
=> Make Realm.targets verify the specification of solutiondir

Realm.Shared/native/NativeSchema.cs, wrappers/src/object-store/src/property.hpp, wrappers/src/schema_cs.cpp, wrappers/wrappers.vcxproj, wrappers/wrappers.vcxproj.filters
..also some small fixes to make it compile on Windows
=> Use unsigned char for PropertyType enum

Realm.Shared/PreserveAttribute.cs, Realm.Shared/handles/SharedRealmHandle.cs, RealmWeaver/ModuleWeaver.cs, Tests/IntegrationTests.Shared/AccessTests.cs, Tests/IntegrationTests.Shared/AsyncTests.cs, Tests/IntegrationTests.Shared/ConfigurationTests.cs, Tests/IntegrationTests.Shared/DateTimeTests.cs, Tests/IntegrationTests.Shared/InstanceTests.cs, Tests/IntegrationTests.Shared/LINQvariableTests.cs, Tests/IntegrationTests.Shared/NotificationTests.cs, Tests/IntegrationTests.Shared/ObjectIntegrationTests.cs, Tests/IntegrationTests.Shared/PeopleTestsBase.cs, Tests/IntegrationTests.Shared/PerformanceTests.cs, Tests/IntegrationTests.Shared/Person.cs, Tests/IntegrationTests.Shared/RefreshTests.cs, Tests/IntegrationTests.Shared/RelationshipTests.cs, Tests/IntegrationTests.Shared/RemoveTests.cs, Tests/IntegrationTests.Shared/SimpleLINQtests.cs, Tests/IntegrationTests.Shared/SortingTests.cs, Tests/IntegrationTests.Shared/StandAloneObjectTests.cs, Tests/IntegrationTests.Shared/TestObjects.cs, Tests/IntegrationTests.XamarinAndroid/IntegrationTests.XamarinAndroid.csproj, Tests/IntegrationTests.XamarinIOS/IntegrationTests.XamarinIOS.csproj, Tests/WeaverTests/RealmWeaver.Tests/WeaverTests.cs
=> Ensure linking works

CHANGELOG.md, Tests/IntegrationTests.Shared/SortingTests.cs
=> Revert to old sort order

CHANGELOG.md, Realm.sln, RealmWeaver/ModuleWeaver.cs, Tests/PurePCLBuildableTest/Class1.cs, Tests/PurePCLBuildableTest/FodyWeavers.xml, Tests/PurePCLBuildableTest/Properties/AssemblyInfo.cs, Tests/PurePCLBuildableTest/PurePCLBuildableTest.csproj, Tests/PurePCLBuildableTest/packages.config, Tests/ThreeLayerRealmXF/PurePCLViewModel/PurePCLViewModel.csproj, Tests/ThreeLayerRealmXF/ThreeLayerRealmXF/ThreeLayerRealmXF.iOS/ThreeLayerRealmXF.iOS.csproj, internals/Realm-dotnet Code Change Diary - Andy Dent.txt
I think this is a robust fix based on building the PCL project now in the Realm.sln
=> Ad/bug/fix not weaving pcl #715

Realm.PCL/RealmListPCL.cs, Realm.Shared/RealmList.cs, Realm.Shared/exceptions/RealmMigrationNeededException.cs
very trivial changes. Substantially more needs to be written for #737
=> Fix comment errors

CHANGELOG.md, Realm.Shared/linq/RealmResults.cs
=> Make RealmResults implement IQueryable.Provider implicitly

Tests/IntegrationTests.Shared/DateTimeTests.cs
=> Add test for indexed DateTimeOffset

CHANGELOG.md, Realm.Shared/handles/QueryHandle.cs, Realm.Shared/linq/RealmResultsVisitor.cs, Tests/IntegrationTests.Shared/PeopleTestsBase.cs, Tests/IntegrationTests.Shared/Person.cs, Tests/IntegrationTests.Shared/SimpleLINQtests.cs, wrappers/src/query_cs.cpp
=> Null comparisons in LINQ

CHANGELOG.md
=> Update the changelog for #762

CHANGELOG.md, Doxygen/realmPublicAPI.doxy, RealmAssemblyInfo.cs, Tests/ThreeLayerRealmXFNuGet/PurePCLViewModel/PurePCLViewModel.csproj, Tests/ThreeLayerRealmXFNuGet/PurePCLViewModel/packages.config, Tests/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet.Droid/FodyWeavers.xml, Tests/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet.Droid/ThreeLayerRealmXFNuGet.Droid.csproj, Tests/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet.Droid/packages.config, Tests/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet.iOS/FodyWeavers.xml, Tests/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet.iOS/ThreeLayerRealmXFNuGet.iOS.csproj, Tests/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet/ThreeLayerRealmXFNuGet.iOS/packages.config, examples/Benchmarkr/Droid/Benchmarkr.Droid.csproj, examples/Benchmarkr/Droid/FodyWeavers.xml, examples/Benchmarkr/Droid/packages.config, examples/Benchmarkr/iOS/Benchmarkr.iOS.csproj, examples/Benchmarkr/iOS/FodyWeavers.xml, examples/Benchmarkr/iOS/packages.config, examples/QuickJournal/Droid/FodyWeavers.xml, examples/QuickJournal/Droid/QuickJournal.Droid.csproj, examples/QuickJournal/Droid/packages.config, examples/QuickJournal/QuickJournal/FodyWeavers.xml, examples/QuickJournal/QuickJournal/QuickJournal.csproj, examples/QuickJournal/QuickJournal/packages.config, examples/QuickJournal/iOS/FodyWeavers.xml, examples/QuickJournal/iOS/QuickJournal.iOS.csproj, examples/QuickJournal/iOS/packages.config, wrappers/Makefile
This cherrypicks the version bump/update commits in the release 0.77.2 branch.
Review please, @AndyDentFree and/or @fealebenpae.
=> Version bump from 0.77.2

CHANGELOG.md, Realm.Shared/Attributes.cs, Realm.Shared/Dynamic/MetaRealmObject.cs, Realm.Shared/Schema/ObjectSchema.cs, Realm.Shared/Schema/Property.cs, Realm.Shared/Schema/RealmSchema.cs, RealmWeaver/ModuleWeaver.cs, Tests/IntegrationTests.Shared/AsyncTests.cs, Tests/IntegrationTests.Shared/SimpleLINQtests.cs, Tests/IntegrationTests.Shared/TestObjects.cs, Tests/WeaverTests/AssemblyToProcess/FaultyClasses.cs, Tests/WeaverTests/AssemblyToProcess/TestObjects.cs, Tests/WeaverTests/RealmWeaver.Tests/WeaverTests.cs, component/samples/Tasky/TaskySharedCode/TodoItem.cs, internals/Realm-dotnet Code Change Diary - Andy Dent.txt
@fealebenpae if you have a minute, easy review
@kristiandupont please review if sits there
Is just a search and replace of terms.
=> General search and replace ObjectId with PrimaryKey

Doxygen/ExtraDeclsForDoxygen.cs, Doxygen/realmPublicAPI.doxy, Realm.PCL/RealmConfigurationPCL.cs, Realm.PCL/RealmListPCL.cs, Realm.PCL/RealmObjectPCL.cs, Realm.PCL/RealmPCL.cs, Realm.PCL/RealmResultsPCL.cs, Realm.PCL/Schema/ObjectSchemaPCL.cs, Realm.PCL/Schema/RealmSchemaPCL.cs, Realm.PCL/TransactionPCL.cs, Realm.Shared/Realm.cs, Realm.Shared/RealmConfiguration.cs, Realm.Shared/RealmList.cs, Realm.Shared/RealmObject.cs, Realm.Shared/Schema/ObjectSchema.cs, Realm.Shared/Schema/Property.cs, Realm.Shared/Schema/RealmSchema.cs, Realm.Shared/linq/RealmResults.cs
This reduces the noise in the other PR - should be JUST comment changes. Will use this to simplify other primary key PR
@fealebenpae or @kristiandupont to approve
=> #737 Isolated RealmSchema and couple of other minor doc changes out

CHANGELOG.md, Realm.Shared/Realm.cs, Realm.Shared/Transaction.cs, Tests/IntegrationTests.Shared/LifetimeTests.cs
=> Transaction should hold a strong reference to its Realm

Realm.Shared/extensions/RealmResultsCollectionChanged.cs
Adapter ctor is now public... also see #798
=> Changed RealmResultsCollectionChanged ctor

Doxygen/linq-support.md, Doxygen/mainpage.md
=> LINQ support status and documentation

Realm.Shared/Migration.cs
=> Decorate the managed migration callback with MonoPInvokeCallback

NuGet/NuGet.Library/FodyWeavers.xml.uninstall.xdt
=> Fix broken NuGet transformation for FodyWeavers.xml

CHANGELOG.md, Realm.Shared/PreserveAttribute.cs, Realm.Shared/RealmObject.cs, RealmWeaver/ModuleWeaver.cs, Tests/IntegrationTests.Shared/DateTimeTests.cs, Tests/IntegrationTests.Shared/DynamicRelationshipTests.cs, Tests/IntegrationTests.Shared/Person.cs, Tests/IntegrationTests.Shared/RelationshipTests.cs, Tests/IntegrationTests.Shared/TestObjects.cs, Tests/IntegrationTests.XamarinIOS/IntegrationTests.XamarinIOS.csproj, internals/Realm-dotnet Code Change Diary - Andy Dent.txt
@fealebenpae please review.
Tried adding the equivalent of `[Persist(allMembers=true)]` to type but that seems insufficient so ended up adding a simple `[Persist]` on all woven members.
=> Ad/weaver write persist attribute#822

CHANGELOG.md, Tests/IntegrationTests.Shared/TestRunner.cs, wrappers/Makefile, wrappers/src/marshalling.hpp
=> Update to core 2.1.1

Platform.PCL/Realm.PCL/RealmPCL.cs, Shared/Realm.Shared/Dynamic/MetaRealmObject.cs, Shared/Realm.Shared/Handles/ObjectHandle.cs, Shared/Realm.Shared/Handles/TableHandle.cs, Shared/Realm.Shared/Realm.cs, Shared/Realm.Shared/RealmObject.cs, Shared/Tests.Shared/AddOrUpdateTests.cs, Shared/Tests.Shared/PrimaryKeyTests.cs, Shared/Tests.Shared/TestObjects.cs, Weaver/RealmWeaver.Fody/ModuleWeaver.cs, Weaver/WeaverTests/AssemblyToProcess/TestObjects.cs, Weaver/WeaverTests/Realm.FakeForWeaverTests/RealmObject.cs, wrappers/src/object_cs.cpp, wrappers/src/table_cs.cpp
=> Add support for nullable integer primary keys

Shared/Realm.Shared/Handles/QueryHandle.cs, Shared/Realm.Shared/Linq/RealmResultsVisitor.cs, Shared/Tests.Shared/RealmResults/SimpleLINQtests.cs, wrappers/src/query_cs.cpp
=> Add support for comparing realm objects

CHANGELOG.md
This adds a changelog entry for #896
=> Update the changelog for #896

Shared/Realm.Shared/Handles/ObjectHandle.cs, Shared/Realm.Shared/Handles/ResultsHandle.cs, Shared/Realm.Shared/Linq/RealmResults.cs, Shared/Realm.Shared/Realm.cs, Shared/Realm.Shared/exceptions/RealmException.cs, Shared/Realm.Shared/exceptions/RealmExceptionCodes.cs, Shared/Tests.Shared/RemoveTests.cs, wrappers/src/error_handling.cpp, wrappers/src/error_handling.hpp, wrappers/src/object_cs.cpp, wrappers/src/realm_error_type.hpp, wrappers/src/results_cs.cpp
=> Guard and add tests for removing object from different realm

Tests/QuickJournalLocal/QuickJournal/QuickJournalLocal.csproj, Tests/QuickJournalLocal/QuickJournalLocal.sln
This is now a trivial PR just for this test project to ensure it compiles with the new folder structure.
Anyone can review @nirinchev , @kristiandupont  or @fealebenpae
=> QuickJournalLocal updated for new paths

CHANGELOG.md, Shared/Realm.Shared/Extensions/RealmResultsCollectionChanged.cs, Shared/Realm.Shared/Handles/CollectionHandleBase.cs, Shared/Realm.Shared/Handles/NotificationTokenHandle.cs, Shared/Realm.Shared/Handles/RealmHandle.cs, Shared/Realm.Shared/Handles/ResultsHandle.cs, Shared/Realm.Shared/Linq/RealmCollectionNativeHelper.cs, Shared/Realm.Shared/Linq/RealmResults.cs, Shared/Realm.Shared/Realm.Shared.projitems, Shared/Realm.Shared/Realm.cs, Shared/Realm.Shared/RealmCollectionBase.cs, Shared/Tests.Shared/AsyncTests.cs, Shared/Tests.Shared/NotificationTests.cs, Shared/Tests.Shared/PropertyChangedTests.cs, Shared/Tests.Shared/TestHelpers.cs
This paves the way for a unified base class for results and lists
=> Refactor results notifycollectionchanged logic

Shared/Tests.Shared/TestHelpers.cs
=> Increase loop delay to 100 ms

Platform.PCL/Realm.Sync.PCL/Exceptions/AuthenticationException.cs, Platform.PCL/Realm.Sync.PCL/Exceptions/HttpException.cs, Platform.PCL/Realm.Sync.PCL/Realm.Sync.PCL.csproj, Shared/Realm.Sync.Shared/Exceptions/AuthenticationException.cs, Shared/Realm.Sync.Shared/Exceptions/ErrorCode.cs, Shared/Realm.Sync.Shared/Exceptions/HttpException.cs, Shared/Realm.Sync.Shared/Realm.Sync.Shared.projitems, Shared/Realm.Sync.Shared/User.cs
=> Add authentication exception handling

Platform.PCL/Realm.Sync.PCL/Permissions/PermissionChangePCL.cs, Platform.PCL/Realm.Sync.PCL/Permissions/UserPermissionsExtensionsPCL.cs, Platform.PCL/Realm.Sync.PCL/Realm.Sync.PCL.csproj, Platform.XamarinAndroid/Realm.Sync.XamarinAndroid/FodyWeavers.xml, Platform.XamarinAndroid/Realm.Sync.XamarinAndroid/Realm.Sync.XamarinAndroid.csproj, Platform.XamarinAndroid/Realm.Sync.XamarinAndroid/packages.config, Platform.XamarinIOS/Realm.Sync.XamarinIOS/FodyWeavers.xml, Platform.XamarinIOS/Realm.Sync.XamarinIOS/Realm.Sync.XamarinIOS.csproj, Platform.XamarinIOS/Realm.Sync.XamarinIOS/packages.config, Shared/Realm.Shared/Attributes.cs, Shared/Realm.Shared/Schema/RealmSchema.cs, Shared/Realm.Sync.Shared/Permissions/IPermissionObject.cs, Shared/Realm.Sync.Shared/Permissions/PermissionChange.cs, Shared/Realm.Sync.Shared/Permissions/UserPermissionsExtensions.cs, Shared/Realm.Sync.Shared/Realm.Sync.Shared.projitems, Shared/Tests.Shared/ConfigurationTests.cs, Shared/Tests.Shared/ObjectIntegrationTests.cs, Shared/Tests.Shared/ObjectSchemaTests.cs, Shared/Tests.Shared/PerformanceTests.cs, Shared/Tests.Shared/RealmResults/SimpleLINQtests.cs, Shared/Tests.Sync.Shared/PermissionsTests.cs, Shared/Tests.Sync.Shared/Tests.Sync.Shared.projitems
=> Add PermissionChangeObject and expose a Management realm getter

Platform.PCL/Realm.Sync.PCL/Realm.Sync.PCL.csproj, Platform.PCL/Realm.Sync.PCL/RealmSyncExtensionsPCL.cs, Platform.PCL/Realm.Sync.PCL/SessionPCL.cs, Platform.PCL/Realm.Sync.PCL/UserPCL.cs, Shared/Realm.Shared/RealmObject.cs, Shared/Realm.Sync.Shared/Exceptions/ErrorCode.cs, Shared/Realm.Sync.Shared/Exceptions/SessionErrorException.cs, Shared/Realm.Sync.Shared/Exceptions/SessionErrorKind.cs, Shared/Realm.Sync.Shared/Handles/SessionHandle.cs, Shared/Realm.Sync.Shared/Handles/SharedRealmHandleExtensions.cs, Shared/Realm.Sync.Shared/Handles/SyncUserHandle.cs, Shared/Realm.Sync.Shared/Realm.Sync.Shared.projitems, Shared/Realm.Sync.Shared/RealmExtensions.cs, Shared/Realm.Sync.Shared/RealmSyncExtensions.cs, Shared/Realm.Sync.Shared/Session.cs, Shared/Realm.Sync.Shared/User.cs, Shared/Tests.Sync.Shared/SessionTests.cs, Shared/Tests.Sync.Shared/Tests.Sync.Shared.projitems, wrappers/src/sync_manager_cs.cpp, wrappers/src/sync_session_cs.cpp
=> Add Error event to Session class

Jenkinsfile
=> [CI] Move the android tests away from the Pi

Jenkinsfile
Reverts realm/realm-dotnet#972
=> Revert "[CI] Move the android tests away from the Pi"

Platform.PCL/Realm.Sync.PCL/UserPCL.cs, Platform.XamarinIOS/Realm.Sync.XamarinIOS/Realm.Sync.XamarinIOS.csproj, Shared/Realm.Shared/MarshalHelpers.cs, Shared/Realm.Sync.Shared/Handles/SharedRealmHandleExtensions.cs, Shared/Realm.Sync.Shared/Handles/SyncUserHandle.cs, Shared/Realm.Sync.Shared/User.cs, Shared/Tests.Sync.Shared/CredentialsTests.cs, wrappers/src/sync_manager_cs.cpp, wrappers/src/sync_user_cs.cpp
OS PR: https://github.com/realm/realm-object-store/pull/279
Resolves #970
Needs to update docs after that: https://github.com/realm/realm.io-middleman/pull/2321
Tests theoretically pass, but due to an OS bug, once they're run, it's game over, because it `reset_for_testing` doesn't delete the metadata realm: https://github.com/realm/realm-object-store/issues/207
=> Expose User.Current and User.AllLoggedIn

Shared/Realm.Shared/Linq/IRealmCollection.cs, Shared/Realm.Shared/RealmCollectionBase.cs, Shared/Realm.Shared/RealmList.cs, Shared/Tests.Shared/NotificationTests.cs
=> Raise PropertyChanged for RealmCollections

Shared/Tests.Shared/DynamicRelationshipTests.cs, Shared/Tests.Shared/RelationshipTests.cs, wrappers/src/list_cs.cpp
=> Don't throw when inserting at the end of the list

Shared/Realm.Shared/RealmObject.cs, Shared/Realm.Shared/native/NativeCommon.cs, Shared/Tests.Shared/PropertyChangedTests.cs, wrappers/src/shared_realm_cs.cpp
=> Guard against NRE's for collected objects

Shared/Realm.Shared/RealmCollectionBase.cs, Shared/Tests.Shared/NotificationTests.cs
=> Fix crash when unsubscribing from notifications in the callback

Weaver/RealmWeaver.Fody/ModuleWeaver.cs, Weaver/RealmWeaver.Fody/extensions/PropertyDefinitionExtensions.cs, Weaver/WeaverTests/AssemblyToProcess/CopyToRealmTestObjects.cs, Weaver/WeaverTests/RealmWeaver.Tests/WeaverTests.cs
=> IRealmObjectHelper.CopyToRealm should always set primary keys

Shared/Realm.Shared/Linq/IRealmCollection.cs, Shared/Realm.Shared/Linq/RealmResultsVisitor.cs, Shared/Realm.Shared/Realm.cs, Shared/Tests.Shared/APITests.cs, Shared/Tests.Shared/Tests.Shared.projitems
which allows for downcasting
Closes #992
=> Make IRealmCollection<T> contravariant

Shared/Tests.Shared/AccessTests.cs, Shared/Tests.Shared/AddOrUpdateTests.cs, Shared/Tests.Shared/GetPrimaryKeyTests.cs, Shared/Tests.Shared/StandAloneObjectTests.cs, Shared/Tests.Shared/TestObjects.cs, Weaver/RealmWeaver.Fody/ModuleWeaver.cs, Weaver/RealmWeaver.Fody/extensions/PropertyDefinitionExtensions.cs, Weaver/WeaverTests/AssemblyToProcess/CopyToRealmTestObjects.cs, Weaver/WeaverTests/RealmWeaver.Tests/WeaverTests.cs
=> Ensure required properties are being set

README.md
An incredibly pedantic PR, but one to make sure we continue to look up-to-date. :)
=> Renamed OS X to macOS in README

Platform.PCL/Realm.PCL/Extensions/CollectionNotificationsExtensionsPCL.cs, Shared/Realm.Shared/Extensions/CollectionNotificationsExtensions.cs, Shared/Realm.Shared/Handles/ListHandle.cs, Shared/Realm.Shared/Linq/IRealmCollection.cs, Shared/Realm.Shared/RealmCollectionBase.cs, Shared/Realm.Shared/RealmList.cs, Shared/Tests.Shared/CollectionTests.cs, Shared/Tests.Shared/NotificationTests.cs, Shared/Tests.Shared/RealmResults/DisallowedPredicateParameters.cs, Shared/Tests.Shared/RelationshipTests.cs, Shared/Tests.Shared/TestObjects.cs, Shared/Tests.Shared/Tests.Shared.projitems, wrappers/src/list_cs.cpp
=> Expose IList<T>.Move extension method

Jenkinsfile
=> Delete the jenkins workspace after build

CHANGELOG.md
=> Update changelog to include api renaming details

Shared/Realm.Shared/Dynamic/DynamicRealmObjectHelper.cs, Shared/Realm.Shared/Realm.cs, Shared/Realm.Shared/weaving/IRealmObjectHelper.cs, Shared/Realm.Sync.Shared/Handles/SharedRealmHandleExtensions.cs, Shared/Tests.Shared/AddOrUpdateTests.cs, Shared/Tests.Shared/TestObjects.cs, Shared/Tests.Sync.Shared/MergeByPKTests.cs, Shared/Tests.Sync.Shared/Tests.Sync.Shared.projitems, Weaver/RealmWeaver.Fody/ModuleWeaver.cs, Weaver/WeaverTests/RealmWeaver.Tests/WeaverTests.cs, wrappers/src/object_cs.cpp
=> Make sure set_unique is always called

Weaver/RealmWeaver.Fody/ModuleWeaver.cs, Weaver/RealmWeaver.Fody/TypeHelper.cs, Weaver/RealmWeaver.Fody/extensions/PropertyDefinitionExtensions.cs, Weaver/RealmWeaver.Fody/extensions/TypeReferenceExtensions.cs, Weaver/WeaverTests/AssemblyToProcess/FaultyClasses.cs, Weaver/WeaverTests/RealmWeaver.Tests/WeaverTests.cs
=> Verify that [Required] is applied on correct property types

Shared/Realm.Shared/RealmList.cs, Shared/Tests.Shared/CollectionTests.cs
Also remove some leftover IList properties
Closes #782 
Closes #283
=> Update RealmList to return the correct value of IsReadOnly

Platform.PCL/Realm.Sync.PCL/Permissions/PermissionChangePCL.cs, Platform.PCL/Realm.Sync.PCL/Permissions/PermissionOfferPCL.cs, Platform.PCL/Realm.Sync.PCL/Permissions/PermissionOfferResponsePCL.cs, Shared/Realm.Sync.Shared/Exceptions/ErrorCodeHelper.cs, Shared/Realm.Sync.Shared/Permissions/IPermissionObject.cs, Shared/Realm.Sync.Shared/Permissions/PermissionChange.cs, Shared/Realm.Sync.Shared/Permissions/PermissionOffer.cs, Shared/Realm.Sync.Shared/Permissions/PermissionOfferResponse.cs, Shared/Realm.Sync.Shared/Realm.Sync.Shared.projitems, Shared/Realm.Sync.Shared/User.cs, Shared/Tests.Sync.Shared/PermissionsTests.cs, Weaver/RealmWeaver.Fody/ModuleWeaver.cs, Weaver/WeaverTests/AssemblyToProcess/TestObjects.cs
=> Expose IPermissionObject.ErrorCode to replace StatusCode

Platform.PCL/Realm.Sync.PCL/SessionPCL.cs, Shared/Realm.Shared/Schema/RealmSchema.cs, Shared/Realm.Sync.Shared/Session.cs, Shared/Realm.Sync.Shared/SessionState.cs, wrappers/src/sync_session_cs.cpp
=> Remove dead APIs and code

Shared/Tests.Sync.Shared/PermissionsTests.cs
=> Add tests for permissions + syncing

Docs/docfx.json
This is the path where "Improve this doc" will autocreate new items. It should match the one in [docfx.json#L61](https://github.com/realm/realm-dotnet/blob/ni/docfx-contribution-path/Docs/docfx.json#L61).
=> Update the contribution path for "Improve this doc"

Platform.PCL/Realm.Sync.PCL/CredentialsPCL.cs, Shared/Realm.Sync.Shared/Credentials.cs
and the static class holding names Providers.
=> Simply removed Twitter as option from Credentials

Platform.PCL/Realm.Sync.PCL/Permissions/PermissionOfferPCL.cs, Shared/Realm.Sync.Shared/Permissions/PermissionOffer.cs
=> Expose public setter for PermissionOffer.ExpiresAt

Shared/Realm.Sync.Shared/Handles/SharedRealmHandleExtensions.cs, Shared/Tests.Sync.Shared/CredentialsTests.cs, wrappers/src/debug.cpp
=> Logout all active user prior to calling reset_for_testing

NuGet/Realm.Database/Realm.Database.nuspec, NuGet/Realm.Database/Realm.Database.targets
This reverts commit 57bb7f22811547a57c1e7a9041aa94267daeeb92.
=> Revert "Remove win32 bits from the nuget (#1096)"

Shared/Realm.Shared/Handles/SharedRealmHandle.cs, Shared/Realm.Shared/Realm.cs, Shared/Realm.Shared/RealmObject.cs, Shared/Realm.Shared/native/NativeCommon.cs, Shared/Tests.Shared/InstanceTests.cs, Shared/Tests.Shared/RemoveTests.cs, wrappers/src/shared_realm_cs.cpp, wrappers/src/shared_realm_cs.hpp
=> Reuse cached Realm instances

Platform.PCL/Realm.PCL/Realm.PCL.csproj, Shared/Realm.Shared/Extensions/StringExtensions.cs, Shared/Realm.Shared/Linq/RealmResultsVisitor.cs, Shared/Realm.Shared/Realm.Shared.projitems, Shared/Tests.Shared/FallbackApiTests.cs, Shared/Tests.Shared/RealmResults/SimpleLINQtests.cs, Shared/Tests.Shared/Tests.Shared.projitems
=> Add support for case-insensitive contains

Platform.PCL/Realm.PCL/RealmPCL.cs, Shared/Realm.Shared/Realm.cs, Weaver/WeaverTests/Realm.FakeForWeaverTests/Realm.cs
#963 did that for the generic version, this PR fixes the inconsistency.
=> Return the passed in object from Realm.Add

Platform.PCL/Realm.PCL/RealmPCL.cs, Platform.PCL/Realm.Sync.PCL/Permissions/PermissionOfferResponsePCL.cs, Platform.PCL/Realm.Sync.PCL/UserPCL.cs, Platform.Win32/Tests.Win32/Tests.Win32.csproj, Settings.StyleCop
needed to prevent errors when building PCL in VS2017RC
=> Minor doc corrections, making PCL match main interface comments

Tests/SmokeTestWin32Console/README.md, Tests/SmokeTestWin32Console/SmokeTestWin32Console.sln, Tests/SmokeTestWin32Console/SmokeTestWin32Console/App.config, Tests/SmokeTestWin32Console/SmokeTestWin32Console/FodyWeavers.xml, Tests/SmokeTestWin32Console/SmokeTestWin32Console/Program.cs, Tests/SmokeTestWin32Console/SmokeTestWin32Console/Properties/AssemblyInfo.cs, Tests/SmokeTestWin32Console/SmokeTestWin32Console/SmokeTestWin32Console.csproj, Tests/SmokeTestWin32Console/SmokeTestWin32Console/packages.config, wrappers/README.md
Created as copy of previous PR because couldn't work out why that was crashing pipeline despite being minimal change in unrelated areas.
=> Merged in old Win32 console work to see if can get building 

Platform.PCL/Realm.Sync.PCL/RealmSyncExtensionsPCL.cs, Shared/Realm.Sync.Shared/RealmSyncExtensions.cs
=> Add xml docs for exceptions thrown by GetSession

Platform.PCL/Realm.Sync.PCL/SessionPCL.cs, Shared/Realm.Sync.Shared/Handles/SessionHandle.cs, Shared/Realm.Sync.Shared/Handles/SharedRealmHandleExtensions.cs, Shared/Realm.Sync.Shared/RealmSyncExtensions.cs, Shared/Realm.Sync.Shared/Session.cs, Shared/Realm.Sync.Shared/User.cs, Shared/Tests.Sync.Shared/PermissionsTests.cs, Shared/Tests.Sync.Shared/SessionTests.cs, wrappers/src/sync_session_cs.cpp
=> Make Session.Error event static

Platform.PCL/Realm.PCL/Realm.PCL.csproj, Platform.PCL/Realm.PCL/RealmObjectPCL.cs, Shared/Realm.Shared/ISchemaObject.cs, Shared/Realm.Shared/ISchemaSource.cs, Shared/Realm.Shared/Linq/IRealmCollection.cs, Shared/Realm.Shared/Realm.Shared.projitems, Shared/Realm.Shared/RealmCollectionBase.cs, Shared/Realm.Shared/RealmObject.cs
=> Extract a new interface exposing ObjectSchema

Jenkinsfile, Shared/Tests.Shared/InstanceTests.cs, Shared/Tests.Sync.Shared/SessionTests.cs
Those have been occasionally failing. Try to make them more robust.
=> Fix some failing unit tests

Shared/Realm.Shared/ErrorMessages.cs, Shared/Realm.Shared/Realm.Shared.projitems, Shared/Realm.Shared/Realm.cs, Shared/Tests.Shared/AsyncTests.cs
=> Refresh the original Realm after WriteAsync

Platform.PCL/Realm.PCL/Properties/AssemblyInfo.cs, Platform.PCL/Realm.Sync.PCL/Permissions/UserPermissionsExtensionsPCL.cs, Platform.PCL/Realm.Sync.PCL/Realm.Sync.PCL.csproj, Shared/Realm.Shared/Linq/RealmResultsVisitor.cs, Shared/Realm.Sync.Shared/Permissions/IPermissionObject.cs, Shared/Realm.Sync.Shared/Permissions/Permission.cs, Shared/Realm.Sync.Shared/Permissions/UserPermissionsExtensions.cs, Shared/Realm.Sync.Shared/Realm.Sync.Shared.projitems, Shared/Tests.Shared/RealmResults/DisallowedPredicateParameters.cs, Shared/Tests.Sync.Shared/PermissionsTests.cs
=> Expose the permission realm

NuGet/Realm.Database/Realm.Database.targets, Platform.XamarinIOS/Tests.XamarinIOS/Tests.XamarinIOS.csproj
=> Add Security to Frameworks

NuGet/Realm.Database/Realm.Database.targets, Platform.XamarinIOS/Tests.XamarinIOS/Tests.XamarinIOS.csproj
Fixes #1227 without requiring iOS 8
=> Fix security linking take 2

wrappers/src/shared_realm_cs.cpp
Resolves private bug report: https://secure.helpscout.net/conversation/314089274/8665
=> Don't delete objects while looping for changes

.gitattributes, .github/PULL_REQUEST_TEMPLATE.md
Per our discussion on [Slack](https://realmio.slack.com/archives/dotnet-team/p1487594931003153) - update the strategy for merging changelog.md
=> Specify union merge for Changelog.md

Docs/Readme.md
Minor update for Docs/Readme.md
=> Update docs readme

Weaver/Realm.BuildTasks/WeaveRealmAssembly.cs
MSBuild doesn't automatically load .dll's from the task folder which results in Cecil being unresolved when installing the nuget. This PR hooks up to `AppDomain.CurrentDomain.AssemblyResolve` to try to load assemblies from the task folder.
=> Add assembly resolve and improve logging for BuildTasks

wrappers/Makefile
Updates to:
- Sync 1.2.1
- Core 2.3.2
- Latest OS that uses Sync 1.2.1
=> Update to latest sync and object store

CHANGELOG.md, NuGet/Realm.Database/Realm.Database.targets, Platform.XamarinIOS/Tests.XamarinIOS/Tests.XamarinIOS.csproj, Settings.StyleCop, Shared/Realm.Sync.Shared/Permissions/PermissionOfferResponse.cs, Shared/Realm.Sync.Shared/User.cs, Weaver/Realm.BuildTasks/WeaveRealmAssembly.cs
=> Fix VS build issues

CHANGELOG.md, Realm/Realm/Realm.cs, Tests/Tests.Shared/RemoveTests.cs
=> Fix the dynamic version of RemoveAll

Jenkinsfile
Due to #1290 CI fails when building in Debug.
=> Temporarily build in release on CI

CHANGELOG.md, Tests/Tests.Shared/AccessTests.cs, Weaver/RealmWeaver.Fody/ModuleWeaver.cs, Weaver/WeaverTests/AssemblyToProcess/CopyToRealmTestObjects.cs, Weaver/WeaverTests/RealmWeaver.Tests/WeaverTests.cs
=> Fix default DateTimeOffset value

CHANGELOG.md, Realm/Realm.Sync/ProgressNotifications/SyncProgressObservable.cs, Tests/Tests.Sync.Shared/SessionTests.cs
=> Call OnCompleted in the SyncProgressObservable

CHANGELOG.md, wrappers/Makefile, wrappers/jni/Android.mk, wrappers/src/table_cs.cpp, wrappers/wrappers.xcodeproj/project.pbxproj
Cherry pick from #1284 to get the new progress notification fixes
=> Update to latest dependencies

Tests/Tests.Shared/MigrationTests.cs
=> Enable the automatic deletion test on windows

CHANGELOG.md
The update of sync in #1300 brings it in: https://github.com/realm/realm-sync/blob/master/CHANGELOG.md#breaking-changes-2
=> Add info about protocol breaking change

Realm/Realm/InteropConfig.cs
=> Add UWP method for obtaining the default folder

CHANGELOG.md, Realm/Realm/Extensions/StringExtensions.cs, Realm/Realm/Handles/QueryHandle.cs, Realm/Realm/Linq/RealmResultsVisitor.cs, Realm/Realm/project.json, Tests/Tests.Shared/RealmResults/SimpleLINQtests.cs, Tests/Tests.Shared/StringExtensionsTests.cs, Tests/Tests.Shared/Tests.Shared.projitems, wrappers/src/query_cs.cpp
=> Add support for like queries on strings

Realm/Realm.Sync/Helpers/AuthenticationHelper.cs
Due to https://bugzilla.xamarin.com/show_bug.cgi?id=20082 dynamic json deserialization fails on iOS. This annoying change fixes it.
=> Fix json deserialization on iOS

Jenkinsfile, NuGet/Realm.Database/Realm.Database.nuspec, NuGet/Realm/Realm.nuspec
Fixes a packaging issue that prevented adding the nuget to a PCL project
=> Update dependencies for PCL

CHANGELOG.md, Tests/Tests.Sync.Shared/SyncConfigurationTests.cs, wrappers/src/sync_manager_cs.cpp
=> Fix encryption + sync bug

Realm/Realm/Linq/RealmResultsVisitor.cs, Realm/Realm/RealmCollectionBase.cs, Tests/Tests.Shared/RealmResults/SimpleLINQtests.cs, wrappers/src/results_cs.cpp
=> Fix IndexOutOfRange being thrown in FirstOrDefault

Jenkinsfile, NuGet/Realm.Database/Realm.Database.nuspec, Weaver/RealmWeaver.Fody/ImportedReferences.cs
=> Include UWP wrappers in the Realm.Database nupkg

CHANGELOG.md, Realm/Realm/Linq/IRealmCollection.cs, Tests/Tests.Shared/CollectionTests.cs
=> Expose RealmCollection.IsValid

DataBinding/DataBindingAssemblyInfo.cs, DataBinding/Realm.DataBinding.PCL/Realm.DataBinding.PCL.csproj, DataBinding/Realm.DataBinding.PCL/TypeInfoHelper.cs, DataBinding/Realm.DataBinding.PCL/packages.config, DataBinding/Realm.DataBinding.PCL/project.json, Jenkinsfile, NuGet/Realm.DataBinding/Realm.DataBinding.nuspec, NuGet/Realm.Database/Realm.Database.nuspec, Realm/Realm/InteropConfig.cs, Weaver/RealmWeaver.Fody/ImportedReferences.cs
Should fix .NET Core issues when adding the nuget
**Note**: this will not fix runtime crashes. Those will be addressed in follow-up PR.
=> Convert databinding project to netstandard

CHANGELOG.md, Platform.PCL/Realm.Sync.PCL/UserPCL.cs, Realm/Realm.Sync/Helpers/AuthenticationHelper.cs, Realm/Realm.Sync/User.cs, Tests/Tests.Sync.Shared/CredentialsTests.cs
Fixes https://github.com/realm/product/issues/294
=> Expose change password API

CHANGELOG.md, Platform.PCL/Realm.Sync.PCL/SyncConfigurationPCL.cs, Realm/Realm.Sync/Native/SyncConfiguration.cs, Realm/Realm.Sync/SyncConfiguration.cs, wrappers/src/sync_manager_cs.cpp
=> Expose SyncConfiguration.EnableSSLValidation

CHANGELOG.md, Platform.PCL/Realm.PCL/RealmConfigurationPCL.cs, Realm/Realm/Native/Configuration.cs, Realm/Realm/RealmConfiguration.cs, Tests/Tests.Shared/InstanceTests.cs, wrappers/src/shared_realm_cs.cpp, wrappers/src/shared_realm_cs.hpp
Fixes #1388 
Depends on https://github.com/realm/realm-object-store/pull/446
=> Expose ShouldCompactOnLaunch

CHANGELOG.md, Platform.PCL/Realm.PCL/RealmObjectPCL.cs, Realm/Realm/Realm.cs, Realm/Realm/RealmCollectionBase.cs, Realm/Realm/RealmObject.cs, Tests/Tests.Shared/PropertyChangedTests.cs, Tests/Tests.Shared/RealmObjectTests.cs, Tests/Tests.Shared/Tests.Shared.projitems
=> Expose RealmObject.OnManaged virtual method

CHANGELOG.md, Platform.PCL/Realm.PCL/RealmPCL.cs, Platform.PCL/Realm.Sync.PCL/SessionPCL.cs, Realm/Realm.Sync/Handles/SessionHandle.cs, Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs, Realm/Realm.Sync/Realm.Sync.csproj, Realm/Realm.Sync/Session.cs, Realm/Realm.Sync/SyncConfiguration.cs, Realm/Realm/Realm.cs, Realm/Realm/RealmConfiguration.cs, Realm/Realm/RealmConfigurationBase.cs, Tests/Tests.Shared/TestHelpers.cs, Tests/Tests.Sync.Shared/PermissionsTests.cs, Tests/Tests.Sync.Shared/SessionTests.cs, Tests/Tests.Sync.Shared/SyncTestHelpers.cs, Tests/Tests.Sync.Shared/SynchronizedInstanceTests.cs, Weaver/RealmWeaver.Fody/ModuleWeaver.cs, wrappers/src/sync_manager_cs.cpp, wrappers/src/sync_session_cs.cpp
This exposes the asynchronous `WaitForUpload/WaitForDownload` pair of methods on the `Session` class and implements the asynchronous `Realm.GetInstanceAsync` on top of `Session.WaitForDownloadAsync`.
* https://github.com/realm/product/issues/63 - Download Realm API
* https://github.com/realm/product/issues/195 - Read-only synced realms
=> Download Realm API

Realm/Realm.Sync/Permissions/UserPermissionsExtensions.cs
Fixes a deadlock exposed with our integration tests
=> Retain permission objects to ensure that the handler has been invoked.

CHANGELOG.md, Platform.PCL/Realm.Sync.PCL/UserPCL.cs, Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs, Realm/Realm.Sync/Helpers/AuthenticationHelper.cs, Realm/Realm.Sync/Permissions/PermissionChange.cs, Realm/Realm.Sync/Permissions/PermissionOffer.cs, Realm/Realm.Sync/User.cs, Tests/Tests.Sync.Shared/Constants.cs, Tests/Tests.Sync.Shared/CredentialsTests.cs
References https://github.com/realm/product/issues/294
=> Expose admin password change API

Realm/Realm/InteropConfig.cs, Realm/Realm/Native/NativeCommon.cs
Some of our clever hacks to conditionally call platform-specific APIs fail, so make sure to silence them.
Fixes #1410
=> Guard platform-specific reflection hacks better

Realm/Realm/Realm.cs, Realm/Realm/RealmConfiguration.cs, Realm/Realm/RealmConfigurationBase.cs, Realm/Realm/project.json, Tests/Tests.Shared/CollectionTests.cs, Tests/Tests.Shared/InstanceTests.cs
Fixes #1356 
Also enables two ignored tests.
=> Remove unnecessary delete lock

CHANGELOG.md, Realm/Realm/Realm.cs
Work around mono's inliner bug to allow building in debug :sigh:
=> Fix build in debug

Realm/Realm/Realm.cs
I stupidly made a change on Windows which broke mono :/ This should hopefully fix it for good.
=> Fix debug build again.

Manual Tests/Readme.md
=> Update tests readme

Jenkinsfile
=> Replace xbuild with msbuild

CHANGELOG.md, Realm/Realm/Linq/RealmResults.cs, Realm/Realm/RealmCollectionBase.cs, Realm/Realm/RealmList.cs
=> Implement IList for realm collections

NuGet/Realm.Database/Realm.Database.targets, Weaver/RealmWeaver.Fody/ImportedReferences.cs
This is very hacky, but can be used for a quick smoke test.
=> Allow building for Xamarin.Mac

CHANGELOG.md, Realm/Realm/Linq/RealmResultsVisitor.cs, Tests/Tests.Shared/DateTimeTests.cs, Tests/Tests.Shared/DynamicRelationshipTests.cs, Tests/Tests.Shared/ObjectIntegrationTests.cs, Tests/Tests.Shared/RealmResults/SimpleLINQtests.cs
=> Improve char handling in queries

CHANGELOG.md, Realm/Realm/Linq/RealmResultsVisitor.cs, Tests/Tests.Shared/RealmResults/SimpleLINQtests.cs
=> Fix byte and short query comparisons

Jenkinsfile, Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs, Realm/Realm.Sync/Helpers/AuthenticationHelper.cs, Realm/Realm.Sync/Session.cs, Realm/Realm.Sync/SyncConfiguration.cs, Realm/Realm.Sync/User.cs, Tests/Tests.Shared/NotificationTests.cs, Tests/Tests.Sync.Shared/CredentialsTests.cs, Tests/Tests.Sync.Shared/MergeByPKTests.cs, Tests/Tests.Sync.Shared/PermissionsTests.cs, Tests/Tests.Sync.Shared/SSLConfigurationTests.cs, Tests/Tests.Sync.Shared/SessionTests.cs, Tests/Tests.Sync.Shared/SyncConfigurationTests.cs, Tests/Tests.Sync.Shared/SyncTestBase.cs, Tests/Tests.Sync.Shared/SyncTestHelpers.cs, Tests/Tests.Sync.Shared/SynchronizedInstanceTests.cs, Tests/Tests.Sync.Shared/Tests.Sync.Shared.projitems, wrappers/CMakeLists.txt, wrappers/src/CMakeLists.txt
=> Run ResetForTesting between tests

CHANGELOG.md, Realm/Realm/Linq/RealmResultsProvider.cs, Tests/Tests.Shared/RealmResults/QueryableAPITests.cs, Tests/Tests.Shared/Tests.Shared.projitems
=> Fix the non-generic IQueryable provider

DataBinding/DataBindingAssemblyInfo.cs, DataBinding/Realm.DataBinding.Android/Properties/AssemblyInfo.cs, DataBinding/Realm.DataBinding.Mac/Properties/AssemblyInfo.cs, DataBinding/Realm.DataBinding.Mac/Realm.DataBinding.Mac.csproj, Jenkinsfile, NuGet/Realm.DataBinding/Realm.DataBinding.nuspec, NuGet/Realm.Database/Realm.Database.nuspec, Realm.sln, Tests/Tests.Shared/ReflectableTypeTests.cs, Tests/Tests.XamarinMac/Tests.XamarinMac.csproj, Weaver/RealmWeaver.Fody/ImportedReferences.cs
This enables XF two-way databinding.
=> Add databinding support for Xamarin.Mac

CHANGELOG.md, Realm.sln, Realm/Realm.Sync/SyncConfiguration.cs, Realm/Realm.Sync/User.cs, Realm/Realm/Helpers/Argument.cs, Tests/Tests.Sync.Shared/CredentialsTests.cs, Tests/Tests.Sync.Shared/SyncConfigurationTests.cs
=> Add better url validation

CHANGELOG.md, Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs, Realm/Realm/Exceptions/RealmException.cs, Tests/Tests.Sync.Shared/SynchronizedInstanceTests.cs, wrappers/src/sync_session_cs.cpp
=> Include error message in GetInstanceAsync error

CHANGELOG.md
=> Add counter changelog entry

Tests/Tests.Sync.Shared/SynchronizedInstanceTests.cs
=> Add a test to validate GetInstanceAsync behavior

README.md
=> Update link to community newsletter

Realm/Realm/Handles/QueryHandle.cs, Realm/Realm/Helpers/Operator.cs, Realm/Realm/Linq/RealmResultsVisitor.cs, Tests/Tests.Shared/RealmResults/ConvertTests.cs, Tests/Tests.Shared/TestHelpers.cs, Tests/Tests.Shared/Tests.Shared.projitems
=> Fix some conversion cases

CHANGELOG.md, Realm/Realm.Sync/Permissions/PermissionCondition.cs
=> Expose PermissionCondition.Default

CHANGELOG.md, Platform.PCL/Realm.Sync.PCL/SyncConfigurationPCL.cs, Realm/Realm.Sync/Exceptions/ClientResetException.cs, Realm/Realm.Sync/Exceptions/PermissionException.cs, Realm/Realm.Sync/Exceptions/SessionException.cs, Realm/Realm.Sync/SyncConfiguration.cs, Realm/Realm/Exceptions/RealmClassLacksPrimaryKeyException.cs, Realm/Realm/Exceptions/RealmDuplicatePrimaryKeyValueException.cs, Realm/Realm/Exceptions/RealmFeatureUnavailableException.cs, Realm/Realm/Exceptions/RealmMigrationNeededException.cs
=> Add HelpLink to some exception types

CHANGELOG.md, wrappers/src/shared_realm_cs.cpp, wrappers/src/sync_manager_cs.cpp
=> Call Realm::refresh before returning a Realm instance

CHANGELOG.md, Platform.PCL/Realm.PCL/RealmObjectPCL.cs, Realm/Realm/Dynamic/DynamicRealmObject.cs, Realm/Realm/Dynamic/MetaRealmObject.cs, Realm/Realm/Handles/ObjectHandle.cs, Realm/Realm/RealmObject.cs, Tests/Tests.Shared/DynamicRelationshipTests.cs, wrappers/src/object_cs.cpp
=> Expose API for getting backlinks dynamically

CHANGELOG.md, NuGet/Realm.Database/Realm.Database.targets, Weaver/Realm.BuildTasks/WeaveRealmAssembly.cs
=> Relax iOS assembly weaver restrictions

CHANGELOG.md, Jenkinsfile, README.md, Tests/Tests.NetCore/Dockerfile
=> Try to revive myget builds

Jenkinsfile
=> Fix jenkinsfile for master

Jenkinsfile
this allows us to target more nodes
=> Use granular tags when selecting Jenkins nodes

NuGet/Realm.Database/Realm.Database.nuspec
=> Add dependency to System.Reflection.TypeExtensions

CHANGELOG.md
Fixes #1519
Just an update to latest OS.
=> Update OS and fix changelog

CHANGELOG.md, Platform.PCL/Realm.PCL/RealmObjectPCL.cs, Realm/Realm/Handles/ObjectHandle.cs, Realm/Realm/RealmObject.cs, Tests/Tests.Shared/RelationshipTests.cs, Tests/Tests.Shared/TestObjects.cs, wrappers/src/object_cs.cpp
=> Expose a method to get the backlink count for an object

CHANGELOG.md, Platform.PCL/Realm.Sync.PCL/Extensions/RealmSyncExtensionsPCL.cs, Platform.PCL/Realm.Sync.PCL/SyncConfigurationPCL.cs, Realm/Realm.Sync/Extensions/RealmSyncExtensions.cs, Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs, Realm/Realm.Sync/Native/SyncConfiguration.cs, Realm/Realm.Sync/SyncConfiguration.cs, Realm/Realm/Extensions/TaskExtensions.cs, Tests/Tests.Shared/TestObjects.cs, Tests/Tests.Sync.Shared/PartialSyncTests.cs, Tests/Tests.Sync.Shared/Tests.Sync.Shared.projitems, wrappers/src/sync_manager_cs.cpp
=> Expose partial sync API

Jenkinsfile
=> Run .NET Core tests on CPH macs

CHANGELOG.md, Realm/Realm/Handles/CollectionHandleBase.cs, Realm/Realm/Handles/ListHandle.cs, Realm/Realm/Handles/ResultsHandle.cs, Realm/Realm/Linq/IRealmCollection.cs, Realm/Realm/Linq/RealmResultsProvider.cs, Realm/Realm/RealmCollectionBase.cs, Tests/Tests.Shared/CollectionTests.cs, wrappers/src/list_cs.cpp, wrappers/src/results_cs.cpp
=> Add snapshotting of enumerable collections

Jenkinsfile
=> Build on all available mac nodes

CHANGELOG.md, Tests/Tests.Shared/RealmResults/SimpleLINQtests.cs, wrappers/src/query_cs.cpp
=> Fix querying for null related objects

Realm/Realm.Sync/SyncConfiguration.cs, Realm/Realm/Native/Configuration.cs, Realm/Realm/Realm.cs, Realm/Realm/RealmConfiguration.cs, Realm/Realm/RealmConfigurationBase.cs, Tests/Tests.Shared/InstanceTests.cs, wrappers/src/shared_realm_cs.cpp, wrappers/src/shared_realm_cs.hpp
=> Expose mechanisms to control cache by the configuration

Jenkinsfile
There's a known issue regarding the serialization of Map iterators so this PR works around that.
=> Fix the usage of Maps in the Jenkinsfile

Realm/Realm.Sync/Handles/SessionHandle.cs, Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs, Realm/Realm.Sync/Handles/SyncUserHandle.cs, Realm/Realm/Handles/SharedRealmHandle.cs, Realm/Realm/Native/NativeCommon.cs, Realm/Realm/Realm.cs, wrappers/src/shared_realm_cs.cpp
Extract general native init in NativeCommon and realm-specific init in the SharedRealmHandle static constructor
=> Refactor Realm’s static constructor

CHANGELOG.md, Realm/Realm/Dynamic/MetaRealmObject.cs, Tests/Tests.Shared/DynamicRelationshipTests.cs
Fixes #1626
* ~[ ] Update PCL (if applicable)~
=> Fix crash when getting primitive list on a dynamic object

CHANGELOG.md, Platform.PCL/Realm.PCL/InMemoryConfigurationPCL.cs, Platform.PCL/Realm.PCL/Realm.PCL.csproj, Realm/Realm/InMemoryConfiguration.cs, Realm/Realm/Realm.csproj, Tests/Tests.Shared/InMemoryTests.cs, Tests/Tests.Shared/Tests.Shared.projitems
=> Add support for in-memory realms

Realm/Realm.Sync/Exceptions/ClientResetException.cs, Tests/Tests.Sync.Shared/SessionTests.cs
=> Fix a failing Windows test

CHANGELOG.md, Realm/Realm/Handles/ListHandle.cs, Realm/Realm/RealmList.cs, Tests/Tests.Shared/CollectionTests.cs, Tests/Tests.Shared/ListOfPrimitivesTests.cs, wrappers/src/list_cs.cpp
=> Enable setting of list items by index

CHANGELOG.md, Platform.PCL/Realm.Sync.PCL/CredentialsPCL.cs, Realm/Realm.Sync/Credentials.cs, Settings.StyleCop
=> Add JWT provider

Jenkinsfile, Tests/Tests.NetCore/Program.cs, Tests/Tests.NetCore/Tests.NetCore.csproj, Tests/Tests.Sync.Shared/Constants.cs, Tests/Tests.Sync.Shared/CredentialsTests.cs, Tests/Tests.Sync.Shared/MergeByPKTests.cs, Tests/Tests.Sync.Shared/PartialSyncTests.cs, Tests/Tests.Sync.Shared/PermissionsTests.cs, Tests/Tests.Sync.Shared/SSLConfigurationTests.cs, Tests/Tests.Sync.Shared/SessionTests.cs, Tests/Tests.Sync.Shared/SyncTestHelpers.cs, Tests/Tests.Sync.Shared/SynchronizedInstanceTests.cs
=> Integration tests

README.md, examples/Benchmarkr/README.md, wrappers/README.md
=> Fix some typos in the readmes

CHANGELOG.md, Realm/Realm/RealmCollectionBase.cs, Tests/Tests.Shared/NotificationTests.cs
=> Ensure initial notification is always delivered

CHANGELOG.md, Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs, Realm/Realm.Sync/SyncConfiguration.cs, Tests/Tests.Sync.Shared/SyncConfigurationTests.cs, Tests/Tests.Sync.Shared/SyncTestBase.cs, wrappers/src/sync_manager_cs.cpp
=> Remove feature tokens

Tests/Tests.Shared/ListOfPrimitivesTests.cs
=> Don't deadlock tests on Windows

CHANGELOG.md, Realm/Realm.Sync/Extensions/RealmSyncExtensions.cs, Realm/Realm.Sync/Handles/SharedRealmHandleExtensions.cs, Realm/Realm/Attributes/MapToAttribute.cs, Realm/Realm/Extensions/ReflectionExtensions.cs, Realm/Realm/Handles/SharedRealmHandle.cs, Realm/Realm/Linq/RealmResultsVisitor.cs, Realm/Realm/Realm.cs, Realm/Realm/Schema/ObjectSchema.cs, Tests/Tests.Shared/AddOrUpdateTests.cs, Tests/Tests.Shared/GetPrimaryKeyTests.cs, Tests/Tests.Shared/RealmResults/SimpleLINQtests.cs, Tests/Tests.Shared/TestObjects.cs
Preparation for object level permissions
TODO:
=> Allow MapTo to be applied on classes

CHANGELOG.md, Platform.PCL/Realm.Sync.PCL/Realm.Sync.PCL.csproj, Platform.PCL/Realm.Sync.PCL/UserPCL.cs, Realm/Realm.Sync/Permissions/PathPermission.cs, Realm/Realm.Sync/Realm.Sync.csproj, Realm/Realm.Sync/User.cs, Tests/Tests.Sync.Shared/PermissionsTests.cs
Preparation for object level permissions
=> Rename Permission to PathPermission

Platform.PCL/Realm.Sync.PCL/ObjectLevelPermissions/PermissionExtensionsPCL.cs, Realm/Realm.Sync/ObjectLevelPermissions/ClassPrivileges.cs, Realm/Realm.Sync/ObjectLevelPermissions/ObjectPrivileges.cs, Realm/Realm.Sync/ObjectLevelPermissions/Permission.cs, Realm/Realm.Sync/ObjectLevelPermissions/PermissionExtensions.cs, Realm/Realm.Sync/ObjectLevelPermissions/RealmPrivileges.cs, Realm/Realm.Sync/Subscription.cs, Tests/Tests.Sync.Shared/ObjectLevelPermissionsTests.cs, Tests/Tests.Sync.Shared/SyncTestBase.cs, Tests/Tests.Sync.Shared/SyncTestHelpers.cs, Tests/Tests.Sync.Shared/Tests.Sync.Shared.projitems
=> Add object permission tests

Realm/Realm.Sync/Subscription.cs, Tests/Tests.Sync.Shared/PartialSyncTests.cs
=> Add missing GCHandle guard for callback method

CHANGELOG.md, Platform.PCL/Realm.PCL/RealmConfigurationPCL.cs, Platform.PCL/Realm.Sync.PCL/SyncConfigurationPCL.cs, Realm/Realm.Sync/SyncConfiguration.cs, Realm/Realm.Sync/User.cs, Realm/Realm/Realm.cs, Realm/Realm/RealmConfiguration.cs, Tests/Tests.Shared/ConfigurationTests.cs, Tests/Tests.Shared/InstanceTests.cs, Tests/Tests.Shared/MigrationTests.cs, Tests/Tests.Shared/PrimaryKeyTests.cs, Tests/Tests.Sync.Shared/SyncConfigurationTests.cs, Tests/Tests.Sync.Shared/SyncTestHelpers.cs
Fixes https://github.com/realm/realm-dotnet/issues/1699
=> Expose parameterless sync configuration constructor

CHANGELOG.md
Fixes https://github.com/realm/realm-dotnet/issues/1706
=> Fix android deadlock when a Realm is opened

Realm/Realm.Sync/ObjectLevelPermissions/ResultSets.cs, Realm/Realm.Sync/Realm.Sync.csproj, Realm/Realm.Sync/Subscription.cs, Tests/Tests.Sync.Shared/ObjectLevelPermissionsTests.cs
=> Fix Subscription.UnsubscribeAsync failing sporadically.

CHANGELOG.md, Platform.PCL/Realm.Sync.PCL/UserPCL.cs, Realm/Realm.Sync/Helpers/AuthenticationHelper.cs, Realm/Realm.Sync/User.cs
=> Add password reset wrappers

CHANGELOG.md, Realm/Realm/Handles/NotifiableObjectHandleBase.cs, Realm/Realm/Linq/IRealmCollection.cs, Realm/Realm/RealmCollectionBase.cs, Tests/Tests.Shared/NotificationTests.cs, wrappers/src/notifications_cs.hpp
Fixes https://github.com/realm/realm-dotnet/issues/1741
=> Expose NewModifiedIndices

Platform.PCL/Realm.Sync.PCL/UserPCL.cs, Realm/Realm.Sync/User.cs
=> Allow configuring the base path for Realm files

CHANGELOG.md, Realm/Realm/RealmObject.cs, Tests/Tests.Shared/PropertyChangedTests.cs
Fixes https://github.com/realm/realm-dotnet/issues/1474
=> Raise property changed with IsValid upon removal

CHANGELOG.md, Realm/Realm.Sync/SubscriptionState.cs
Fixes https://github.com/realm/realm-dotnet-private/issues/128
=> Fix subscription state size

CHANGELOG.md, Realm/Realm.Sync/Subscription.cs, Realm/Realm/Helpers/AsyncHelper.cs, Realm/Realm/Realm.cs, Realm/Realm/Realm.csproj, Realm/Realm/RealmConfiguration.cs, Tests/Tests.NetCore/Tests.NetCore.csproj, Tests/Tests.Sync.Shared/QueryBasedSyncTests.cs
Fixes https://github.com/realm/realm-dotnet-private/issues/130
=> Throw an error when trying to call async subscription methods on background threads

CHANGELOG.md, Tests/Tests.Sync.Shared/QueryBasedSyncTests.cs, wrappers/src/sync_manager_cs.cpp
Fixes https://github.com/realm/realm-dotnet/issues/1814
=> Ensure GetInstanceAsync works with QBS config

CHANGELOG.md, Realm/Realm/Handles/SubscriptionHandle.cs, Realm/Realm/Helpers/LinqHelper.cs, Realm/Realm/Native/StringValue.cs, Realm/Realm/Sync/Subscription.cs, Tests/Realm.Tests/Sync/QueryBasedSyncTests.cs, wrappers/src/marshalling.hpp, wrappers/src/results_cs.cpp, wrappers/src/schema_cs.hpp, wrappers/src/subscription_cs.cpp
Fixes https://github.com/realm/realm-dotnet/issues/1834
=> Add support for subscription inclusions

Realm/Realm.Fody/ImportedReferences.cs, Realm/Realm.Fody/ModuleWeaver.Schema.cs, Realm/Realm.Fody/ModuleWeaver.cs, Realm/Realm/Attributes/Attributes.cs, Tests/Weaver/Realm.FakeForWeaverTests/Realm.FakeForWeaverTests.csproj, Tests/Weaver/Realm.Fody.Tests/WeaveEmptyTests.cs, Tests/Weaver/Realm.Fody.Tests/WeaverTestBase.cs, Tests/Weaver/Realm.Fody.Tests/WeaverTests.cs
=> Don't execute weaver multiple times

CHANGELOG.md, Realm/Realm/Configurations/RealmConfiguration.cs, Realm/Realm/Handles/SharedRealmHandle.cs, Realm/Realm/Handles/SharedRealmHandleExtensions.cs, Realm/Realm/Migration.cs, Realm/Realm/Native/NativeCallbackAttribute.cs, Realm/Realm/Native/NativeCommon.cs, Realm/Realm/Native/SynchronizationContextEventLoopSignal.cs, Realm/Realm/NotificationsHelper.cs, Realm/Realm/Sync/Subscription.cs, wrappers/build-ios.sh, wrappers/src/CMakeLists.txt
Fixes https://github.com/realm/realm-dotnet/issues/1871
Fixes https://github.com/realm/realm-dotnet/issues/1870
=> Fix iOS device builds

CHANGELOG.md, Realm/Realm/Helpers/AuthenticationHelper.cs, Realm/Realm/Sync/Credentials.cs
Fixes https://github.com/realm/realm-dotnet/issues/1879
=> Deprecate Credentials.Nickname

Jenkinsfile, wrappers/CMakeLists.txt, wrappers/CMakeSettings.json
Generate PDBs for Release builds and archive them in Jenkins in case we need to retrieve them later. Also update for Visual Studio 2019 local development.
=> Always include debug information in release builds.

CHANGELOG.md, Realm/Realm/Handles/ResultsHandle.cs, Realm/Realm/Linq/IRealmCollection.cs, Realm/Realm/Linq/RealmResults.cs, Realm/Realm/RealmCollectionBase.cs, Realm/Realm/RealmList.cs, Tests/Realm.Tests/Database/CollectionTests.cs, Tests/Realm.Tests/Database/RealmResults/SimpleLINQtests.cs, Tests/Realm.Tests/Sync/CredentialsTests.cs, wrappers/src/list_cs.cpp, wrappers/src/results_cs.cpp
Fixes https://github.com/realm/realm-dotnet/issues/1892
=> Fix IndexOf for Results

CHANGELOG.md, Realm/Realm.Fody/ImportedReferences.cs, Realm/Realm.Fody/InSolutionWeaver.props, Realm/Realm.Fody/Realm.Fody.csproj, Realm/Realm.Fody/Weaver.props, Realm/Realm/Realm.csproj, Tests/Realm.Tests/Realm.Tests.csproj, Tests/Weaver/AssemblyToProcess/AssemblyToProcess.csproj, Tests/Weaver/Realm.Fody.Tests/Realm.Fody.Tests.csproj, Tests/Weaver/Realm.Fody.Tests/WeaverTests.cs, Tests/Weaver/RealmFreeAssemblyToProcess/RealmFreeAssemblyToProcess.csproj, global.json
Fixes https://github.com/realm/realm-dotnet/issues/1899
=> Update to latest Fody

CHANGELOG.md, Realm/Realm.Fody/Extensions/PropertyDefinitionExtensions.cs, Realm/Realm.Fody/ModuleWeaver.cs, Tests/Realm.Tests/Database/ListOfPrimitivesTests.cs, Tests/Realm.Tests/Database/TestObjects.cs
Fixes https://github.com/realm/realm-dotnet/issues/1911
=> Allow [Required] on IList<string>

CHANGELOG.md, Realm/Realm/RealmObject.cs, Tests/Realm.Tests/Database/RealmObjectTests.cs
=> Fix xml serialization of RealmObject classes

Realm/Realm/Handles/SharedRealmHandleExtensions.cs, Realm/Realm/InteropConfig.cs, Realm/Realm/Native/NativeCommon.cs, Realm/Realm/Sync/User.cs, Tests/Realm.Tests/RealmTest.cs, Tests/Realm.Tests/Sync/MetadataTests.cs, wrappers/src/sync_manager_cs.cpp
Fixes #1956 
Fixes #1960 
Fixes #1967
=> RNET-194: Only encrypt user metadata where necessary.

CHANGELOG.md, Realm/Realm/RealmCollectionBase.cs, Tests/Realm.Tests/Database/CollectionTests.cs, Tests/Realm.Tests/Database/NotificationTests.cs, Tests/Realm.Tests/EventHelper.cs, wrappers/build.ps1
=> RNET-207: Fix access to invalidated list error when adding objects to a list whose parent is deleted

Jenkinsfile, Tests/Realm.Tests/Program.cs, Tests/Realm.Tests/TestHelpers.cs, Tests/Tests.XamarinMac/Tests.XamarinMac.csproj, Tests/Tests.XamarinMac/ViewController.cs
Fixes #2009 by replacing xunit reporting with junit.
=> Use junit for test reporting

CHANGELOG.md, Jenkinsfile, Realm/AssemblyInfo.props
=> Publish github prerelease packages

Jenkinsfile
TODO: don't enforce macos-catalina for builds
=> Use the CPH macs for building v10

CHANGELOG.md
This updates the changelog to reflect the most recent Studio releases.
=> Update changelog to reflect Realm Studio releases

Tests/Realm.Tests/Database/ListOfPrimitivesTests.cs, Tests/Realm.Tests/Database/TestObjects.cs, Tests/Weaver/AssemblyToProcess/TestObjects.cs, wrappers/src/list_cs.cpp, wrappers/src/marshalling.hpp, wrappers/src/object_cs.cpp
Fixes https://github.com/realm/realm-dotnet/issues/2036
=> RNET-255: Add support for lists of decimals/objectids

Tests/Realm.Tests/Database/AsyncTests.cs, Tests/Realm.Tests/Database/CollectionTests.cs, Tests/Realm.Tests/Database/ConfigurationTests.cs, Tests/Realm.Tests/Database/DateTimeTests.cs, Tests/Realm.Tests/Database/InMemoryTests.cs, Tests/Realm.Tests/Database/InstanceTests.cs, Tests/Realm.Tests/Database/LifetimeTests.cs, Tests/Realm.Tests/Database/ListOfPrimitivesTests.cs, Tests/Realm.Tests/Database/MigrationTests.cs, Tests/Realm.Tests/Database/NotificationTests.cs, Tests/Realm.Tests/Database/ObjectIntegrationTests.cs, Tests/Realm.Tests/Database/PrimaryKeyTests.cs, Tests/Realm.Tests/Database/PropertyChangedTests.cs, Tests/Realm.Tests/Database/RealmResults/DisallowedPredicateParameters.cs, Tests/Realm.Tests/Database/RealmResults/SimpleLINQtests.cs, Tests/Realm.Tests/Database/RefreshTests.cs, Tests/Realm.Tests/Database/RemoveTests.cs, Tests/Realm.Tests/Database/StandAloneObjectTests.cs, Tests/Realm.Tests/Database/ThreadHandoverTests.cs, Tests/Realm.Tests/RealmInstanceTest.cs, Tests/Realm.Tests/RealmTest.cs, Tests/Realm.Tests/Sync/SessionTests.cs, Tests/Realm.Tests/Sync/SyncConfigurationTests.cs, Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
=> Clean up tests and ensure we delete everything we create

CHANGELOG.md
=> Fix up the changelog

Realm/Realm.Unity/Editor/Common/WeaveResults.cs, Realm/Realm.Unity/Editor/UnityWeaver.cs, Realm/Realm.Unity/Editor/WeaverAssemblyResolver.cs, Realm/Realm/Realm.csproj, Tools/SetupUnityPackage/SetupUnityPackage/Program.cs
* Fixes first part of #2136
* Fixes the casing of info.plist
* Adds [Preserve] to UnityUtils to prevent stripping
=> Trigger weaving on editor plugin load

Realm/Realm.Unity/Editor/UnityWeaver.cs, Realm/Realm.Unity/Editor/WeaverAssemblyResolver.cs
* Add a build callback to weave assemblies
* Replace realm-wrappers with __Internal for dll imports on iOS
Fixes #2136
=> Unity fixes for iOS

CHANGELOG.md, Jenkinsfile, Realm/Realm/GlobalSuppressions.cs, Realm/Realm/Native/Credentials.cs, Realm/Realm/Native/FindAndModifyOptions.cs, Realm/Realm/Sync/Credentials.cs, Realm/Realm/Sync/GoogleCredentialType.cs, wrappers/src/app_cs.hpp
=> Update to latest sync and add support for the new credential types

CHANGELOG.md, Realm/Realm.Unity/Editor/Common/RealmWeaver.cs
Release 10.0.0-beta.3 with sync fixes + new google credentials method.
=> Prepare for 10.0.0-beta.3

CHANGELOG.md, Jenkinsfile, Realm/Realm.Unity/Editor/Common/RealmWeaver.cs, Realm/Realm/Handles/AppHandle.cs
Bumps versions and reverts the code that disabled Guid/ISet properties.
=> Prepare for vnext

README.md
=> Make reference to wrappers/README.md a link

CHANGELOG.md, Realm/Realm/DatabaseTypes/RealmObjectBase.cs, Realm/Realm/Extensions/FrozenObjectsExtensions.cs, Tests/Realm.Tests/Database/RealmObjectTests.cs, Tests/Realm.Tests/RealmInstanceTest.cs, Tests/Weaver/Realm.FakeForWeaverTests/Realm.FakeForWeaverTests.csproj
Fixes https://github.com/realm/realm-dotnet/issues/2180
=> Remove RealmObject.FreezeInPlace

CHANGELOG.md
Fixes https://github.com/realm/realm-dotnet/issues/1664 and similar multiprocess issues on Windows.
=> Update to newest Core

Realm/Realm/Handles/SharedRealmHandle.cs, Realm/Realm/Realm.cs, Tests/Realm.Tests/Database/InstanceTests.cs, Tests/Realm.Tests/Database/ListOfPrimitivesTests.cs, wrappers/src/shared_realm_cs.cpp, wrappers/src/shared_realm_cs.hpp
Added freeing of the handle in `State` when disposing of realm.
Fixes #2184
=> Fix memory leak due to handle

CHANGELOG.md, Jenkinsfile
Release beta.6 with a fix for the date regression.
=> Prepare for beta.6

CHANGELOG.md, Realm/AssemblyInfo.props
=> vNext changelog update

CHANGELOG.md, Jenkinsfile, Realm/AssemblyInfo.props, Realm/Realm.Unity/Editor/Common/Analytics.cs, Realm/Realm/Handles/AppHandle.cs
Merges the changelog updates from v10 and bumps the version to 10.5.0. The number was arbitrarily chosen and we'll update it once we get closer to releasing the data types.
=> Merge relevant portions from v10 and bump version to 10.5 (arbitrarily)

CHANGELOG.md, Jenkinsfile, Realm/Realm/Handles/AppHandle.EmailPassword.cs, Realm/Realm/Handles/AppHandle.cs, wrappers/CMakeLists.txt, wrappers/build.ps1, wrappers/src/CMakeLists.txt
Fixes https://github.com/realm/realm-dotnet/issues/2215
=> Enable LTO builds

Realm - Windows.sln, Realm/Realm/DatabaseTypes/RealmCollectionBase.cs, Realm/Realm/DatabaseTypes/RealmDictionary.cs, Realm/Realm/DatabaseTypes/RealmList.cs, Tests/Realm.Tests/Database/EmbeddedObjectsTests.cs, Tests/Realm.Tests/Database/RealmDictionaryTests.cs, Tests/Realm.Tests/Database/TestObjects.cs, wrappers/src/dictionary_cs.cpp, wrappers/src/marshalling.hpp, wrappers/src/results_cs.cpp
Fixes https://github.com/realm/realm-dotnet/issues/2210
=> Add support for dictionaries of objects

Realm/Realm/DatabaseTypes/RealmCollectionBase.cs, Realm/Realm/DatabaseTypes/RealmDictionary.cs, Realm/Realm/Dynamic/MetaRealmDictionary.cs, Realm/Realm/Realm.cs, Tests/Realm.Tests/Database/DynamicEmbeddedTests.cs, Tests/Realm.Tests/Database/DynamicRelationshipTests.cs, Tests/Realm.Tests/Database/EmbeddedObjectsTests.cs, Tests/Realm.Tests/Database/PropertyChangedTests.cs, Tests/Realm.Tests/Database/RealmDictionaryTests.cs, Tests/Realm.Tests/Database/TestObjects.cs, Tests/Realm.Tests/TestHelpers.cs, wrappers/src/dictionary_cs.cpp
=> Add embedded object support for dictionaries

CHANGELOG.md, wrappers/src/results_cs.cpp
=> Use new core

Realm/Realm.UnityUtils/Initializer.cs, Realm/Realm/Handles/SharedRealmHandle.cs, Realm/Realm/InteropConfig.cs, Realm/Realm/Native/NativeCommon.cs, Realm/Realm/Native/SynchronizationContextScheduler.cs, wrappers/src/app_cs.cpp, wrappers/src/app_cs.hpp, wrappers/src/marshalling.hpp, wrappers/src/scheduler_cs.cpp, wrappers/src/shared_realm_cs.cpp, wrappers/src/sync_session_cs.cpp, wrappers/src/sync_session_cs.hpp, wrappers/src/transport_cs.cpp
More fixes to make the SDK resilient to domain unloads.
Fixes https://github.com/realm/realm-dotnet/issues/2273.
=> More protective measures related to domain unloading

CHANGELOG.md
=> Bump to latest Core

Tests/Realm.Tests/Database/TestObjects.cs, Tests/Realm.Tests/Sync/DataTypeTests.cs, Tests/Realm.Tests/Sync/SyncTestBase.cs
Blocked on https://jira.mongodb.org/browse/REALMC-8495.
=> Add e2e dictionary tests

Realm/Realm/DatabaseTypes/RealmDictionary.cs, Tests/Realm.Tests/Database/RealmDictionaryTests.cs
Fixes https://github.com/realm/realm-dotnet/issues/2316
=> Add tests for invalid dictionary keys

Realm/Realm/DatabaseTypes/RealmValue.cs, Realm/Realm/Handles/CollectionHandleBase.cs, Realm/Realm/Handles/DictionaryHandle.cs, Realm/Realm/Handles/ListHandle.cs, Realm/Realm/Handles/ObjectHandle.cs, Realm/Realm/Handles/ResultsHandle.cs, Realm/Realm/Handles/SetHandle.cs, Realm/Realm/Helpers/Argument.cs, Realm/Realm/Logging/Logger.cs, Realm/Realm/Native/PrimitiveValue.cs, Realm/Realm/Realm.cs, Tests/Realm.Tests/Database/RealmValueTests.cs, wrappers/src/list_cs.cpp, wrappers/src/marshalling.hpp, wrappers/src/object_cs.cpp, wrappers/src/results_cs.cpp, wrappers/src/set_cs.cpp, wrappers/src/shared_realm_cs.cpp, wrappers/src/shared_realm_cs.hpp
Final touches for #2252 
Unrelated to that, the changes in https://github.com/realm/realm-dotnet/pull/2328/commits/d48ed01f6cc85be037a3bb834cd14eb9441bb555 attempt to fix Compact when called with SyncConfiguration.
=> Store the looked up schema in the binding context

CHANGELOG.md, Jenkinsfile, wrappers/android.Dockerfile
=> Prepare for 10.1.3

.gitignore, Tests/Readme.md, Tests/Realm.Tests/Database/CollectionTests.cs, Tests/Realm.Tests/Database/DateTimeTests.cs, Tests/Realm.Tests/Database/EmbeddedObjectsTests.cs, Tests/Realm.Tests/Database/InstanceTests.cs, Tests/Realm.Tests/Database/ListOfPrimitivesTests.cs, Tests/Realm.Tests/Database/NotificationTests.cs, Tests/Realm.Tests/Database/PrimaryKeyTests.cs, Tests/Realm.Tests/Database/RealmIntegerTests.cs, Tests/Realm.Tests/Database/RealmSetTests.cs, Tests/Realm.Tests/Database/TestObjects.cs, Tests/Realm.Tests/TestHelpers.cs, Tests/Tests.Unity/.TestConfigs/IL2CPP-Net4.json, Tests/Tests.Unity/.TestConfigs/Mono-Net4.json, Tests/Tests.Unity/Assembly-CSharp-Editor.csproj, Tests/Tests.Unity/Assets/Editor/BuildManager.cs, Tests/Tests.Unity/Assets/TestsManager/TestManager.cs, Tests/Tests.Unity/ProjectSettings/ProjectSettings.asset, Tests/Tests.Unity/ProjectSettings/ProjectVersion.txt, Tests/Tests.Unity/Tests.Player.csproj, Tests/Tests.Unity/Tests.csproj
Refactors tests and fixes issues when run with IL2CPP.
Fixes https://github.com/realm/realm-dotnet/issues/2372
=> Changes needed to get IL2CPP tests passing

Jenkinsfile, Tests/Realm.Tests/Database/TestObjects.cs, Tests/Realm.Tests/Sync/DataTypeTests.cs, wrappers/src/sync_user_cs.cpp
This PR adds a couple of sync tests for float
Fixes #2348
=> Sync tests for float

Tests/Realm.Tests/Sync/DataTypeTests.cs
=> Added fix for sync tests

Realm/Realm/DatabaseTypes/RealmInteger.cs, Realm/Realm/DatabaseTypes/RealmObjectBase.cs, Realm/Realm/Helpers/Operator.cs, Realm/Realm/Helpers/Operator.tt, Realm/Realm/Helpers/SerializationHelper.cs, Realm/Realm/Sync/ApiKey.cs, Realm/Realm/Sync/Credentials.cs, Realm/Realm/Sync/MongoClient.cs, Realm/Realm/Sync/UserIdentity.cs, Tests/Realm.Tests/Database/EmbeddedObjectsTests.cs, Tests/Realm.Tests/Database/InstanceTests.cs, Tests/Realm.Tests/Database/MigrationTests.cs, Tests/Realm.Tests/Sync/DataTypeTests.cs, Tests/Realm.Tests/Sync/FunctionsTests.cs, Tests/Realm.Tests/Sync/MergeByPKTests.cs, Tests/Realm.Tests/Sync/MongoClientTests.cs, Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs, Tests/Realm.Tests/Sync/UserManagementTests.cs
Fixes https://github.com/realm/realm-dotnet/issues/2372
=> Fix IL2CPP Sync

.github/templates/Readme.md, .github/templates/main.yml, .github/workflows/main.yml, Jenkinsfile
Fixes https://github.com/realm/realm-dotnet/issues/2285
* Replaces the code to unstash wrapper binaries with a loop
* Adds steps to build the unity package both with and without deps
=> Add Unity build to the GHA pipeline

wrappers/src/app_cs.cpp, wrappers/src/sync_user_cs.cpp
Will likely introduce segfaults on Linux. We'll address those separately.
=> Update to latest v11

CHANGELOG.md, Realm/Realm/DatabaseTypes/RealmSet.cs, Realm/Realm/DatabaseTypes/RealmValue.cs, Realm/Realm/Extensions/RealmValueExtensions.cs
Spun off from https://github.com/realm/realm-dotnet/pull/2404
Fixes https://github.com/realm/realm-dotnet/issues/2412
=> Add custom comparer for sets of numeric RealmValues

Realm/Realm/DatabaseTypes/RealmDictionary.cs, Realm/Realm/Handles/DictionaryHandle.cs, Realm/Realm/Linq/DictionaryChangeSet.cs, Tests/Realm.Tests/Database/RealmDictionaryTests.cs, wrappers/src/dictionary_cs.cpp, wrappers/src/notifications_cs.hpp
Depends on https://github.com/realm/realm-dotnet/pull/2404
=> Add support for deletions in the key-based notifications for dicts

CHANGELOG.md, Realm/Realm/Configurations/SyncConfiguration.cs, Realm/Realm/Sync/ProgressNotifications/ProgressNotificationToken.cs, Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
Fixes https://github.com/realm/realm-dotnet/issues/2400
=> Fix NRE reported in rnet-454

Jenkinsfile, Tests/.gdbinit, Tests/netcore31.Dockerfile, wrappers/src/sync_user_cs.cpp
This combines https://github.com/realm/realm-dotnet/pull/2355 and https://github.com/realm/realm-core/pull/4716 in an attempt to trigger a linux crash and run gdb to investigate what is causing it.
=> Update to Core with app destruction fix

CHANGELOG.md, Jenkinsfile, Realm/Realm.Unity/package.json, Realm/Realm.Weaver/Analytics.cs, Realm/Realm/Handles/AppHandle.cs
=> Upgrade to Core 11.0.3

.github/templates/main.yml, .github/workflows/benchmark-ios.yml, .github/workflows/benchmark.yml, .github/workflows/lint.yml, .github/workflows/main.yml
Just a minor renaming to make them shorter and easier to read as the long names were getting trimmed in the GHA UI.
=> Rename the GHA steps to make them shorter

.github/templates/main.yml, .github/workflows/main.yml
Mostly just renames the publishing step so that it's consistent with the wording in the testing step
=> Rename results steps

wrappers/src/app_cs.hpp, wrappers/src/results_cs.cpp
Pretty boring, figured might as well fix them to avoid getting warnings on every PR build.
=> Fix some native warnings

CHANGELOG.md, Realm/Realm/Helpers/SerializationHelper.cs
Adds a bunch of serializers to the preserved ones to make sure at least some basic serialization works without hiccups on Unity.
=> Add more serializer types to the preserved ones

Realm/Realm/Sync/AppConfiguration.cs
Fixes https://github.com/realm/realm-dotnet/issues/2493
=> Update the AppConfiguration.Logger obsolete message

.github/templates/main.yml, .github/workflows/main.yml, CHANGELOG.md, Realm/Realm.Weaver/Analytics.cs
=> Stop sending analytics to mixpanel

CHANGELOG.md, Realm/Realm.UnityUtils/Initializer.cs, Realm/Realm/Logging/Logger.cs, Realm/Realm/Sync/AppConfiguration.cs
Fixes https://github.com/realm/realm-dotnet/issues/2481
=> Fix Logger.Default on Unity

CHANGELOG.md, Realm/Realm/DatabaseTypes/RealmCollectionBase.cs, Realm/Realm/DatabaseTypes/RealmList.cs, Realm/Realm/Extensions/CollectionExtensions.cs, Realm/Realm/Handles/CollectionHandleBase.cs, Realm/Realm/Handles/DictionaryHandle.cs, Realm/Realm/Handles/ListHandle.cs, Realm/Realm/Handles/ResultsHandle.cs, Realm/Realm/Handles/SetHandle.cs, Tests/Realm.Tests/Database/CollectionTests.cs, Tests/Realm.Tests/Database/TestObjects.cs, wrappers/src/list_cs.cpp
Fixes https://github.com/realm/realm-dotnet/issues/1499
=> Allow lists to be converted to queries

.github/actions/benchmark-uploader/dist/index.js, .github/actions/benchmark-uploader/src/main.ts, .github/workflows/main.yml, CHANGELOG.md
Also, adds a changelog entry that I had forgotten.
=> Remove refs/heads/ from branch name when uploading benchmark results

.github/templates/main.yml, .github/workflows/main.yml, CHANGELOG.md, wrappers/README.md
=> Install the win 81 SDK when building wrappers on GHA

Realm/Realm/Schema/ObjectSchema.cs
Corrects link for error message
=> Added correct link

.github/templates/main.yml, .github/workflows/main.yml, .github/workflows/prepare-release.yml
Fixes https://github.com/realm/realm-dotnet/issues/2586
=> Start uploading coverage reports to coveralls.io

Tests/Realm.Tests/Database/RealmObjectTests.cs
Adds more comprehensive tests for Equals and ToString.
=> Add more tests for RealmObject

.github/templates/main.yml, .github/workflows/main.yml
I noticed we see leftover files from previous runs in the self-hosted workspace. Add a powershell step to remove everything.
=> Cleanup self-hosted workspaces

.github/templates/common.lib.yml, .github/templates/publish-release.yml, .github/workflows/publish-release.yml, CHANGELOG.md
This should wrap up our release workflow. After publishing to Nuget/npm, it will merge the release PR, publish the Github release, tag master, then create a new PR, updating the changelog and merge that in.
=> Wrap up the release workflow

.github/templates/publish-release.yml, .github/workflows/prepare-release.yml, .github/workflows/publish-release.yml, Realm/Realm/Realm.csproj
=> Fixes to the release workflows

CHANGELOG.md, Realm/Realm/RealmWrappersReferences.props
Fixes https://github.com/realm/realm-dotnet/issues/1877. Tested it manually and seems to work, will test again when CI produces a package.
=> Use Content instead of None for the native libs on .NET Framework

.github/templates/main.yml, .github/workflows/main.yml
Fixes 6.0.1-rc.1 breaks compilation of our tests. Pin preview.7 and hope they fix it with a future update.
=> Pin .NET 6 to preview 7

.github/templates/publish-release.yml, .github/workflows/prepare-release.yml, .github/workflows/publish-release.yml
A minor cosmetic improvement for commits generated by Github Actions.
=> Add commit messages to prepare and publish release PRs

.github/templates/main.yml, .github/templates/publish-release.yml, .github/workflows/main.yml, .github/workflows/publish-release.yml, CHANGELOG.md
=> Run perf test on a self-hosted runner

Realm/Realm/Realm.cs
Supersedes https://github.com/realm/realm-dotnet/pull/2658
=> Fix awkward wording for Realm.IsInTransaction

.github/sleet.json, .github/templates/common.lib.yml, .github/templates/main.yml, .github/templates/publish-prerelease.yml, .github/templates/publish-release.yml, .github/workflows/main.yml, .github/workflows/publish-prerelease.yml, .github/workflows/publish-release.yml, CHANGELOG.md, Realm/Realm.Fody/Realm.Fody.csproj
Fixes https://github.com/realm/realm-dotnet/issues/2708
=> Add a dispatch workflow to upload packages to an S3 bucket

wrappers/README.md
Corrected the README.md file for how to build wrappers
Fixes #2748
=> Update README.md  for wrappers

CHANGELOG.md, Realm/Realm/Handles/QueryHandle.cs, Realm/Realm/Linq/RealmResultsVisitor.cs, Tests/Realm.Tests/Database/CollectionTests.cs, wrappers/src/query_cs.cpp
=> Respect limit when counting query matches

Realm/Realm/Linq/RealmResultsVisitor.cs
Fixes https://github.com/realm/realm-dotnet/issues/1373
I'm a first time contributor and I would like to ask what are changelog entries specifically?
=> Fix `TraverseSort` to support properties declared by interfaces

Tests/Realm.Tests/Database/MigrationTests.cs
This only adds a test that passes, meaning https://github.com/realm/realm-dotnet/issues/2587 was not a real bug and most likely a logic issue. Still, worth having a test to verify it in case another user reports a similar problem.
Fixes https://github.com/realm/realm-dotnet/issues/2587
=> Add a migration test that removes objects from the Realm

global.json, wrappers/src/marshalling.hpp, wrappers/src/query_cs.cpp
=> Silence some warnings

Tests/Realm.Tests/Database/ListOfPrimitivesTests.cs, Tests/Realm.Tests/Database/RealmSetTests.cs, Tests/Realm.Tests/Database/RealmValueTests.cs
This is mostly for VS/Unity test explorer - they really dislike random test parameters.
=> Replace random test parameters with constants

.github/templates/main.yml, .github/workflows/main.yml, CHANGELOG.md, Realm/Realm.Unity/Runtime/macOS/librealm-wrappers.dylib.meta, Realm/Realm/Realm.csproj, Realm/Realm/RealmWrappersReferences.props, Tools/SetupUnityPackage/CommandLineOptions/RealmOptions.cs
=> Make the nuget package target the osx universal runtime

Realm/Realm/Sync/SchemaMode.cs, Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs, wrappers/build-ios.ps1, wrappers/build-ios.sh, wrappers/build-macos.sh, wrappers/src/shared_realm_cs.cpp
=> Update to latest core

.github/templates/codeql.yml, .github/templates/main.yml, .github/workflows/codeql.yml, .github/workflows/main.yml
Fixes https://github.com/realm/realm-dotnet/issues/2850
=> Don't run workflows when code hasn't changed

Realm/Realm.Weaver/Analytics.cs
=> Migrate to HTTPS endpoint

CHANGELOG.md
=> Update to Core 11.12.0

CHANGELOG.md, Realm/Realm/Sync/App.cs, Realm/Realm/Sync/AppConfiguration.cs, Tests/Realm.Tests/Sync/AppTests.cs
Fixes https://github.com/realm/realm-dotnet/issues/2892
=> Don't use the managed http client handler unless explicitly specified

CHANGELOG.md
=> Updated core to 11.14.0

Tests/Realm.Tests/Sync/BaasClient.cs
This PR fixes the test harness to use the new admin API. Similar to what https://github.com/realm/realm-core/pull/5333 did for core
=> Update test harness to new API

Realm/Realm/DataBinding/RealmObjectTypeDelegator.cs, Tests/Realm.Tests/Database/ReflectableTypeTests.cs
=> Modified type delegator and added test

CHANGELOG.md, Realm/Realm/Exceptions/Sync/ErrorCode.cs, Tests/Realm.Tests/Sync/FlexibleSyncTests.cs
=> Update to Core 12.1.0

.github/templates/build.lib.yml, .github/templates/common.lib.yml, .github/templates/main.yml, .github/templates/pr.yml, .github/templates/test-code-coverage.yml, .github/templates/test-net-core.yml, .github/templates/test-weaver.yml, .github/templates/test.lib.yml, .github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/test-code-coverage.yml, .github/workflows/test-net-core.yml, .github/workflows/test-weaver.yml, Tests/Realm.Tests/Program.cs, Tests/Realm.Tests/Realm.Tests.csproj
=> Add M1 tests on CI

Realm/Realm.Weaver/ImportedReferences.cs, Realm/Realm.Weaver/RealmWeaver.cs, Realm/Realm/DatabaseTypes/Accessors/ManagedAccessor.cs, Realm/Realm/DatabaseTypes/Accessors/UnmanagedAccessor.cs, Realm/Realm/DatabaseTypes/RealmObjectBase.cs, Realm/Realm/Dynamic/DynamicRealmObjectHelper.cs, Realm/Realm/Extensions/RealmObjectExtensions.cs, Realm/Realm/Realm.cs, Realm/Realm/Weaving/IRealmObjectHelper.cs, Tests/Realm.Tests/SourceGeneration/ManualGenerationTests.cs, Tests/Realm.Tests/SourceGeneration/TestClasses/ManuallyGeneratedClass.cs, Tests/Weaver/Realm.FakeForWeaverTests/RealmObject.cs
This is a very messy POC of how the class hierarchy could look like. Some notes:
* We now have Managed/UnmanagedAccessor base classes and a generic implementation for both. The generic is intended to be used when we use the weaver (it's what we default to). The non-generic is to be used by SG.
* `IRealmObjectHelper` can now create a managed accessor which is then set on the object instance.
* The accessor initializer is internal as it requires access to internal types
* Created an interface for the generated accessor and implementations for both unmanaged/managed using concrete properties.
=> Have fun with the SG scaffolding

CHANGELOG.md
Adds changelog entries from https://github.com/realm/realm-dotnet/pull/2981.
=> Add Changelog entries from the core upgrade

Realm/Realm/Sync/User.cs, Tests/Realm.Tests/Database/InstanceTests.cs, Tests/Realm.Tests/Sync/AppTests.cs, Tests/Realm.Tests/Sync/FlexibleSyncTests.cs, Tests/Realm.Tests/Sync/SyncConfigurationTests.cs
=> Try to fix MAUI failing test

Realm/Realm.SourceGenerator/ClassCodeBuilder.cs, Realm/Realm.SourceGenerator/Parser.cs, Realm/Realm.SourceGenerator/Utils.cs, Realm/Realm/Extensions/RealmObjectExtensions.cs, Tests/SourceGenerators/Realm.SourceGenerator.Tests/CSharpSourceGeneratorVerifier.cs, Tests/SourceGenerators/Realm.SourceGenerator.Tests/UtilsTests.cs, Tests/SourceGenerators/SourceGeneratorAssemblyToProcess/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/AllTypesClass_generated.cs, Tests/SourceGenerators/SourceGeneratorAssemblyToProcess/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/Dog_generated.cs, Tests/SourceGenerators/SourceGeneratorAssemblyToProcess/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/Person_generated.cs
=> Add some indenting capabilities to the SG

.github/templates/main.yml, .github/templates/test-android.yml, .github/workflows/main.yml, .github/workflows/test-android.yml
Since the introduction of MAUI tests, we renamed the xamarinandroid job to android, which broke the main workflow.
=> Fix the main workflow

CHANGELOG.md, Realm/Realm.Fody/ModuleWeaver.cs
=> More meaningful error message when target framework missing

CHANGELOG.md, wrappers/src/guid_representation_migration.cpp
=> Upgrade to Core 12.7.0

CHANGELOG.md, wrappers/src/transport_cs.cpp, wrappers/src/transport_cs.hpp
=> Upgrade to Core 12.9.0

Realm/Realm.Weaver/Analytics.cs
Aligns metrics endpoint with other SDKs
=> Use different endpoint for metrics (drop _stage)

.github/templates/common.lib.yml, .github/templates/wrappers.yml, .github/workflows/wrappers.yml, CHANGELOG.md, wrappers/CMakeLists.txt, wrappers/build-ios.ps1
Fixes https://github.com/realm/realm-dotnet/issues/3059
=> Disable bitcode for iOS builds

.github/templates/codeql.yml, .github/workflows/codeql.yml
It never finds any issues with our code, but keeps reporting problems from dependencies, such as OpenSSL.
=> Disable the cpp version of codeql

Tools/DeployApps/BaasClient.cs
Just a little bit of tweaking - I noticed there was a typo - `useId` vs `userId` which is why we weren't logging the user id (even though the actual deletion was succeeding). I also reshuffled the code a little bit to make it shorter.
=> Cleanup trigger client reset function

.github/auto_assign.yml, .github/workflows/auto-assign.yml, .github/workflows/check-changelog.yml, CHANGELOG.md
Part of https://github.com/realm/realm-dotnet/issues/3063
=> Add workflows for automatically assigning users and changelog verification

.github/actions/benchmark-uploader/action.yml, .github/actions/benchmark-uploader/package-lock.json, .github/actions/benchmark-uploader/package.json, .github/actions/run-android-device-farm-test/action.yml, .github/workflows/deploy-baas.yml
Update benchmark-uploader to use node 16
Part of https://github.com/realm/realm-dotnet/issues/3063
=> Update setup-dotnet action

.github/templates/build-packages.yml, .github/templates/common.lib.yml, .github/templates/main.yml, .github/templates/test-net-core.yml, .github/templates/test.lib.yml, .github/workflows/build-packages.yml, .github/workflows/lint.yml, .github/workflows/main.yml, .github/workflows/publish-prerelease.yml, .github/workflows/publish-release.yml, .github/workflows/test-android.yml, .github/workflows/test-code-coverage.yml, .github/workflows/test-ios.yml, .github/workflows/test-macos.yml, .github/workflows/test-net-core.yml, .github/workflows/test-net-framework.yml, .github/workflows/test-source-generation.yml, .github/workflows/test-unity.yml, .github/workflows/test-uwp-managed.yml, .github/workflows/test-weaver.yml, .github/workflows/test-woven-classes.yml, .github/workflows/wrappers.yml, Tests/Realm.Tests/Sync/AsymmetricObjectTests.cs, Tests/Realm.Tests/Sync/SyncConfigurationTests.cs, Tests/Realm.Tests/TestHelpers.cs
Part of https://github.com/realm/realm-dotnet/issues/3063
=> Update test reporter action

.github/templates/publish-release.yml, .github/workflows/publish-release.yml, CHANGELOG.md, Tests/Realm.Tests/Database/CollectionTests.cs
=> Update to Core 12.12.0

Realm/Realm.SourceGenerator/Diagnostics.cs
=> Corrected typo

CHANGELOG.md, Realm/Realm/Handles/SubscriptionSetHandle.cs, Tests/Realm.Tests/Sync/FlexibleSyncTests.cs, wrappers/src/shared_realm_cs.cpp, wrappers/src/subscription_set_cs.cpp
Fixes https://github.com/realm/realm-dotnet/issues/2952
=> Fix subscription set being deleted while waiting

CHANGELOG.md, Realm/Realm.UnityUtils/Initializer.cs, Realm/Realm/Native/NativeCommon.cs
=> Fix Realm not getting reinitialized when domain reload is disabled

CHANGELOG.md, Realm/Realm/DatabaseTypes/RealmCollectionBase.cs, Realm/Realm/DatabaseTypes/RealmList.cs
Putting this up to get a package and see if the Xamarin.Forms bug still exists.
Fixes https://github.com/realm/realm-dotnet/issues/1759
=> Bring back IList conformance to RealmCollectionBase

CHANGELOG.md, Realm/Realm/Linq/RealmResultsVisitor.cs, Tests/Realm.Tests/Database/RealmResults/SimpleLINQtests.cs
Fixes https://github.com/realm/realm-dotnet/issues/3134
Fixes https://github.com/realm/realm-dotnet/issues/2747
Supersedes https://github.com/realm/realm-dotnet/pull/3140 and https://github.com/realm/realm-dotnet/pull/2753.
=> Fix string.Contains with .NET 2.1 or higher

.github/templates/test-ios.yml, .github/workflows/test-ios.yml, CHANGELOG.md, Realm/Realm/DatabaseTypes/RealmDictionary.cs, Realm/Realm/DatabaseTypes/RealmSet.cs, Realm/Realm/Exceptions/Sync/ErrorCode.cs
=> Deprecate legacy error codes

CHANGELOG.md, Realm/Realm/Sync/User.cs, Tests/Realm.Tests/Sync/UserManagementTests.cs
Fixes https://github.com/realm/realm-dotnet/issues/3073
=> Deprecate push client

CHANGELOG.md, Tests/Tests.UWP/RunTests.ps1
Fixes https://github.com/realm/realm-dotnet/issues/3030
=> Fix uwp workflow when running in debug

.github/templates/common.lib.yml, .github/workflows/wrappers.yml
=> Bump docker layer caching action to use node16

CHANGELOG.md, Realm/Realm.UnityWeaver/Realm.UnityWeaver.csproj, Realm/Realm.Weaver/RealmWeaver.Schema.cs
Fixes https://github.com/realm/realm-dotnet/issues/3199
=> Workaround Mono yield bug

.github/workflows/prepare-release.yml
=> Allow overriding the version when preparing a release

Tests/Realm.Tests/ConfigHelpers.cs, Tests/Realm.Tests/GlobalSuppressions.cs, Tests/Realm.Tests/Realm.Tests.csproj, Tests/Realm.Tests/Sync/SyncTestHelpers.cs
Additionally, replaces configuration manager with manual xml parsing.
Fixes https://github.com/realm/realm-dotnet/issues/3108
=> Fix copying of wrappers when running tests

CHANGELOG.md, Realm/Realm/Helpers/SerializationHelper.cs, Realm/Realm/Native/NativeCommon.cs
Fixes https://github.com/realm/realm-dotnet/issues/3225
=> Use BsonSerializer.RegisterProvider

CHANGELOG.md, Realm/Realm/DatabaseTypes/RealmCollectionBase.cs, Realm/Realm/DatabaseTypes/RealmDictionary.cs, Realm/Realm/Linq/IRealmCollection.cs, Tests/Realm.Tests/Database/CollectionTests.cs, Tests/Realm.Tests/Database/InMemoryTests.cs, Tests/Realm.Tests/Database/InstanceTests.cs, Tests/Realm.Tests/Database/ListOfPrimitivesTests.cs, Tests/Realm.Tests/Database/NotificationTests.cs, Tests/Realm.Tests/Database/RealmDictionaryTests.cs, Tests/Realm.Tests/Database/RealmSetTests.cs, Tests/Realm.Tests/Sync/SessionTests.cs
=> [v11] 1. Remove error argument from notification callbacks

CHANGELOG.md, Realm/Realm/Configurations/InMemoryConfiguration.cs, Realm/Realm/Configurations/RealmConfiguration.cs, Realm/Realm/Configurations/RealmConfigurationBase.cs, Realm/Realm/Configurations/SyncConfigurationBase.cs, Tests/Realm.Tests/Database/InMemoryTests.cs
It has never worked, so we're removing it to make that explicit.
=> [v11] 4. Remove InMemoryConfiguration.EncryptionKey

CHANGELOG.md, Realm/Realm/Extensions/TestingExtensions.cs, Realm/Realm/GlobalSuppressions.cs, Realm/Realm/Handles/SessionHandle.cs, Realm/Realm/Sync/ErrorHandling/ManualRecoveryHandler.cs, Realm/Realm/Sync/Session.cs, Tests/Realm.Tests/Sync/DataTypeSynchronizationTests.cs, Tests/Realm.Tests/Sync/SessionTests.cs, Tests/Realm.Tests/Sync/SyncTestHelpers.cs
Removes `Session.Error` and `ManualRecoveryHandler.ctor()`.
=> [v11] 9. Remove Session.Error

Realm/Realm.UnityWeaver/UnityWeaver.cs, Realm/Realm.Weaver/Analytics/Analytics.cs, Realm/Realm.Weaver/Analytics/AnalyticsUtils.cs, Realm/Realm.Weaver/Analytics/Metric.cs
=> Extract CPU architecture from Unity

examples/SimpleToDoAvalonia/Models/Item.cs, examples/SimpleToDoAvalonia/Models/ToDoList.cs, examples/SimpleToDoAvalonia/SimpleToDo.csproj, examples/SimpleToDoAvalonia/ViewModels/MainViewModel.cs, examples/SimpleToDoAvalonia/ViewModels/ToDoListCollectionViewModel.cs, examples/SimpleToDoAvalonia/ViewModels/ToDoListViewModel.cs, examples/SimpleToDoAvalonia/Views/ToDoListCollectionView.axaml, examples/SimpleToDoAvalonia/Views/ToDoListView.axaml
A few minor changes to the Avalonia sample I figured would be easier to just make than to comment:
* Suppresses a few warnings (documentation and namespace placement)
* Fixes a few suggestions (spacing in comments, attribute location, etc.)
* Adds a watermark to the item name as it wasn't clear what was going on initially
* Adds a bit of a margin to the "Add a todo list" button as it was bugging me
=> Avalonia example suggestions

.github/templates/publish-release.yml, .github/workflows/publish-release.yml, CHANGELOG.md
=> Upgrade to Core 13.6.0

Realm/Realm.SourceGenerator/Diagnostics.cs, Realm/Realm.SourceGenerator/DiagnosticsEmitter.cs, Realm/Realm.SourceGenerator/InfoClasses.cs, Realm/Realm.SourceGenerator/IsExternalInit.cs, Realm/Realm.SourceGenerator/NullableAttributes.cs, Realm/Realm.SourceGenerator/Parser.cs, Realm/Realm.SourceGenerator/Realm.SourceGenerator.csproj, Realm/Realm.SourceGenerator/SyntaxContextReceiver.cs, Realm/Realm.SourceGenerator/Utils.cs, Realm/Realm.UnityUtils/FileHelper.cs, Realm/Realm.UnityUtils/Initializer.cs, Realm/Realm.UnityUtils/Realm.UnityUtils.csproj, Tools/SetupUnityPackage/CommandLineOptions/RealmOptions.cs, Tools/SetupUnityPackage/CommandLineOptions/TestOptions.cs, Tools/SetupUnityPackage/Helpers.cs, Tools/SetupUnityPackage/PackageInfo.cs, Tools/SetupUnityPackage/Program.cs, Tools/SetupUnityPackage/SetupUnityPackage.csproj
Annotations in this PR:
- SetupUnityPackage
- Realm.UnityUtils
- Realm.SourceGenerator
=> [v11] 10. Annotate projects for nullability

CHANGELOG.md, Realm/Realm/Handles/AppHandle.cs, Realm/Realm/Handles/SharedRealmHandle.cs, Realm/Realm/Logging/LogLevel.cs, Realm/Realm/Logging/Logger.cs, Realm/Realm/Native/AppConfiguration.cs, Realm/Realm/Schema/RealmSchema.cs, Realm/Realm/Sync/App.cs, Tests/Realm.Tests/Database/GuidRepresentationMigrationTests.cs, Tests/Realm.Tests/Database/InstanceTests.cs, Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/LoneClass_generated.cs, Tests/Realm.Tests/RealmTest.cs, Tests/Realm.Tests/TestHelpers.cs, wrappers/src/app_cs.cpp, wrappers/src/marshalling.cpp, wrappers/src/shared_realm_cs.cpp, wrappers/src/shared_realm_cs.hpp, wrappers/src/sync_session_cs.cpp
Fixes https://github.com/realm/realm-dotnet/issues/1885
=> Improve explanation for AddDefaultTypes exception

CHANGELOG.md, Realm/Realm/Exceptions/Sync/PermissionDeniedException.cs, Realm/Realm/Handles/SessionHandle.cs, Tests/Realm.Tests/Sync/SessionTests.cs, Tools/DeployApps/BaasClient.cs
Fixes https://github.com/realm/realm-dotnet/issues/3292
=> Fix PermissionDenied marshaling from Core

Realm/Realm/Exceptions/Sync/ErrorCode.cs, Tests/Realm.Tests/Sync/SessionTests.cs, Tools/DeployApps/BaasClient.cs
Fixes https://github.com/realm/realm-dotnet/issues/3291
=> Bring back the permission denied error code

CHANGELOG.md, Tests/Realm.Tests/Database/InstanceTests.cs, wrappers/src/guid_representation_migration.cpp
Fixes https://github.com/realm/realm-dotnet/issues/3302
=> Guard guid table creation in a write transaction

.github/templates/build-packages.yml, .github/templates/codeql.yml, .github/templates/main.yml, .github/templates/pr.yml, .github/templates/test-android.yml, .github/templates/test-code-coverage.yml, .github/templates/test-ios.yml, .github/templates/test-macos.yml, .github/templates/test-net-core.yml, .github/templates/test-source-generation.yml, .github/templates/test-tvos.yml, .github/templates/test-woven-classes.yml, .github/workflows/build-packages.yml, .github/workflows/codeql.yml, .github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/test-android.yml, .github/workflows/test-code-coverage.yml, .github/workflows/test-ios.yml, .github/workflows/test-macos.yml, .github/workflows/test-net-core.yml, .github/workflows/test-source-generation.yml, .github/workflows/test-woven-classes.yml, Tests/Realm.Tests/Realm.Tests.csproj
Fixes https://github.com/realm/realm-dotnet/issues/3214
=> Change testing targets to net7.0

CHANGELOG.md, Realm/Realm/Handles/SharedRealmHandle.cs, Tests/Realm.Tests/Database/InstanceTests.cs, wrappers/src/shared_realm_cs.cpp
Fixes https://github.com/realm/realm-dotnet/discussions/3335
=> Add a check for the thread in Realm.IsInTransaction

CHANGELOG.md, Realm/Realm/Configurations/RealmConfiguration.cs, Realm/Realm/Native/Configuration.cs, Tests/Realm.Tests/Database/MigrationTests.cs, Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/ObjectContainerEmbedded_generated.cs, Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/ObjectContainerV1_generated.cs, Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/ObjectEmbedded_generated.cs, Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/ObjectV2_generated.cs, wrappers/src/shared_realm_cs.cpp, wrappers/src/shared_realm_cs.hpp
=> Automatically handle object -> embedded object migrations

CHANGELOG.md, Realm/Realm/Handles/ObjectHandle.cs, Realm/Realm/Native/PrimitiveValue.cs, Tests/Realm.Tests/Database/EmbeddedObjectsTests.cs
=> Don't throw an exception when setting an embedded property to the same value

Tests/Readme.md, Tests/Tests.UWP/Tests.UWP.csproj
=> Update UWP certificate, add instructions on how to do it

Realm/Realm/Configurations/SyncConfigurationBase.cs, Realm/Realm/Native/SyncConfiguration.cs, wrappers/src/shared_realm_cs.cpp, wrappers/src/shared_realm_cs.hpp
=> Use system http proxy for sync connections

NuGet.md, Realm/Realm/Realm.csproj
=> Add nuget readme

CHANGELOG.md, Realm/Realm.UnityUtils/DeviceInfo.cs, Realm/Realm.UnityUtils/Initializer.cs, Realm/Realm.UnityUtils/Realm.UnityUtils.csproj, Tests/SourceGenerators/Realm.SourceGenerator.Tests/Program.cs, Tests/SourceGenerators/Realm.SourceGenerator.Tests/UtilsTests.cs
Fixes https://github.com/realm/realm-dotnet/issues/3351
=> Fix namespaces to ensure we don't have Realm as a namespace

CHANGELOG.md, Realm/Realm.PlatformHelpers/Realm.PlatformHelpers.csproj
=> Fix maui namespaces

CHANGELOG.md, Realm/Realm/DatabaseTypes/Geospatial/GeoBox.cs, Realm/Realm/DatabaseTypes/Geospatial/GeoCircle.cs, Realm/Realm/DatabaseTypes/Geospatial/GeoPolygon.cs, Realm/Realm/DatabaseTypes/Geospatial/GeoShapeBase.cs, Realm/Realm/DatabaseTypes/QueryArgument.cs, Realm/Realm/Exceptions/RealmException.cs, Realm/Realm/Exceptions/RealmExceptionCodes.cs, Realm/Realm/Handles/QueryHandle.cs, Tests/Realm.Tests/Database/GeospatialTests.cs, wrappers/src/error_handling.cpp, wrappers/src/error_handling.hpp, wrappers/src/query_cs.cpp
=> Add geospatial ctor validations

CHANGELOG.md, Realm/Realm.UnityWeaver/UnityWeaver.cs
Fixes https://github.com/realm/realm-dotnet/issues/3363
=> Fix NRE on Unity in batch mode

CHANGELOG.md, Realm/Realm/Native/AppConfiguration.cs, Realm/Realm/Sync/App.cs, Realm/Realm/Sync/AppConfiguration.cs, Tests/Realm.Tests/Sync/AppTests.cs, wrappers/src/app_cs.cpp
=> Deprecate LocalAppName and LocalAppVersion

Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
=> Add a test for verifying sync log level changes

CHANGELOG.md, Realm/Realm/Native/Schema.cs, Realm/Realm/Schema/Property.cs, Tests/Realm.Tests/Database/AsyncTests.cs, Tests/Realm.Tests/Database/CollectionTests.cs, Tests/Realm.Tests/Database/RealmSetTests.cs, wrappers/src/schema_cs.cpp, wrappers/src/schema_cs.hpp
Fixes https://github.com/realm/realm-dotnet/issues/3149
=> Pass public_name down to Core

Realm.sln.DotSettings, Tests/Realm.Tests/Database/CollectionTests.cs, Tests/Realm.Tests/Realm.Tests.csproj
Fixes an incorrect assertion where we were asserting on the wrong collection and cleans up the code a little. Make sure to review with whitespace off since I moved the namespace to a file-scoped syntax.
=> Fix incorrect assertion and cleanup CollectionTests.cs

Realm/Realm/Linq/IRealmCollection.cs
Fixes https://github.com/realm/realm-dotnet/issues/2546
=> Fix some API docs for notifications

CHANGELOG.md, Realm/Realm/Dynamic/DynamicObjectApi.cs
=> Fix MissingMemberException calls

Realm/Realm.Weaver/Analytics/Analytics.cs
=> Fix trailing comma when there are no features to analyze

Realm/Realm/Attributes/MapToAttribute.cs
=> Fixed documentation of `MapTo`

CHANGELOG.md
=> Update Core to 13.23.4

CHANGELOG.md
=> Updated core to v13.25.1

.github/templates/pr.yml, .github/workflows/pr.yml, Tests/Tests.Android/Properties/AndroidManifest.xml
This PR updates the target version of Tests.Android, to fix an error on CI due to the image updates on the GitHub runners
Fixes #3508
=> Updated target Android version on test

.github/templates/pr.yml, .github/templates/test-net-core.yml, .github/workflows/pr.yml, .github/workflows/test-net-core.yml
Fixes an issue on CI - https://github.com/realm/realm-dotnet/actions/runs/7812830018/job/21313094096?pr=3513
=> Test to fix CI

CHANGELOG.md
=> Upgrade to Core 14.5.1

CHANGELOG.md, Realm/AssemblyInfo.props, Realm/Realm.Unity/package.json
=> Prepare for 12.0.0

CHANGELOG.md
=> Update to Core 14.6.1

CHANGELOG.md, Realm/AssemblyInfo.props, Realm/Realm.Unity/package.json
=> Prepare for 12.1.0

.github/templates/test.lib.yml, .github/workflows/test-android.yml, .github/workflows/test-code-coverage.yml, .github/workflows/test-ios.yml, .github/workflows/test-macos.yml, .github/workflows/test-net-core.yml, .github/workflows/test-net-framework.yml, .github/workflows/test-source-generation.yml, .github/workflows/test-tvos.yml, .github/workflows/test-unity.yml, .github/workflows/test-uwp-managed.yml, .github/workflows/test-weaver.yml, .github/workflows/test-woven-classes.yml
=> RNET-1130: Fail action if tests aren't passing

CHANGELOG.md, Realm/AssemblyInfo.props, Realm/Realm.Unity/package.json, Tests/Realm.Tests/Sync/UserManagementTests.cs
=> Prepare for 12.2.0

Tests/Realm.Tests/Database/NotificationTests.cs, Tests/Realm.Tests/Database/TestNotificationObject.cs, Tests/Realm.Tests/Generated/Realm.SourceGenerator/Realms.SourceGenerator.RealmGenerator/TestNotificationObject_generated.cs
Adds to the notification tests to track behavior of collection listener for updates on embedded links.
=> Test collection listener for updates on embedded object

.github/pkl-workflows/publish-release.pkl, .github/workflows/prepare-release.yml, .github/workflows/publish-release.yml
=> Add `no-jira-ticket` to release PRs.

Realm/Realm/Logging/Logger.cs, Tests/Realm.Tests/Sync/DataTypeSynchronizationTests.cs, Tests/Realm.Tests/Sync/SynchronizedInstanceTests.cs
=> Fix a warning and Unity build

CHANGELOG.md, Realm/AssemblyInfo.props, Realm/Realm.Unity/package.json
=> Prepare for 12.4.0

CHANGELOG.md, Realm/AssemblyInfo.props, Realm/Realm.Unity/package.json
=> Prepare for 20.0.0
